### ISSUE TITLE
Plugin host terminated unexpectedly

### ISSUE THREAD

**Issue by felixfbecker** [DonJayamanne/gitHistoryVSCode#10]
VS Code crashes on startup with this extension

![image](https://cloud.githubusercontent.com/assets/10532611/13143680/e922aeba-d645-11e5-8d04-4603ea2e4419.png)

**Comment by DonJayamanne** [comment]
Hi, are you still getting  this error. Vs code can't crash upon startup sure this extension. This extension gets activated only you use the relevant commands.

Please retest.

**Comment by felixfbecker** [comment]
Couldnt reproduce anymore. Think it was VS Code bug.
