### ISSUE TITLE
Error: spawn git ENOENT

### ISSUE THREAD

**Issue by dapidmini** [DonJayamanne/gitHistoryVSCode#100]
I keep getting this error message: `Error: spawn git ENOENT` when I try to view git history log for a private repository that I'm contributing to.
![image](https://cloud.githubusercontent.com/assets/1236612/23497025/dcadd406-ff53-11e6-9e4b-9cc956aa05f0.png)

P.S. I have git desktop and git shell already installed on my local computer because I've been using git desktop and notepad++ before this. I also have tried caching my git account credential as instructed [here](https://help.github.com/articles/caching-your-github-password-in-git/) and restarted the computer but I'm still getting the same error.
![image](https://cloud.githubusercontent.com/assets/1236612/23497243/c6cd1dda-ff54-11e6-9a06-b3c939795f6f.png)

**Comment by mikes-gh** [comment]
Could you try updating to 0.2.0
It may not fix the issue but this version logs to the output window 'Git History Log which may give us more info.'

**Comment by pechar** [comment]
Have the same problem. Any news of how to fix this?

**Comment by mikes-gh** [comment]
This issue never progressed because we need more info.
Could you paste the contents of the `Git History Log` output window please

**Comment by pechar** [comment]
Below is the response form my log. I'm on Windows 10. VSCode 1.11.0

`[Info -09:09:03.638] git path: falling back to PATH environment variable
[Info -09:09:03.638] git log --format="%n95E9659B-27DC-43C4-A717-D75969757EA5%nrefs=%d%ncommit=%H%ncommitAbbrev=%h%ntree=%T%ntreeAbbrev=%t%nparents=%P%nparentsAbbrev=%p%nauthor=%an <%ae> %at%ncommitter=%cn <%ce> %ct%nsubject=%s%nbody=%b%n%nnotes=%N%n95E9659B-27DC-43C4-A717-D75969757EA1%n" --date-order --decorate=full --skip=0 --max-count=50 --numstat --
[Error-09:09:03.638] Error: spawn git ENOENT
`

**Comment by mikes-gh** [comment]
That would indicate we cant find git 

Could you open a command window (not bash shell) and 

1.  Could you paste the result of `echo %PATH%`
2.  Could you try `git log`

**Comment by pechar** [comment]
Ok solved it! Thanks for the info. The error was not very clear so I couldn't figure it out. Git was not registered in the PATH variable. I would have thought installing GIT in VS Code would have done that. I installed Windows for GIT and switched my terminal to Command Prompt in VS Code. Thanks for your help!

**Comment by mikes-gh** [comment]
OK I guess its not a clear error message.
We should check the path to make sure git is in there.
When you say installing GIT in vscode what do you mean?
Were you expecting vscode to intsall git for you? (it doesnt)

**Comment by pechar** [comment]
Well, since there is embedded source control and it seems to be working well from the interface I would have thought VS Code would have already set it up as part of the default command prompt. However I did notice Powershell seems to be the default in editor console. Not sure if Powershell uses the PATH variable.

**Comment by zxbetter** [comment]
I also get the error.
In the `settings.json` of vscode: 
```
"git.path": "D:\\Git\\bin"
```
all git commands perform well in vscode terminal, except the extension.

when I change the configuration to `"git.path": "D:\\Git\\bin\\git.exe"`, the error disappears.

**Comment by MuhammadaliZoyirov** [comment]
ENOENT: spawn git ENOENT
