### ISSUE TITLE
"Unable to open 'file:///tmp/tmp-26988u9NrabVqM0g4.py ⟷ file:///home/...'"

### ISSUE THREAD

**Issue by apahl** [DonJayamanne/gitHistoryVSCode#101]
Hi, thanks a lot for this great VSCode plugin.

When I try to compare a file from the history against my workfile ("Compare against workspace file"), I
get the above mentioned error. The current file is already opened in the editor.  
"Compare against previous version" does work.

VS Code v1.10.1
Git History v0.1.5
OS: Ubuntu 16.10

Many thanks in advance for your help.

Kind regards,  
Axel

**Comment by janrybka** [comment]
This is applicable also for Windows version. It seems that the path is badly constructed. In following path the project folder is added twice:
1) How it is:
d:/VSCode/angular2-learn/APM - Start/**APM - Start/**app/products/product-list.component.ts
2) How it should be:
d:/VSCode/angular2-learn/APM - Start/app/products/product-list.component.ts

VS Code Version 1.10.1
Commit 653f8733dd5a5c43d66d7168b4701f94d72b62e5
Date 2017-03-02T00:33:15.706Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

Git History v0.1.5
OS: Windows 10

**Comment by mikes-gh** [comment]
Could you try updating to 0.2.0
It may not fix the issue but this version logs to the output window 'Git History Log which may give us more info.'

**Comment by apahl** [comment]
Well, the option "Compare against workspace file" is not present anymore in that version, therefore I can not reproduce the error.

**Comment by mikes-gh** [comment]
We now check to see if the files are present in the commit and dont show options that are not applicable.
Is you repo public so I could test?

**Comment by apahl** [comment]
Yes: [rdkit_ipynb_tools](https://github.com/apahl/rdkit_ipynb_tools)

Thanks a lot for your efforts.

**Comment by mikes-gh** [comment]
Which file/commit are you examining the history for

**Comment by apahl** [comment]
`rdkit_ipynb_tools/tools.py`

I just tried a different repo of mine, there "Compare against workspace file" was shown as option and did work.

**Comment by mikes-gh** [comment]
Which commit please

**Comment by apahl** [comment]
Sorry, `394e1d8`.

But everyone I tried gives the error.

**Comment by mikes-gh** [comment]
Hmm its working for me on a fresh clone.
Using both `Git log` and `Git View File History`.
Could you post your exact steps and the results of the `Git History Log` output window.
![compare to workspace](https://cloud.githubusercontent.com/assets/16208742/23697812/191328e2-03e1-11e7-99ae-82b88256b7a2.png)

**Comment by mikes-gh** [comment]
Could you also do a fresh clone to see if its related to your current working copy.

**Comment by apahl** [comment]
Well, as I mentioned above, I can not reproduce the error anymore, because the option is not shown. I can only select "Compare against previous version" and that works for me, too. But  "Compare against workspace file" is not available as option.

**Comment by mikes-gh** [comment]
Yes but I would still like the steps upto the point you dont see the option and the logs
Otherwise I havent got anything to work off.

**Comment by apahl** [comment]
On a fresh clone of my own repo it works for me, too. Very strange.

**Comment by mikes-gh** [comment]
Do you have `Beyond Compare` or some file diff tool.
Could you do a diff of your fresh clone and you current working copy.
Maybe that might shed some light.

**Comment by apahl** [comment]
That's the funny part: my working copy is currently identical to to the repo, at least according to `git status'
```
git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

I am now suspecting some caching issue in VS Code.

**Comment by mikes-gh** [comment]
https://github.com/mikes-gh/gitHistoryVSCode/blob/master/src/commands/fileHistory.ts#L114

This is the check here that shows or hide the `Compare with Workspace.`
If you have time to debug it would be much appreciated.
Otherwise you could zip your non functioning working copy and google drive it for me to look at.

**Comment by apahl** [comment]
Yup, I did `rm -rf ~/.config/Code`and now it works!!  
It was some caching in VS Code that messed it up.

Thanks a lot for your efforts!

Kind regards,  
Axel

**Comment by apahl** [comment]
Of course, all my settings are now gone, as well :-). Should have a backup somewhere...

**Comment by mikes-gh** [comment]
It would be good if you could post the contents of your .config if you can find a backup.

**Comment by apahl** [comment]
No, I just have a backup of the settings file on my other machine, not of the whole config folder.

**Comment by mikes-gh** [comment]
OK Ill close this then :smile:

**Comment by janrybka** [comment]
I still have the problem (no option to compare with workspace version). 

Where is this ".config" on Windows? 
I've tried to reinstall the plugin but it didn't help and I can't find it {user_dir}\.vscode\

**Comment by mikes-gh** [comment]
Sorry closed this as I had no feedback repoening.
.config is on Linux

https://code.visualstudio.com/docs/customization/userandworkspace

It would be great if you could add your config files here so we can see what is going on

**Comment by mikes-gh** [comment]
Specifically you settings.json would be helpful

**Comment by mikes-gh** [comment]
Sorry and your `Git History Log` output window contents (new feature) 
This will show your git path and git commands

**Comment by janrybka** [comment]
Compare with previous works. Files in attachment. I'll try to clean "Cache" and "CachedData".
[settings.json.txt](https://github.com/DonJayamanne/gitHistoryVSCode/files/827500/settings.json.txt)
[git-history-output.txt](https://github.com/DonJayamanne/gitHistoryVSCode/files/827502/git-history-output.txt)

**Comment by mikes-gh** [comment]
Dont clean yet until we work out whats going on

**Comment by mikes-gh** [comment]
What repo is this I did a search on github but there a few angular-learn repos

**Comment by mikes-gh** [comment]
OK looking at this it may be a cache issue.
Could you clean the cache directories please and report back.

**Comment by mikes-gh** [comment]
You may want to backup `%APPDATA%\Roaming\Code` first but as far as I can see theres not anything that cant be lost in there

**Comment by janrybka** [comment]
I've cleaned "Cache", "CachedData" and also "Local Storage" but nothing has changed. All the same.

**Comment by mikes-gh** [comment]
Could you let me know the repo you are using please ????/angular2-learn

**Comment by janrybka** [comment]
Checked on this one: https://github.com/janrybka/angular2-learn 
File: APM - START\app\products\product-detail.component.ts
Commit: be47b07224e52d0327c1c54c08718f04879c36ae

**Comment by mikes-gh** [comment]
OK works with a fresh clone (see below)

You could go one step further and rename your `%APPDATA%\Roaming\Code` to `%APPDATA%\Roaming\Code.bak`
Then start vscode to see if it resolves your issue (it will recreate a new Code directory with default settings on startup).

DISCLAIMER: Do this at your own risk.  However in my experience you will only lose usersetting and MRU which is usually not a big deal unless you have significantly customised the IDE.

![compare](https://cloud.githubusercontent.com/assets/16208742/23705191/9c1cc9a4-0400-11e7-975a-14b9e4312cd6.png)

**Comment by janrybka** [comment]
I've removed the folder (and updated VS Code to newest) and still the same...

**Comment by mikes-gh** [comment]
But you were already on the latest?

From your previous post
> VS Code Version 1.10.1
Commit 653f8733dd5a5c43d66d7168b4701f94d72b62e5
Date 2017-03-02T00:33:15.706Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by mikes-gh** [comment]
Ah sorry just saw new release today

**Comment by mikes-gh** [comment]
Fresh clone?

**Comment by mikes-gh** [comment]
@janrybka  Please try a fresh clone (for debugging purposes) and report back.

**Comment by janrybka** [comment]
I'm going for vacation now. I'll try it and report back next week. Thanks.

**Comment by DonJayamanne** [comment]
Fixed in latest release
