### ISSUE TITLE
Crashes 1.11 insiders

### ISSUE THREAD

**Issue by pocesar** [DonJayamanne/gitHistoryVSCode#102]
I'm not being able to get the stack or anything from it, but the latest insiders is crashing when clicking "Git: View File History" quite consistently.

**Comment by DonJayamanne** [comment]
Does it work in the stable version?

**Comment by DonJayamanne** [comment]
@pocesar any update on this?

**Comment by pocesar** [comment]
it didn't happen with newer versions of insiders, so I guess it was a transient problem
