### ISSUE TITLE
How to specify the project folder you want？

### ISSUE THREAD

**Issue by zysidea** [DonJayamanne/gitHistoryVSCode#103]
Hello, it looks like that the "View file history" is for the current project floder. I am a golang developer, golang's project folder is not the same as any other language.There are many different project in the "src" floder,so many different git repository.So show error when i used the command "View file history",but it worked when i only open the specific project folder.
Hope to be resolved，thanks!

**Comment by mikes-gh** [comment]
Could you post the error please and attache a copy of the output window `Git History Log`
This will show what git commands are being used.
As far as I know we should cope with repos that are not the root of the project.
We find the git repo path form the file chosen so it should work.

**Comment by zysidea** [comment]
I use "Git History Log" in the root of project or the root of specific project, the error is : <br>
`[Info -10:27:26.173] git log --format="%n95E9659B-27DC-43C4-A717-D75969757EA5%nrefs=%d%ncommit=%H%ncommitAbbrev=%h%ntree=%T%ntreeAbbrev=%t%nparents=%P%nparentsAbbrev=%p%nauthor=%an <%ae> %at%ncommitter=%cn <%ce> %ct%nsubject=%s%nbody=%b%n%nnotes=%N%n95E9659B-27DC-43C4-A717-D75969757EA1%n" --date-order --decorate=full --skip=0 --max-count=50 --numstat --
[Error-10:27:26.369] fatal: Not a git repository (or any of the parent directories): .git`

**Comment by mikes-gh** [comment]
Is the issue with `VIew File History` or `Git History Log`?
You mention both but they work differently in the way they find the repo root.
`VIew File History` has some context to work with.
`Git History Log` will use the folder you opened the project with.

**Comment by zysidea** [comment]
Both are  not work with the project floder of golang

**Comment by zysidea** [comment]
Hi, you can try to make a test with the golang, thanks!

**Comment by mikes-gh** [comment]
Do you have a repo that is public that I can test

**Comment by zysidea** [comment]
yes, https://github.com/zysidea/taskmanager.git @mikes-gh

**Comment by mikes-gh** [comment]
It works for me are you opening at the project root?
![git log](https://cloud.githubusercontent.com/assets/16208742/23952708/25d8d46a-098a-11e7-9b9e-e050e2790339.png)
![git view file history](https://cloud.githubusercontent.com/assets/16208742/23952709/2787c140-098a-11e7-9bcf-f05d3f171351.png)

**Comment by zysidea** [comment]
![ ](http://ofcnzxaa4.bkt.clouddn.com/github_vscode_issue.png)

**Comment by zysidea** [comment]
This is the project folder of golang, every project in the src is a repo

**Comment by zysidea** [comment]
I thinks the probleam is that "gitHistoryVSCode" only load the root repo

**Comment by mikes-gh** [comment]
I see you are opening below the the repo root.
I just tested and get the same error as you.
However  `Git View File History` should still work as that has the context of the current file to work from.

The problem we have here is that there is no concept of a current directory AFAIK in vscode.
So how does `Git Log` know which repo to use?
By the way that is a genuine question.  What would indicate which repo you are working on?

**Comment by mikes-gh** [comment]
BTW vscode without gitHistory doesnt like opening mutiple repos under one folder.
Click on the git icon on the left and do you get 
![not a git repository](https://cloud.githubusercontent.com/assets/16208742/23959018/d7b41116-099b-11e7-9f57-b23c11ae05e0.png)

**Comment by mikes-gh** [comment]
I just thought we could add a right click for `Git Log`
Would this work for you?

`Git Log` at the command bar level might work if we can find a context that works for example the currently opened window?

Note you still wont be able to use any of vscode's built in git commands with your setup.
It seems vscode is designed to work at the repo root level as well.

**Comment by zysidea** [comment]
Yes, i know the vscode design,so i always use git command.  It will be a good idea that dd a right click for `Git Log`. Thanks @mikes-gh

**Comment by mikes-gh** [comment]
IN the previous post you said `View File History` didn't work either.
I am confused on this one as that should work as it has context?

**Comment by zysidea** [comment]
This command can show the history under the command window,but show error if you click it to see detail

**Comment by mikes-gh** [comment]
Got it thanks for picking this up.
