### ISSUE TITLE
Respect editor font-size (and other font) settings

### ISSUE THREAD

**Issue by medikoo** [DonJayamanne/gitHistoryVSCode#105]
It'll be great if git history log is show with respect to editor font settings.

Currently if someone's setup differs from default significantly, there's a big contrast:

![screen shot 2017-03-15 at 08 46 13](https://cloud.githubusercontent.com/assets/122434/23938270/e268f4ea-095b-11e7-929a-c11f29b5a3ee.png)

**Comment by ole1986** [comment]
since version 0.4.8 this should be resolved
