### ISSUE TITLE
refactor using express and react

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#108]
@mikes-gh 
I'm planning on re-writing the code in the [browser](https://github.com/DonJayamanne/gitHistoryVSCode/tree/master/src/browser) folder using [react.js](https://facebook.github.io/react/) and using [express](https://expressjs.com/) (to act as the web server that will serve the browser content)

You can find an example of such an implementation here [vscodeJupyter](https://github.com/DonJayamanne/vscodeJupyter/tree/master/browser). This is another extension I've developed.

The benefit is simple - its easier to manage and extend. E.g. extend the UI to add filtering, sorting, etc and other features. 

You've been doing a great job at maintaining this repo. I don't want to go around making major changes unless you're comfortable. Bulk of the code remains the same (all that changes is the code in the browser folder, code used to get git repo, launching diff, etc - all of that remains intact).

Please let me know your thoughts on using Express and React for the browser component (component used to render the UI).

Note: The reason for this change (refactor) is to get started on extending the UI to add searching, and other UI changes (in other issues).

**Comment by mikes-gh** [comment]
That's a really good idea.  It will also be a unique feature amongst extensions :smile: 

I had a good idea on caching (which could be done separately).
When we spawn git log we could cache the log entires and use the last commit hash as a dirty flag for subsequent webapi calls.
That way we could serve the commits from memory to be very fast serving via express.

I would say this will probably require some backend rewriting for the express webapi to serve the page.

**Comment by DonJayamanne** [comment]
excellent, i'll start on this asap on a separate branch. 
I'll try to leave most of the backend untouched (adding adapters to the web api to use the existing code), later we can clean it up.

**Comment by DonJayamanne** [comment]
Will keep this open to for discussions related to piece of work.
Phase 1 will be to get a same functionality with react+express, later we extend it to add more features.

Oh yes, please do feel free to jump in and make changes or comment on the code (specifically with the react code) if you have any suggestions/questions, etc...

**Comment by DonJayamanne** [comment]
fyi, branch created - https://github.com/DonJayamanne/gitHistoryVSCode/tree/reactexpress

**Comment by mikes-gh** [comment]
Sounds good.  BTW I'm not precious about any of the code I wrote if there is a better way.  I'll happily  test or review.  Unfortunately I don't know react but I guess I can learn :smile:

**Comment by DonJayamanne** [comment]
you can learn easily. Thanks.

**Comment by mikes-gh** [comment]
I just had a look reminds me a bit of razor for c#.  
Sort of like a templating language.
Am I getting the idea?

**Comment by DonJayamanne** [comment]
Yes and no. Yes there is Markup with inline expressions, but all of that is provided in code. Think of it as returning your Markup (html) from within c# code. Also these are not real html elements, but placeholders that the react rendering engine understands , to inturn generate the actual mark up.

**Comment by aberonni** [comment]
Hi there, happy to give a hand on this if needed. I'm just looking for ways to contribute to this repo.

I opened #207 because I noticed that issue was marked as "good first issue" but I'm having a hard time trying to understand how to build and run locally so I opened #208.

The idea of integrating React + express is pretty cool so maybe I could give a hand with that if you can help me out on #208.

**Comment by DonJayamanne** [comment]
>The idea of integrating React + express is pretty cool so maybe
This has been completed.

**Comment by DonJayamanne** [comment]
> Hi there, happy to give a hand on this if needed. I'm just looking for ways to contribute to this repo.

Please feel free to contribute in any way possible.
There are a number of issues and plenty of areas of improvement.
