### ISSUE TITLE
no commits is not a fatal error

### ISSUE THREAD

**Issue by vilinski** [DonJayamanne/gitHistoryVSCode#109]
Actually not yet having commits isn't a fatal error, is it? Sure it happens only once, but isn't it better to show an info about instead of any fatality?

```
[Info -09:37:53.882] git path: C:\Program Files\Git\bin\git - from registry
[Info -09:37:53.883] git log --format="%n95E9659B-27DC-43C4-A717-D75969757EA5%nrefs=%d%ncommit=%H%ncommitAbbrev=%h%ntree=%T%ntreeAbbrev=%t%nparents=%P%nparentsAbbrev=%p%nauthor=%an <%ae> %at%ncommitter=%cn <%ce> %ct%nsubject=%s%nbody=%b%n%nnotes=%N%n95E9659B-27DC-43C4-A717-D75969757EA1%n" --date-order --decorate=full --skip=0 --max-count=50 --numstat --
[Error-09:37:53.971] fatal: your current branch 'master' does not have any commits yet
```

**Comment by mikes-gh** [comment]
Yes.  You are right this needs tightening up

**Comment by mikes-gh** [comment]
BTW its git that considers this fatal not us.

**Comment by vilinski** [comment]
well.... nevermind then

**Comment by mikes-gh** [comment]
I hope I didnt offend?
Not saying we wont downgrade this to INFO but just wanted to point out it is git that says this is fatal :smile: 
If you do a git log at the command line with no commits you will get that exact same message.

**Comment by vilinski** [comment]
not at all :)
Don't know whether its simple to recognize this particular message as an info instead of error and maintain this little hack through eternity.
I always ignored it in the console, errors are looking not such scary here.

**Comment by DonJayamanne** [comment]
Closing this issue for now due to inactivity
