### ISSUE TITLE
Usage is complicated

### ISSUE THREAD

**Issue by zevero** [DonJayamanne/gitHistoryVSCode#11]
Hey I like gitHistory a lot!

But I have to
```
press F1
type Git
select Git: View History
select either Line or File
```

which is rather inconvenient...

gitBlame plugin just displays a line in the footer ... this is very nice, but insufficient.

I wonder if there is something inbetween?
I would love to have a small status in the footer, with two buttons for file and line history.

Or at least instructions for a keyboard shortcut

**Comment by DonJayamanne** [comment]
Key board short cut is easy. I will update the documentation later during the weekend. And we'll look into the other suggestions. Thanks.

**Comment by DonJayamanne** [comment]
Please check the latest version.
