### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by noChamp** [DonJayamanne/gitHistoryVSCode#110]
hi
i would like to ask for mouse support.
i would like to right click a file and select 'view history'.
same for right clicking a folder, branch etc...
thanks
M>

**Comment by mikes-gh** [comment]
I am probably misunderstanding this but isn't this is already supported in vscode explorer.
Right click file then select `Git: View File History`

**Comment by noChamp** [comment]
hi
thanks for reviewing my comments !
I expected that after right clicking a file - I would get a windows where I could select 2 revisions and compare them. today I can only select to compare a revision with the current working file or the previous revision.
thanks again
M>

**Comment by DonJayamanne** [comment]
Fixed in latest release.
Viewing by rightclicking a folder and branch not added though.

**Comment by noChamp** [comment]
hi
thanks for your effort !!
:)
👍
