### ISSUE TITLE
Provide access to commit diff via history log

### ISSUE THREAD

**Issue by medikoo** [DonJayamanne/gitHistoryVSCode#111]
When click on item in log, all I got is brief info on what files have been changed in that commit.
It would be great to also provide a mean to open a diff for given commit (can be in another window).

e.g. in Emacs this the feature that works great, through neat git log I can get to diff for any commit. It's very useful, and now I strongly miss it in VSC

![screen shot 2017-03-20 at 11 21 16](https://cloud.githubusercontent.com/assets/122434/24095888/71e9d74a-0d5f-11e7-9eb7-c75b48078c1a.png)

**Comment by DonJayamanne** [comment]
@medikoo 
Clicking the individual file (from within the list of files) in the list will provide a list of options (e.g. view file, compare against local version, compare against previous version, etc).

**Comment by medikoo** [comment]
@DonJayamanne thanks, indeed.

Still access is a bit cumbersome, as after clicking the message in log, I still need to take following steps to access diff for singular file:
1. Navigate with mouse to filename
2. Click
3. Navigate with mouse (or click 4 times down arrow) to option "Compare against previous version",
4. Click (or press enter).

Then I need to repeat it, if want to see differences in other file. It's far from good.

It'll be great to have some sort of shortcut on log, so clicking on it (can be via context menu) I can see a git-diff for given commit (covering all changed files). It's what e.g. Emacs provides via one keystroke:

![emacs-log-diff 5](https://cloud.githubusercontent.com/assets/122434/24097999/b0fbedb6-0d68-11e7-850b-57285295052e.gif)

**Comment by DonJayamanne** [comment]
Closing as this isn't related to this extension.

**Comment by medikoo** [comment]
> Closing as this isn't related to this extension.

How come? Can you share a bit more details? You don't have control over what happens when user clicks on history item?

**Comment by DonJayamanne** [comment]
This isn't something built by this extension. You've got the wrong repo.

**Comment by DonJayamanne** [comment]
Oops, sorry.

**Comment by DonJayamanne** [comment]
This feature is available today:
* Open history
* Select an item form the history view
* Look at the explorer view, you'll find a view named `COMMITS`

![view](https://user-images.githubusercontent.com/1948812/35499647-2cc1a9c4-0488-11e8-82e8-e522a3d36829.gif)

**Comment by medikoo** [comment]
Thanks @DonJayamanne 
It's indeed a big improvement. Still it's not as convenient as browsing whole commit diff in one window.

Imagine case when we have some small changes done in three big files. With one diff it can fit one screen (and this is what you get on Emacs or Vim), and with that you instantly see what has been done.
While in case of this extension: first you get list of files, and then the only option is to inspect files individually, where if file is big, you need to browse whole content to see the changes. That's not great UX wise. So time taken to see all changes is significant.
