### ISSUE TITLE
Error when trying to view history of moved file

### ISSUE THREAD

**Issue by Goblinlordx** [DonJayamanne/gitHistoryVSCode#113]
When looking at the `file history` it actually shows these properly.  The problem is when I try to select one of the entries before the file was moved, it tries to access the same file name but at the newest location.  What I would expect to happen is it would try to open the file location of the selected commit (which should prevent this error).

**Comment by mikes-gh** [comment]
Just to be clear is this on the html page( `Git Log`? Or using `Git: View File History`

**Comment by Goblinlordx** [comment]
Git: View File History

**Comment by mikes-gh** [comment]
Thanks for confirming

**Comment by Goblinlordx** [comment]
Actually, just a note on this, after you mentioned "Git Log".  I tried there and when it lists the files there it does have the newest location displayed.  This is fine I think, it also opens the file from "Git Log" perfectly fine.  I when I said it should "try to open the old location" I think I just don't have a full understanding of how git stores old commits.  Anyways, I am sure you can figure it out ^^.

As an aside note, I want to express my appreciation for your effort in maintaining this plugin.  It is absolutely awesome and I can't thank you enough for it~

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version. Please retest and open if the problem persists.
