### ISSUE TITLE
Wrong display of the encoding of the text

### ISSUE THREAD

**Issue by aragorlum234** [DonJayamanne/gitHistoryVSCode#116]
After last update 1.11.1 of Visual Studio Code comment on russian language in the commited file is displayed incorrectly.
Picture1 - Index vs. Working Tree
On the right side russian comment is correct.
![picture1_index vs working tree](https://cloud.githubusercontent.com/assets/2423818/24798941/5cc4c668-1ba1-11e7-9736-e8600dacb20c.PNG)

Picture2 - HEAD(staged) vs. Index
![picture2_head vs index](https://cloud.githubusercontent.com/assets/2423818/24798970/7a82cb6e-1ba1-11e7-9858-b106dcb3648b.PNG)

In settings "files.encoding": "windows1251"

**Comment by mikes-gh** [comment]
Just to clarify it worked in 1.10.2?

**Comment by DonJayamanne** [comment]
If it worked in the older version, please could you confirm this by installing the old vscode version and giving it a go.
https://code.visualstudio.com/updates/v1_10

If it does work in the old version, then we can report this issue to the VSCode team at msft

**Comment by aragorlum234** [comment]
I've installed previous version of VS Code.

![vs code 1 10 2](https://cloud.githubusercontent.com/assets/2423818/24847560/54a56426-1dca-11e7-9442-d7301b3b8909.PNG)
Now it works correctly.

![picture3_head vs index_old_version vs code 1_10_2](https://cloud.githubusercontent.com/assets/2423818/24847633/ce171192-1dca-11e7-9d68-578fcda2b47c.PNG)

**Comment by aragorlum234** [comment]
After update 1.11.2 the problem has remained.

**Comment by aragorlum234** [comment]
"SCM: Disable Preview SCM" has solved the problem. By default SCM preview has been enabled.
