### ISSUE TITLE
Feature request: don't lose context when opening file comparison

### ISSUE THREAD

**Issue by warpdesign** [DonJayamanne/gitHistoryVSCode#122]
How to reproduce?
--
1. Open the `view history (git log)`
2. Scroll down a little and select a commit: it is highlighted in green and files changed appear at the bottom
3. Select one of the modified file and choose `Compare against previous version`: the two versions are opened side by side
4. Now close one of the files: you get back to the `view history (git log)` but it's reloaded, so you don't know what commit you selected before

Suggestion
--
When opening the comparison tabs and getting back to view history, do not lose context: keep the previous commit selected and the scroll to the previous position

**Comment by ajaygm** [comment]
Refer #51 for more details.

**Comment by DonJayamanne** [comment]
Fixed in latest release
