### ISSUE TITLE
don.jayamanne@yahoo.com in user tooltip

### ISSUE THREAD

**Issue by adambowles** [DonJayamanne/gitHistoryVSCode#127]
Hovering over username shows two tooltips, one with correct email, one with don.jayamanne@yahoo.com:

![screenshot from 2017-05-30 10-38-50](https://cloud.githubusercontent.com/assets/10128574/26577460/5a1f6f2e-4524-11e7-86e0-89595c056933.png)

**Comment by DonJayamanne** [comment]
Lol..bug, will fix soon

**Comment by ajaygm** [comment]
@adambowles @DonJayamanne Don't see this issue (the second tooltip with Don's email id) in the latest version of the plugin (0.2.2). 

Is it already fixed?

I do see a line of code with the email id still present...
https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/logViewer/htmlGenerator.ts#L63

```            
<div class="commit-author">
	<span class="name hint--right hint--rounded hint--bounce" aria-label="don.jayamanne@yahoo.com">Don Jayamanne</span>
	<span class="timestamp">on Feb 22th 2016, 12:21:43 am</span>
</div>
```

**My versions...**
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:34:09.706Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by adambowles** [comment]
I don't get this extra tooltip at the moment either

- vscode: v1.14.1
- gitHistoryVSCode: v2.2.0
