### ISSUE TITLE
Git log always needs to reload when clicking on file difference

### ISSUE THREAD

**Issue by BorntraegerMarc** [DonJayamanne/gitHistoryVSCode#128]
My use case:
1. I view the git logs
2. I see a commit that interests me and click on it
3. I compare a file with its previous version
4. Done comparing and I switch back to the git logs
5. Git log needs to reload and it takes some time

Better would be if the git log would update async and the user would not even notice it. The waiting in step 5 is quite annoying if you compare a lot of files

**Comment by dwarburt** [comment]
Not only does it take some time, but the commit you had selected is now deselected and you have to find it again in the list.

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version
