### ISSUE TITLE
Git Log does not show future commits

### ISSUE THREAD

**Issue by CoenraadS** [DonJayamanne/gitHistoryVSCode#129]
```
commit C
commit B
commit A
```

If I checkout commit B, I can no longer see commit C in Git Log.

I suggest use `git log --all`, and then highlight the current checkedout commit

**Comment by atk** [comment]
It would be great to have a config option; the required attributes are already mentioned inside a comment here: https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/helpers/gitHistory.ts#L14
