### ISSUE TITLE
File History wrong – showing commits from before file was created?

### ISSUE THREAD

**Issue by peabnuts123** [DonJayamanne/gitHistoryVSCode#130]
Viewing the history of files in my project seems to be producing incorrect results. The file in particular that I installed this extension to investigate is showing the latest revision, the commit wherein the file was added, and then 2 other seemingly random commits. I am unsure what this is about. Executing `git log -- path/to/file` is only showing the 2 commits (edited, created) which I expected. 

I can supply more details / some screenshots etc. but will need to censor them and thus would like to know exactly what is needed before doing so. 

Furthermore, in what may potentially be a separate issue, attempting to view the commit in which the file was created (and the other 2 commits) says in the console: 
```
[Error-10:46:59.935] fatal: Path 'path/to/file.js' exists on disk, but not in 'ac2db701d59f6fbd54fc5125c78a881d97fc3d74'.
```

**Comment by ole1986** [comment]
Possible duplicate #135

**Comment by peabnuts123** [comment]
Certainly could be sharing a root cause. My files have not moved on disk, however

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version
