### ISSUE TITLE
Add Branch Name to Line History Cards

### ISSUE THREAD

**Issue by EthanMelamed** [DonJayamanne/gitHistoryVSCode#134]
Hello,

Please add the branch names to their latest commit in the line history. Having the remote and local branches would be very helpful! I am a source tree user but I would like to use this plug-in instead. Only the branch name indicators are a feature that is hard to give up!

Thank you!
Ethan

**Comment by ole1986** [comment]
It is supposed to be in with version 0.2.1.
Another PR which fixes an issues is available in #136

**Comment by ole1986** [comment]
I think this issue can be closed as it is implemented since v0.2.1
