### ISSUE TITLE
Fatal Path - Can't View History

### ISSUE THREAD

**Issue by spottedmahn** [DonJayamanne/gitHistoryVSCode#135]
I'm trying to view the history of a file and I'm receiving:

> [Error-15:17:49.045] fatal: Path 'myApp/src/app/shared/some.service.ts' exists on disk, but not in '173117caadaf695404a3f6b99005806a4c854e5f'.

I think this file was under a **different path** for the commit I'm trying to review.  Is that a known limitation of this extension?

**Comment by ajaygm** [comment]
I remember having received a similar error (and I had saved the log to report the bug) ...
```
[Info -12:56:03.033] git log --no-abbrev-commit --max-count=10 --decorate=full --date=default --pretty=fuller --all --parents --numstat --topo-order --raw --follow --before='2017-07-12T07:39:40.000Z' -- template/default.css
[Info -12:56:03.115] git rev-parse --show-toplevel
[Info -12:56:03.161] git repo path: c:/TestPCs
[Info -12:56:03.163] git show 95ef62ec24938908e048f1390b873e37f16dc61e:template/default.css
[Info -12:56:03.167] git show cfeb653ebf4c83f3b286aa0b0c2af17aa9a6e71b:template/default.css
[Error-12:56:03.217] fatal: Path 'template/default.css' exists on disk, but not in 'cfeb653ebf4c83f3b286aa0b0c2af17aa9a6e71b'.
[Error-12:56:03.217] fatal: Path 'template/default.css' exists on disk, but not in 'cfeb653ebf4c83f3b286aa0b0c2af17aa9a6e71b'.

```
I think it was about a newly added file to a local branch that has not been pushed to remote. If I remember correctly the diff was working fine from outside the plugin but the plugin used to fail with this error.

@spottedmahn Can you try to detail out the steps to reproduce this issue? I think it was easily reproducible.
