### ISSUE TITLE
No command works with Windows non-ASCII user.

### ISSUE THREAD

**Issue by astafev** [DonJayamanne/gitHistoryVSCode#137]
Just installed the extension, tried few commands, all gave errors:
```
[Info -11:48:24.046] git path: C:\Users\�������\AppData\Local\Programs\Git\bin\git - from registry
[Info -11:48:24.047] git rev-parse --show-toplevel
[Error-11:48:24.048] Error: spawn C:\Users\�������\AppData\Local\Programs\Git\bin\git ENOENT
[Error-11:48:24.048] Error: spawn C:\Users\�������\AppData\Local\Programs\Git\bin\git ENOENT
[Info -11:48:24.049] git repo path: c:\Aurea\monitoring\aurea-saas-monitoring\selenium-js\alss
[Info -11:49:13.656] git rev-parse --show-toplevel
[Error-11:49:13.657] Error: spawn C:\Users\�������\AppData\Local\Programs\Git\bin\git ENOENT
[Info -11:49:13.659] git repo path: c:\Aurea\monitoring\aurea-saas-monitoring\selenium-js\alss
```
Default git integration in VS Code works fine, use it all time. There's my username: Евгений.

**Comment by ole1986** [comment]
Seems to be an issue receiving the unicode path properly from the registry in gitPath.ts
A possible workaround is to install your git client into an alternative folder instead or try define the git.path in your user settings:

```
{
    "git.path": "C:\Users\ Евгений\AppData\Local\Programs\Git\bin"
}
```

**Comment by astafev** [comment]
@ole1986 thanks. Something started to work with settings update (not everything though works as I would expect). Just one thing - git path should be a bit different:
`"git.path": "C:\\Users\\Евгений\\AppData\\Local\\Programs\\Git\\bin\\git.exe"`

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version
