### ISSUE TITLE
Feature Request: Compare Branches

### ISSUE THREAD

**Issue by Aaron-Zhao** [DonJayamanne/gitHistoryVSCode#138]
One of the features provided already is: View a previous copy of the file or compare it against the local workspace version or a previous version.

If somehow, this can be extended to "compare two **branches** for all files changes, and being able to compare files side by side", would be awesome!

Diff files will be shown as a list, by clicking each file it will bring up windows compare the files from two branches side by side with highlights.

**Comment by icetbr** [comment]
This was added in the plugin latest version (0.2.3)

**Comment by pprochnicki** [comment]
that's great, but how to do it?

**Comment by DonJayamanne** [comment]
Open the git history viewer. For each commit, look for the commit icon (far left), clicking on that will display a prompt to select a commit to compare.
E.g. if you wish to compare branch A and B, then select commit for the head commit of A, then select the head commit of B for comparison.

**Comment by DonJayamanne** [comment]
FYI - The UI will be polished and most bugs fixed in the next upcoming version.
