### ISSUE TITLE
command 'git.viewHistory' not found

### ISSUE THREAD

**Issue by TaylorPzreal** [DonJayamanne/gitHistoryVSCode#139]
OS: MAC OS
After i installed git-history, i use ```command+shift+p``` to select ```view history(git log)```,got an error:
```command 'git.viewHistory' not found```

**Comment by alvaromunoz** [comment]
Seems to be fixed in 0.2.2

**Comment by Oikio** [comment]
Good day, same error on Windows 10. 
`VSCode 1.20.0`, `git history extension 0.4.0`, `git version 2.14.2.windows.1.`
Also I'm using Ubuntu terminal with fish in case it might affect this issue:
```
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe",
  "terminal.external.windowsExec": "C:\\WINDOWS\\Sysnative\\Ubuntu.exe",
```

**Comment by lcruz4** [comment]
This issue seems to have come back. I'm also getting the issue. Tried reinstalling and reloading vs code. I'm using 1.19.3 git history 0.4.0 git version 2.13.2.windows.1

**Comment by DonJayamanne** [comment]
@lcruz4
Please disable all extensions except for Git History and try once again.

**Comment by lcruz4** [comment]
@DonJayamanne same issue after disabling everything. Just updated to vsCode to 1.20.0 and it still has the same issue.

**Comment by DonJayamanne** [comment]
@lcruz4
Please create a separate issue with the following info:
* Output from `Git History` output panel
* Output from `console window` (got into Help->Toggle Developer Tools)
