### ISSUE TITLE
Cannot set property 'previousSha1' of undefined

### ISSUE THREAD

**Issue by blopez2010** [DonJayamanne/gitHistoryVSCode#142]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.6.0

Going to git history log, if I click on one of the commit tree I will see the files changed on it. If I click on one of them I'm getting this error:

`[Info -08:39:55.004] git log --no-abbrev-commit --max-count=10 --decorate=full --date=default --pretty=fuller --all --parents --numstat --topo-order --raw --follow --before='2017-07-25T00:21:45.000Z' -- ng-ui/test/spec/app/reservation/modify_reservation/undocheckoutmodal-controller.spec.js
[Error-08:39:55.566] TypeError: Cannot set property 'previousSha1' of undefined`

**Comment by pavelmorozov** [comment]
Still same error in November

**Comment by DonJayamanne** [comment]
I'll be releasing a new version soon

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version
