### ISSUE TITLE
There was an error, please view details in the 'Git History Log' output window

### ISSUE THREAD

**Issue by skybluefly** [DonJayamanne/gitHistoryVSCode#146]
help!!
why my plugins always throwing this errors ?

**Comment by ajaygm** [comment]
@skybluefly What does the 'Git History Log' output window show?

(You can get there by "Ctrl+J" -> "OUTPUT" tab -> "Git History Log" from the drop down.)

**Comment by skybluefly** [comment]
@ajaygm When I enter the Git History Log command，It does not open the relevant panels~ throwing this error

**Comment by ajaygm** [comment]
@skybluefly If it does not open it automatically that is fine, just do these steps after you have run the command...
1. Type the key combination "Ctrl+J"
1. Select the "OUTPUT" tab
1. Select the "Git History Log" option from the drop down.

**Comment by skybluefly** [comment]
@ajaygm thanks！I had find my answer~~
from 
https://github.com/DonJayamanne/gitHistoryVSCode/issues/100

**Comment by ajaygm** [comment]
@skybluefly OK. So I'm assuming we can close this issue?
