### ISSUE TITLE
Feature Request: Show Stash info

### ISSUE THREAD

**Issue by ajaygm** [DonJayamanne/gitHistoryVSCode#147]
Compare the gitk and vscode git history extension's all branches git log output.
gitk is able to recognize that it is a stash and it can also show the files that are modified in it. That's not the case with this extension.

Steps:
1. make some change to the workspace.
2. stash it
3. see the output of gitk and vscode extension.

gitk screenshot...
![git-stash-gitk](https://user-images.githubusercontent.com/217481/28993205-6634eaa8-79ce-11e7-8377-670afb559048.png)

extension screenshot...
![git-stash-vscode](https://user-images.githubusercontent.com/217481/28993209-8094c774-79ce-11e7-8696-671f5a1f7eb0.png)

**Comment by DonJayamanne** [comment]
Please install this extension pack, it is in there.
https://marketplace.visualstudio.com/items?itemName=donjayamanne.git-extension-pack
