### ISSUE TITLE
Branch of a branch is not shown in log history view

### ISSUE THREAD

**Issue by ajaygm** [DonJayamanne/gitHistoryVSCode#148]
Branch of a branch is not shown in the git log history (all branches) view  if it is not the current branch.

In the example below the branch name is "git-log-file" which is a branch of "git-log-all" branch. 

It is not shown when the "master" branch is the current branch...
![missing-branch-name](https://user-images.githubusercontent.com/217481/28993668-c24ad7f2-79d9-11e7-8d20-dd81c541a98b.png)

The same branch is visible in gitk tool as shown below...
![visible-branch-name__gitk](https://user-images.githubusercontent.com/217481/28993670-c95d09e8-79d9-11e7-8e5d-23e8b146d9d7.png)

The branch is visible if it is your currently selected branch as shown below...
![visible-branch-name](https://user-images.githubusercontent.com/217481/28993675-d81e2f0c-79d9-11e7-93b9-baa7c4f9c7d3.png)

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
