### ISSUE TITLE
Update side bar "Commits" on open and on branch switch

### ISSUE THREAD

**Issue by bm-stschneider** [DonJayamanne/gitHistoryVSCode#153]
It would be cool if the commits collapsible in the side bar would automatically update when I open a repo or a folder with a repo and when I change the branch.

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now

**Comment by bm-stschneider** [comment]
It is now already part of the insider version kind of, and of course there is gitlens.
