### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by whyleee** [DonJayamanne/gitHistoryVSCode#154]
It would be nice to display emoji in commit messages like on GitHub. See [carloscuesta/gitmoji](https://github.com/carloscuesta/gitmoji) 😍

**Comment by Dream4ever** [comment]
Hope it will support emoji.

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
