### ISSUE TITLE
Branch lables truncated at '#' character

### ISSUE THREAD

**Issue by c600g** [DonJayamanne/gitHistoryVSCode#155]
When viewing Git: View History (got log), if a a branch name has the '#' character in it, then the display of the branch name is truncated just before that character.

As an example, we typically name our fix branches associated with a ticket as "origin/fix-#NNNN" where NNNN is the issue number. Git History displays this branch as "origin/fix-".

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
