### ISSUE TITLE
Allow history info to show when in file comparison view

### ISSUE THREAD

**Issue by icetbr** [DonJayamanne/gitHistoryVSCode#157]
If I'm in file view myFile.js, I can see the latest commit message from the line the cursor is on (either with 'show line history' or inline with git lens).

If I'm in comparison view 'myFile (v1) -> myFile (v2)', this info is lost.

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
