### ISSUE TITLE
Error: warning: inexact rename detection was skipped due to too many files.

### ISSUE THREAD

**Issue by alekseysshubin** [DonJayamanne/gitHistoryVSCode#158]
I have just installed Git History and opened my repository in it, and the following error appears:

    warning: inexact rename detection was skipped due to too many files.
    warning: you may want to set your diff.renameLimit variable to at least 2467 and retry the command.

![desktop 08 24 2017 - 18 26 25 05](https://user-images.githubusercontent.com/3538470/29674108-d7b7d138-88f9-11e7-9fe9-bea8f36bc374.png)

The output window's content:

    [Info -18:23:09.402] git rev-parse --show-toplevel
    [Info -18:23:09.442] git repo path: c:/Users/aleks/Documents/Projects/Dashell/dashell.io
    [Info -18:23:09.490] git log --format="%n95E9659B-27DC-43C4-A717-D75969757EA5%nrefs=%d%ncommit=%H%ncommitAbbrev=%h%ntree=%T%ntreeAbbrev=%t%nparents=%P%nparentsAbbrev=%p%nauthor=%an <%ae> %at%ncommitter=%cn <%ce> %ct%nsubject=%s%nbody=%b%n%nnotes=%N%n95E9659B-27DC-43C4-A717-D75969757EA1%n" --date-order --decorate=full --skip=0 --max-count=50 --numstat --summary --
    [Error-18:23:10.248] warning: inexact rename detection was skipped due to too many files.warning: you may want to set your diff.renameLimit variable to at least 2467 and retry the command.
    [Info -18:23:10.271] git log --format="%n95E9659B-27DC-43C4-A717-D75969757EA5%nrefs=%d%ncommit=%H%ncommitAbbrev=%h%ntree=%T%ntreeAbbrev=%t%nparents=%P%nparentsAbbrev=%p%nauthor=%an <%ae> %at%ncommitter=%cn <%ce> %ct%nsubject=%s%nbody=%b%n%nnotes=%N%n95E9659B-27DC-43C4-A717-D75969757EA1%n" --date-order --decorate=full --skip=0 --max-count=50 --numstat --summary --
    [Error-18:23:11.141] warning: inexact rename detection was skipped due to too many files.warning: you may want to set your diff.renameLimit variable to at least 2467 and retry the command.

I'm not quite sure I understand the warning message, but I have searched for it, and it looks like it is normal in a repository with a lot of renames. So probably it shouldn't be treated as an error.

**Comment by phabri** [comment]
git config merge.renameLimit 999999

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
