### ISSUE TITLE
Enhancement: Integrate gitgraph.js

### ISSUE THREAD

**Issue by 4ux-nbIx** [DonJayamanne/gitHistoryVSCode#159]
Hi guys,
Please have a look at [gitgraph](http://gitgraphjs.com/). May be it'll make things a bit easier and nicer.

Cheers,
Roman

**Comment by ajaygm** [comment]
The samples look good...
http://gitgraphjs.com/examples/gitflowsupport.html
http://gitgraphjs.com/examples/index.html

**Comment by DonJayamanne** [comment]
Yes they do, however at this stage I am not looking to integrate this.
