### ISSUE TITLE
Make Treeviews optional?

### ISSUE THREAD

**Issue by dhayab** [DonJayamanne/gitHistoryVSCode#164]
Hi, first of all, thanks for your work!

Can you please add a set of settings parameters to permanently disable the "Commits" and "Compare Commits" treeviews ?

**Comment by DonJayamanne** [comment]
Duplicate https://github.com/DonJayamanne/gitHistoryVSCode/issues/162

**Comment by jsilvermist** [comment]
@DonJayamanne This isn't necessarily a duplicate, as this is asking for a way to disable it completely, whereas the other issue only asks for autohide.

Note: I will probably be disabling this plugin until either option is implemented.
