### ISSUE TITLE
Options to remove | control explorer views

### ISSUE THREAD

**Issue by Esteban-Rocha** [DonJayamanne/gitHistoryVSCode#166]
Hi! it will be a good idea to allow to the user to choose if it wants to display or not these view panels on the explorer.

I know you can hide them but they re appear as soon you update the editor, or switch your project folder, which is totally nuts breaking.

Everything else is rock solid awesome.

**Comment by jtsom** [comment]
Any movement on this? Seems like it could be a simple setting that's added to the user's setting... Very annoying to have to hide these panels every. time. I. open. a. new. window.

**Comment by DonJayamanne** [comment]
This month for sure, working on a new release. Sorry

**Comment by Esteban-Rocha** [comment]
Thanks @DonJayamanne let know if this was implemented, I'm still getting the little nut breaking panel every time, and I could not find an option for this on the new settings panel (if it's there my apologies but i could find that at all)
