### ISSUE TITLE
UI Polish issues

### ISSUE THREAD

**Issue by CoenraadS** [DonJayamanne/gitHistoryVSCode#167]
Hello, I would like to note some UI issues I have encountered. 

1. Confusing branch visualization. Why is the master branch node extending upwards when there is no linking commit there?
![image](https://user-images.githubusercontent.com/5593825/32543591-5c937eea-c476-11e7-9ab6-799211d60028.png)

2. Checked out commit should be highlighted. 

I am at detached head 13a3f21, but this is not visualized.
![image](https://user-images.githubusercontent.com/5593825/32543739-c4778204-c476-11e7-8a29-3af916bd5f8a.png)

3. Don't scroll the panel when clicking on commits.

I maximized the description panel, but now when I click the commits, it automatically scrolls the clicked commit to the top, which then I have to scroll down again if I want to click the next commit.

![image](https://user-images.githubusercontent.com/5593825/32543921-4d4477ae-c477-11e7-8659-d8e864b203c9.png)

**Comment by ole1986** [comment]
I think all the points being asked by the author has been resolved.
The pending point 2. has now been fixed with commit 83942b8
