### ISSUE TITLE
Presence of not top level .gitattribute file with macro definition breaks "view file history"

### ISSUE THREAD

**Issue by antonsoch** [DonJayamanne/gitHistoryVSCode#172]
[Error-10:26:56.590] [attr]normaltext text eol=lf whitespace=space-before-tab,trailing-space not allowed: <path>/.gitattributes:1

As soon as I rename\remove file everything starts to work properly. 
I know that macro definition are supported for top level folder of working tree. However I'm not sure why that prevents extension from showing file history.

Command extension uses work perfectly fine:
"git log --no-abbrev-commit --max-count=50 --decorate=full --date=default --pretty=fuller --parents --numstat --topo-order --raw --follow -- <file path>"

**Comment by DonJayamanne** [comment]
Please could you test the latest version and check if the issue still persists.

**Comment by antonsoch** [comment]
Fixed.
Awesome! Thank you!
