### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by pavelsuraba** [DonJayamanne/gitHistoryVSCode#178]
After VScode Version 1.19.1 update, my CPU is running on full throttle. After some investigation I discovered It's caused by this extension. I had to disable it.

I'm on macOS Sierra 10.12.6

**Comment by DonJayamanne** [comment]
>After some investigation

What was the investigation and what was the outcome? 
This extension doesn't do anything in the background. Almost nothing.

**Comment by NazarYablonskiy** [comment]
@DonJayamanne same problem here. what does it mean `Almost nothing.`? - mining? :)

**Comment by DonJayamanne** [comment]
Please could you test the new version and let me know.
>Almost nothing.? - mining? :)

Nothing, except for running `git` commands in the background.
The `git commands` that are run are printed out in the `Git History` output panel.

Please update to the latest version (0.3.4)

**Comment by DonJayamanne** [comment]
Closing this issue, as the extension does nothing in the background that could cause the CPU to run on full throttle. 
You have to be using the extension (launch the history view for it to do anything), and it merely runs git commands in the background. The extension now displays all commands that have been executed with the time taken (in the `Git History` output window).

Please feel free to open with the following information:
* You could use the following extension to try and identify the issue (https://github.com/weinand/vscode-processes)
