### ISSUE TITLE
File history fails when file has been moved

### ISSUE THREAD

**Issue by leVladimirus** [DonJayamanne/gitHistoryVSCode#181]
Plugin can't open older version of a file if a file has been moved to another folder.
It happening because plugin try to open the older version by current file path, but GIT keep storing the older versions in the initial location. As result we get error that necessary file present in local folder but does not exist in remote repository.

**Comment by DonJayamanne** [comment]
Please could you check this in the latest version.

**Comment by leVladimirus** [comment]
Hello Don,

Thank you for your quick response!
I updated plugin in VSC extensions manager. And unfortunately plugin became inoperational after update. Every time when I invoking the plugin I getting this error:

git rev-parse --show-toplevel
{"stack":"Error: spawn git ENOENT\n\tat exports._errnoException (util.js:1050:11)\n\tat Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:193:32)\n\tat onErrorNT (internal/child_process.js:367:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:80:11)\n\tat process._tickCallback (internal/process/next_tick.js:104:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel


С уважением. / Best regards.
-----------------------------------------
Vladimir Tepikin
Head of IT Infrastructure department
Liberty Insurance (JSC)
Liberty Mutual Insurance Group
Saint-Petersburg, Russian Federation
Phone: +7 812 4494758 +31221
Mobile: +79118116487

**Comment by DonJayamanne** [comment]
@leVladimirus please could you install the latest version and try once again.
Should be fixed by now.

**Comment by leVladimirus** [comment]
Many thanks, Don!
Now works fine.

С уважением. / Best regards.
-----------------------------------------
Vladimir Tepikin
Head of IT Infrastructure department
Liberty Insurance (JSC)
Liberty Mutual Insurance Group
Saint-Petersburg, Russian Federation
Phone: +7 812 4494758 +31221
Mobile: +79118116487
