### ISSUE TITLE
Feature Request: Styles

### ISSUE THREAD

**Issue by CarlosAzocar** [DonJayamanne/gitHistoryVSCode#183]
1. Small padding between the search elements, i think they are very close together 
![captura de pantalla de 2018-01-17 08-28-01](https://user-images.githubusercontent.com/18235355/35042887-3a14b062-fb82-11e7-8134-bab73361b4ce.png)

2. When searching, then clear the search, return to the original state (without losing the guideline of  commits).
**Current result after cleaning:** 
![captura de pantalla de 2018-01-17 08-30-59](https://user-images.githubusercontent.com/18235355/35042996-caa1ce94-fb82-11e7-8d0f-7897dde4834e.png)
**Desired result after cleaning:**
![captura de pantalla de 2018-01-17 08-31-34](https://user-images.githubusercontent.com/18235355/35042998-cac2566e-fb82-11e7-97ee-b05170d2b506.png)

**Comment by DonJayamanne** [comment]
As this is cosmetic hence I'll leave this as a light priority, unless someone else would like to submit a PR  for this.

**Comment by DonJayamanne** [comment]
Oops forgot about the bug with the state. Would be good to create separate issues for each.
