### ISSUE TITLE
git.viewLineHistory not found

### ISSUE THREAD

**Issue by dohyun-cse** [DonJayamanne/gitHistoryVSCode#185]
- OS : windows 10 1709 b16299.192
- VSCode : 1.19.2
- GitHistory : 0.3.2

When I select `git:view line history` from the Command Palette, it gives me error

![image](https://user-images.githubusercontent.com/17425440/35048299-f01a5b48-fbdf-11e7-953f-64bd61d35fa2.png)

Also, it seems that I cannot access to this command via right click button in the editor.

Is this functionality not supported? or is it also a bug?

**Comment by Deguang** [comment]
I have the same issue with macOs.

**Comment by dgrizzla** [comment]
Same here with Windows 10

**Comment by ckang777** [comment]
Same issue for me as well. VS code version 1.19.2/macOS version 10.12.6/Git History version 0.3.2

**Comment by doubleceston** [comment]
same issue with macOS

**Comment by nmss** [comment]
this seems to have been simply deleted in the v3.0

do someone knows how I can install back an older version ?

**Comment by dgrizzla** [comment]
I agree with @nmss , older version was working just fine with me, there has been a lot of issues since the update and I had to delete the extension and use another one

**Comment by hmafzal** [comment]
Seeing the same issue here - any tips on how to roll back while we wait for a fix would be great

**Comment by SteveRoland** [comment]
same issue with macOS.
I cloned this repository. 
In the "lineHistory.ts", all codes were disabled  (13 days ago commit).
I believe that It will be fix..

**Comment by DonJayamanne** [comment]
>In the "lineHistory.ts", all codes were disabled (13 days ago commit).
>I believe that It will be fixed..

Will be fixed in the next release. Just released a new version a moment ago with a bunch of fixes.
Please hang in there, apologies for this

**Comment by rsperl** [comment]
I just upgraded to 0.3.6, and I get the same error.

**Comment by DonJayamanne** [comment]
Sorry guys, will fix this soon (this week).

**Comment by reuvygroovy** [comment]
This is still happening to me. Was this fixed?

**Comment by ole1986** [comment]
@reuvygroovy I have experienced similar issue with `command *** not found` when the extension could not properly be initialized at start up due to an user action which took place before the git repository was loaded.

So a possible workaround would be to wait a short while when opening your project before you run any git history command.

Where you able to run `Git: View History (git log)` at that moment?

**Comment by reuvygroovy** [comment]
I tried waiting a while and nothing changed. Same issue…..

Also I can’t find “Git: View History” in the menu. Do I need to add something?

**Comment by ole1986** [comment]
This actually sounds like the extension is not initialized at all.
Feel free to create a new issue with version number and log output attached.

Thank you

**Comment by reuvygroovy** [comment]
How do I get a log output?

**Comment by ole1986** [comment]
Make sure the extension setting`Log Level` for Git History is set to Debug

![image](https://user-images.githubusercontent.com/4850116/73348868-79868300-428a-11ea-9ef3-0f7e8af10156.png)


Then set the Output window to `Git History`

![image](https://user-images.githubusercontent.com/4850116/73348800-565bd380-428a-11ea-9cfd-63fb9f7398d8.png)

*Sorry for german language*

**Comment by reuvygroovy** [comment]
I don’t have Git History, only these:

[cid:image001.png@01D5D6A0.41537E80]
