### ISSUE TITLE
Hide icon in top right

### ISSUE THREAD

**Issue by tgreen7** [DonJayamanne/gitHistoryVSCode#186]
I think this must have been added in the last patch. Is there a way to hide the icon?

![screen shot 2018-01-17 at 2 26 10 pm](https://user-images.githubusercontent.com/10415101/35070514-6489edac-fb92-11e7-8f4e-55cc60693f7a.png)

**Comment by DonJayamanne** [comment]
Will be in the next release (some time next week).
