### ISSUE TITLE
Keyboard shortcut Search History overwrites native Find Next Selection

### ISSUE THREAD

**Issue by mkszepp** [DonJayamanne/gitHistoryVSCode#188]
OS : Windows 10 x64
VSCode : 1.19.2
gitHistory : 0.3.2

In the latest version from gitHistory, there was added "Ctrl + F3" as keybind.

When you make a search in vscode, you can move with this keybind to the next result. Now there is not anymore possible :(

Is there possible to change the default keybind from this extension? I know, that there is possible in vscode to overwrite this keybind, but i think, that also other persons use this standard keybind for next search result

**Comment by DonJayamanne** [comment]
Yes, will remove that. Its no longer valid.

**Comment by DonJayamanne** [comment]
Fixed, will release a new version shortly

**Comment by mkszepp** [comment]
thank you
