### ISSUE TITLE
Unable to view differences in a file between two commits

### ISSUE THREAD

**Issue by gjegadesh** [DonJayamanne/gitHistoryVSCode#189]
OS - Win 7
VS Code version - 1.19.2
Git History - 0.3.2

I am attempting to view the differences in a file between two commits via 'Git: View File History'. I see my file that I am interested in seeing the differences in 'Compare Commits' window. However, clicking on the file produces this error in Output and I do not see the two-pane viewer that shows the differences between the versions:

git show 6f24acfe7ee262096a54ecf319a6b8bbdd54ea94:dir\subdir\file1.js > C:\Users\xxxx\AppData\Local\Temp\tmp-5020VEzS18LvurII.js
The process cannot access the file because it is being used by another process.

In Developer Tools > Console, I see these errors:
[Extension Host] rejected promise not handled within 1 second
    t.log @ console.ts:123
    t._logExtensionHostMessage @ extensionHost.ts:391
    (anonymous) @ extensionHost.ts:211
    emitTwo @ events.js:106
    emit @ events.js:194
    process.nextTick @ internal/child_process.js:766
    _combinedTickCallback @ internal/process/next_tick.js:73
    _tickCallback @ internal/process/next_tick.js:104
[Extension Host] onDidChangeTextDocument: [object Object]

**Comment by michaelseb** [comment]
I also have this error ( "The process cannot access the file because it is being used by another process." ). I am unable to do anything with the plugin, compare files, view file content, anything since the update. I had to install the 0.2.3 version to make it work again. Please correct the last versions.

**Comment by bakeiro** [comment]
I confirm this bug, before was working nicely, after the last update it simply doesn't work

**Comment by bakeiro** [comment]
Also when I enter the command manually in the terminal to compare 2 files I get the same error message

**Comment by DonJayamanne** [comment]
Fixed in the latest version, will release it shortly.
