### ISSUE TITLE
Reenable the one-click view file history

### ISSUE THREAD

**Issue by zurfyx** [DonJayamanne/gitHistoryVSCode#190]
Hello,

I was looking forward to using this extension back again, when I've noticed the entire workflow has been redone. 4 steps are required to get a file comparison, when most of the times I'm just willing to compare the same file at an older point in time that it is in the same branch.

This used to be the default view file history, and IMO it was really handy.

**Comment by DonJayamanne** [comment]
I'll add a configuration option to always set the branch to current (or for current session).

**Comment by yantakus** [comment]
It would be also great to have ability to redefine what the button in the titlebar does. Personally I never use history of a branch (what currently this button shows), external git apps like source tree do this much better. But what would be really helpful is to see **file** history when clicking this button when viewing a file. @DonJayamanne Can you add configuration option to choose what this button does? This would be awesome. Thanks for the great extension BTW!

**Comment by DonJayamanne** [comment]
@yantakus please could you create a separate issue for your requirement.
