### ISSUE TITLE
can not show diff window when using chinese charactor in commit

### ISSUE THREAD

**Issue by aihuasxy** [DonJayamanne/gitHistoryVSCode#192]
error in console:

[donjayamanne.githistory]Running the contributed command:'vscode.diff' failed. Illegal argument 'right' - Right-hand side resource of the diff editor

**Comment by DonJayamanne** [comment]
Please could you provide the output found in "Git history" output panel. It's at the bottom along with task, git output (use the drop down).

Please replicate the issue first then copy the contents.

**Comment by DonJayamanne** [comment]
Also, what OS are you using?

**Comment by DonJayamanne** [comment]
Fixed in the new version. Please test and let me know how it goes

**Comment by aihuasxy** [comment]
thx!
no problem in new version

**Comment by DonJayamanne** [comment]
Awesome
