### ISSUE TITLE
Unable to refresh history after doing a commit

### ISSUE THREAD

**Issue by ougarte** [DonJayamanne/gitHistoryVSCode#193]
Hi team, your tool is very very useful, so I would to report this issue, because I love this feature.

Mac macOS High Sierra version 10.13.2
vsCode version 1.19.2
Git History version 0.3.2

Please follow below steps:

Step 1 Do changes
Step 2 Commit new changes
Step 3 Press Shift + Cmd + P
Step 4 Select Git: View History
Step 5 Select Current Branch
Step 6 Verify that last commit is displayed into History

Thanks for you help

**Comment by DonJayamanne** [comment]
Oops

**Comment by ougarte** [comment]
Thank you so much for solving this problem....
