### ISSUE TITLE
incorrect compare display (compare against previous version)

### ISSUE THREAD

**Issue by SteveRoland** [DonJayamanne/gitHistoryVSCode#197]
Hello!

When I open the "compare against previous version", I can see the incorrect compare result in the compare windows.

For example, I added a new line at the latest commit, the compare windows displayed that a removed line .

---

1. git: View History (git log)
2. click the latest commit.
3. click the file in the commit list
4. click the compare against previous version in command

---
- test repository : https://github.com/SteveRoland/vscode-git-history-compare-test

**Comment by michaelseb** [comment]
In the ver. 0.3.4 the compare results are inverted for me I believe ...

**Comment by SteveRoland** [comment]
Thanks, @DonJayamanne.
