### ISSUE TITLE
Issues with the last version

### ISSUE THREAD

**Issue by michaelseb** [DonJayamanne/gitHistoryVSCode#198]
Hello,

Comparisons are inverted with the last update (0.3.4) and "view file contents" and "file history" still do not work.

**Comment by DonJayamanne** [comment]
> "view file contents" and "file history" still 

Please could you provide more information on this.
Please could you go into the `Git History` output window (bottom) and provide all of the output.
First, replicate the issue, then capture the output from `Git History` output window.

**Comment by DonJayamanne** [comment]
>Comparisons are inverted with the last update (0.3.4) 
Fixed in 0.3.5

**Comment by Gavin110** [comment]
me too.Thanks you to fiexed,i looking forward to!

**Comment by Gavin110** [comment]
@DonJayamanne

**Comment by nmofonseca** [comment]
@DonJayamanne  I have the same issue view file contents doesnt work, Is there anything I can provide to help on fixing this?
Thank you.

Kind regards,

**Comment by Gavin110** [comment]
I would  like to know you  when  the version 0.3.5 will be online？？

**Comment by nmofonseca** [comment]
@Gavin110  I believe it went online today, I just notice my git history plugin updated, now I can see the compare against the workspace file or compare against previous version started working again, however view file contents still doesn't work, just opens a empty temp file.

Cheers,

**Comment by michaelseb** [comment]
@DonJayamanne I have noticed that "File history" works but is very slow. It first show the search form at the top and after 1minute it display the history.
"View file contents" only open a blank temp file. There is no output for both functions.

**Comment by DonJayamanne** [comment]
Hi guys, Please could you provide more information on this.
Please could you go into the Git History output window (bottom) and provide all of the output.
First, replicate the issue, then capture the output from Git History output window.

**Comment by DonJayamanne** [comment]
@michaelseb

>have noticed that "File history" works but is very slow. It first show the search form at the top and after 1minute it display the history.

Please could you provide a sample repo for this. Along with the output from the `Git History` output window

**Comment by Gavin110** [comment]
Version 0.3.5 
VSCode：1.19.2
windows：win10
There is still no historical comparison.

**Comment by DonJayamanne** [comment]
@Gavin110 Please could you provide a sample repo for this. Along with instructions to replicate, and finally the output from the Git History output window

**Comment by Gavin110** [comment]
git rev-parse --show-toplevel
git rev-parse --abbrev-ref HEAD
git branch
git log --full-history --pretty=one-line --date-order --decorate=full --skip=0 --max-count=100 master --follow -- build/webpack.prod.conf.js
git show-ref
git branch --all --contains edbfa0e1fdf1de4b8fe9fd4c2e87174ff7c6299f
git log --pretty=one-line -n1 edbfa0e1fdf1de4b8fe9fd4c2e87174ff7c6299f
git show --pretty=one-line --decorate=full --numstat edbfa0e1fdf1de4b8fe9fd4c2e87174ff7c6299f
git show --numstat --pretty=one-line -M edbfa0e1fdf1de4b8fe9fd4c2e87174ff7c6299f
'D:/Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���


---this is show on output window!

**Comment by Gavin110** [comment]
this is 0.3.7 version

**Comment by Gavin110** [comment]
oh,sorry！Just upgraded, not reloaded!And I was too busy yesterday to reply you immediately！Thanks!

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version. Please reopen the issue if it still persists.

**Comment by nmofonseca** [comment]
I know this is closed, but just wanted to confirm that I tested and everything is working fine for me know with the latest version 0.38
