### ISSUE TITLE
Fails on paths with spaces

### ISSUE THREAD

**Issue by simonl65** [DonJayamanne/gitHistoryVSCode#199]
Clicking on any commit fails with the following error:

```'C:/Program' is not recognized as an internal or external command, operable program or batch file.```

Looks like it's due to there being a space in the path?

**Comment by akaustav** [comment]
Same issue here. Visual Studio code running on Windows 7 displays the following message on the "Git History" Output console:

```
git rev-parse --show-toplevel
git rev-parse --abbrev-ref HEAD
git log --full-history --format=<format> --date-order --decorate=full --skip=0 --max-count=100 S-76562 --follow -- proxy.conf.json
git show-ref
git log --format=<format> -n1 e8d8f5d84511ac2b65af100ec2bcc0504e979de6
git show --format=<format> --decorate=full --numstat e8d8f5d84511ac2b65af100ec2bcc0504e979de6
git show --numstat --format=<format> -M e8d8f5d84511ac2b65af100ec2bcc0504e979de6
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
```

Not sure if it matters, but I am behind an office firewall, by the way.

**Comment by simonl65** [comment]
Thanks @DonJayamanne
