### ISSUE TITLE
Cant find commandId for shortcut

### ISSUE THREAD

**Issue by MatthieuScarset** [DonJayamanne/gitHistoryVSCode#20]
Hi and thank you for your extension.

I'm trying to find what are the commandIds for Git : View File History Git : View Line History

Could you please complete the following json snippet :) ?
```
// Git
{
		"key": "ctrl+alt+g",
		"command": "workbench.view.git.???",
	}
```

Thanks and kind regards

**Comment by gdziadkiewicz** [comment]
```json
[
    {
        "key": "ctrl+alt+g",
        "command": "git.viewFileHistory"
    },
    {
        "key": "ctrl+alt+h",
        "command": "git.viewLineHistory"
    }
]
```

**Comment by MatthieuScarset** [comment]
Thank you @gdziadkiewicz 
Works like a charm.
