### ISSUE TITLE
Fails if there is same name of dir and branch

### ISSUE THREAD

**Issue by wafer-li** [DonJayamanne/gitHistoryVSCode#205]
Fails if there is a dir with the same name of the branch.

For example:

I have a dir named `source`, and I have a branch named `source`.
And then it will complain: 

```
git log --full-history --pretty=one-line --date-order --decorate=full --skip=0 --max-count=100 source
fatal: ambiguous argument 'source': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

You could clone my repo https://github.com/wafer-li/wafer-li.github.io to reproduce.

**Comment by DonJayamanne** [comment]
@wafer-li 
Please could you type the following into your command window and let me know what you get:
`git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=10 source --`

Hopefully this will work.

**Comment by wafer-li** [comment]
Sorry for late reply, I was fighting with my paper deadline.

Here is the result:

![image](https://user-images.githubusercontent.com/12459199/35735381-e300fce8-0867-11e8-9b5a-8e049cbd7909.png)
