### ISSUE TITLE
It seems like that the plugin doesn't support chinese message.

### ISSUE THREAD

**Issue by DFVSQY** [DonJayamanne/gitHistoryVSCode#206]
When i click the chinese commit message, the git history output messy code, like below:
![test](https://user-images.githubusercontent.com/8075421/35332906-c30d7a32-0147-11e8-9cc5-c4fcc7d48da0.gif)

**Comment by DonJayamanne** [comment]
Sorry, but would you be able to provide a sample repo with such colors. I tested this at my end and it seemed to work just fine.

**Comment by DFVSQY** [comment]
You can clone [this repo](https://github.com/DFVSQY/NoDrawingGraphic), view "**Test.cs**" file history and click chinese message commit, then it outputs messy code.

**Comment by DFVSQY** [comment]
Ps: windows 10 chinese language edition and vscode x64 chinese language edition

**Comment by DonJayamanne** [comment]
Should be fixed in the latest version. Please update and let me know.
