### ISSUE TITLE
[Improvement] Add documentation for local development

### ISSUE THREAD

**Issue by aberonni** [DonJayamanne/gitHistoryVSCode#208]
I tried forking and working on the extension locally but I bumped into a few errors while compiling. I noticed that [travis](https://travis-ci.org/DonJayamanne/gitHistoryVSCode) is reporting the same errors.

I see that React has been added (like that) but the launch.json script might not have been updated accordingly, so I think this extension might have a different development workflow compared to traditional extensions.

I'm not sure whether this is something temporary or maybe just a nuisance, but I think that maybe adding some documentation on how to contribute to this repo would be handy for newcomers (especially seeing as the issue count seems to be rising 😄 )

Also maybe a CONTRIBUTING.md as a template for new issues and PRs might be a good idea to avoid random and not very descirptive issues.

**Comment by DonJayamanne** [comment]
> travis is reporting the same errors.
Yes, none of the tests work. Yikes

**Comment by DonJayamanne** [comment]
Instructions:
* Install nodejs 8.9.1
* install yarn
* Clone repo
* Open above folder in VS Code
* Run command `yarn` in terminal
* Go to `Task-> Run Build Task` menu option
* Run both `Compile` and `npm:WatchReact`

Thats it.
I'll update the documentation and improve the build, tools and (write & fix) unit tests.
