### ISSUE TITLE
History formatting fails

### ISSUE THREAD

**Issue by bartosz-antosik** [DonJayamanne/gitHistoryVSCode#209]
VSCode version 1.19.2
Architecture x64
Windows 10 PRO
Git History version 0.3.5

History listing bit down is crimped as shown on the screenshots. I tried to think/observe but I have no idea what may cause this.

![image](https://user-images.githubusercontent.com/20492548/35346536-c955a7bc-0132-11e8-9932-7749ad4fc892.png)

![image](https://user-images.githubusercontent.com/20492548/35346570-e16f5e4c-0132-11e8-98fd-b484127596e4.png)

**Comment by DonJayamanne** [comment]
Please could you provide the following info:
* A sample repo I could use to replicate this issue
* Does this happen always or when you resize the viewers or VS Code (or similar)
* Does this happen always?

**Comment by bartosz-antosik** [comment]
* Sady I do not think I can provide a repository. It does happen on my corporate repo which I really cannot show. On (smaller|other) repos I cannot reproduce it.
* It seems resizing has nothing to do with it. Switching branches with the dropdown has. It happens nearly always after switching branch on this particular repo.
* As I have said above: on this repo always. On others I cannot reproduce this.

Maybe you can close this thread and I will keep observing this.

**Comment by DonJayamanne** [comment]
Sorry @bartosz-antosik 
I'm going to close this as I can't do anything at this stage unless someone else reports this with instructions to reproduce this issue.
