### ISSUE TITLE
Recent update broke this...

### ISSUE THREAD

**Issue by mmahimtura** [DonJayamanne/gitHistoryVSCode#213]
Issue can be closed, I updated to git > 2.0 and issue went away

Hi,

When viewing file history, clicking on the hash on any of the commits no longer shows the list of changed files in that commit.

Last line in the output windows shows "Unrecognized file stat status 'c"

Thanks for writing this awesome plugin, very helpful indeed.

**Comment by DonJayamanne** [comment]
Please could you execute the following commands in your terminal and provide the output for each of them. Thanks.
This should be easy to fix. 

* `git show --numstat --pretty=one-line -M <commit hash>`
* `git show --name-status --pretty=one-line -M <commit has>`
