### ISSUE TITLE
Can't compare files!

### ISSUE THREAD

**Issue by DFVSQY** [DonJayamanne/gitHistoryVSCode#217]
Hi, issue #206 has fixed, but there is a new bug, like below:
![test](https://user-images.githubusercontent.com/8075421/35469293-f05000ce-036c-11e8-837c-7f9467878240.gif)
The files compared are both empty.

**Comment by DonJayamanne** [comment]
Please could you go into the `Git History` output window and provide the output from there.
Please ensure you have the latest version 0.3.7

**Comment by DFVSQY** [comment]
Yes, i have the latest version and the complete log is below:
![image](https://user-images.githubusercontent.com/8075421/35469413-f8a2195e-036e-11e8-8503-c97b4464a77d.png)

**Comment by DonJayamanne** [comment]
Please could you try running the last command in the terminal

**Comment by DFVSQY** [comment]
I have a try for it, but nothing happen.
![image](https://user-images.githubusercontent.com/8075421/35469597-f20efd7e-0372-11e8-9e1b-c6890e2b5a03.png)

**Comment by DFVSQY** [comment]
now it ok:
![image](https://user-images.githubusercontent.com/8075421/35469609-5208ee9c-0373-11e8-9684-5daaa1878713.png)

**Comment by DonJayamanne** [comment]
Will release a new version now.

**Comment by DonJayamanne** [comment]
Fixed, new version has been uploaded
