### ISSUE TITLE
github image implementation grabs random persons picture

### ISSUE THREAD

**Issue by null4bl3** [DonJayamanne/gitHistoryVSCode#227]
The 4 day old feature of adding profile pictures to git history searches for random matching names and adds the result as a profile picture.

Pretty weird to see random peoples profile pictures added to my git history overview.

Please do fix or remove the feature

**Comment by DonJayamanne** [comment]
Please could you provide a screen shot along with a sample repo to replicate this.

**Comment by Crevil** [comment]
We experience the same. We use BitBucket so I expected no avatars to show up but we get random avatars in the commit history. This avatar comes from a commit with email `bso@lunarway.com`
![screen shot 2018-01-31 at 17 54 40](https://user-images.githubusercontent.com/6881694/35635915-de49d724-06af-11e8-8927-187596ef0a23.png)

**Comment by DonJayamanne** [comment]
@Crevil 
* Please could you type the following command in your terminal and let me know what you get `git remote get-url origin`

**Comment by DonJayamanne** [comment]
@null4bl3 
Please could also provide the following:
* Are you using github or bitbucket
* Please could you type the following command in your terminal and let me know what you get git remote get-url origin
* Please could you give me an example name and email from one of your commits for which the avatar is incorrect?

Thanks

**Comment by Crevil** [comment]
We are using BitBucket.
Get remote url is `git@bitbucket.org:LunarWay/lw-go-context.git`
An example could be: user `Bjørn Sørensen <bso@lunarway.com>`. I have no GitHub account related to that email and the buzz lightyear avatar is shown as the screen dump above shows.
