### ISSUE TITLE
how to set my git avatar

### ISSUE THREAD

**Issue by accpdyk** [DonJayamanne/gitHistoryVSCode#228]
git history has aavatar image, but not I'm set

**Comment by DonJayamanne** [comment]
Please could you provide more info.
"
* Screen shot
* Os
* Output from `console window` in `Help->Toggle Developer Tools`

Also, the git Avatar only works for GitHub, and after a few attempts. This is because GitHub limits the number of calls to get the Avatar from the client, (possibly rate limit)

**Comment by DonJayamanne** [comment]
The problem is its not possible to uniquely identify your profile using just your name, there are others with the exact same name. In such a situation i have decided not to display the avatar.

I could possible display gravatars (https://en.gravatar.com/) as a fall back.
