### ISSUE TITLE
Github avatars not me

### ISSUE THREAD

**Issue by seblee** [DonJayamanne/gitHistoryVSCode#230]
## as tittle.Github avatars not me

![image](https://user-images.githubusercontent.com/28698690/35663037-48ef6fa2-0756-11e8-97f6-dba6e33e73cc.png)

**Comment by ababak** [comment]
Same here

**Comment by apdev4life** [comment]
same

**Comment by weiofcn** [comment]
Same. I thought someone hacked my computer. Then, I did some research because the beautiful female avatar intrigued me, I found my avatar shows the one of github user's, we have a same family name and his Bio write my last name.

**Comment by phoenixwu** [comment]
same here
my GitHub display name is "Phoenix Wu", but my avatar is from the other GitHub user called "Fred Wu"
