### ISSUE TITLE
File History - Compare Against Workspace

### ISSUE THREAD

**Issue by pltrant** [DonJayamanne/gitHistoryVSCode#232]
With the UI overhaul, performance has become a significant issue with this extension and there is now no compare against the workspace version of File History (that I can find).  The performance issue could just be due to the git repository that I'm working in (with lots of daily commits).  Overall, I feel like the process is more disjointed and takes significantly longer to perform previously quick tasks.

I almost exclusively use the extension for the File History functionality.  Previously, I could execute the command to view the File History and it would present the drop down from the command palette to select one of the prior versions.  This was a nice implementation because you never had to leave the existing file and it was relatively fast.  I could then select one of the versions, then compare it against my workspace version.  Now, when I execute the File History command, it opens entire new document and takes significantly longer to display all the versions of the file.  I then have to click a button to select select one commit, then select another commit to compare it against.  I don't even think the latter is working - when I select compare, it's not showing anything in the UI as a result of that action.  But more importantly, where is the option to compare it against the workspace version?  In the previous version, it probably took 2-3 clicks to compare a version against the workspace file and now it's at least 4-5 plus takes me out of the existing document.

**Comment by pltrant** [comment]
Here's the output when it takes so long to view the history (shortened the long URL by removing the file name and inserting <file>):

git rev-parse --abbrev-ref HEAD  (completed in 0.069s)
Server running on http://localhost:58920/?_&id=d2bbe9f5d51e8f1ed8c76e035e5b00ca&branchName=master&file=<file>&theme=&branchSelection=1&locale=en_US
git branch  (completed in 0.125s)
git shortlog -e -s -n HEAD  (completed in 0.835s)
git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 master --follow -- <file>  (completed in 29.943s)
git show-ref  (completed in 0.072s)
git remote get-url origin  (completed in 0.074s)

**Comment by pltrant** [comment]
If I try to then run a compare, it shows:

```
git diff --name-status 59992cace4c31b0700a26761722d20d178332e07 99983b82e8ad6985adaa41b034051eca53e854dc  (completed in 0.118s)
git diff --numstat 59992cace4c31b0700a26761722d20d178332e07 99983b82e8ad6985adaa41b034051eca53e854dc  (completed in 0.518s)
```

But nothing shows up in the UI.

**Comment by DonJayamanne** [comment]
@pltrant as a quick fix, you can reduce the number of items displayed in the history view from 100 to something smaller like 20 as follows:
* Open your settings file
* add the following entry:
```json
"gitHistory.pageSize": 20
```

**Comment by DonJayamanne** [comment]
Please could you run each of the following and provide the output:
* `git diff --name-status 59992cace4c31b0700a26761722d20d178332e07 99983b82e8ad6985adaa41b034051eca53e854dc` 
* `git diff --numstat 59992cace4c31b0700a26761722d20d178332e07 99983b82e8ad6985adaa41b034051eca53e854dc`

**Comment by DonJayamanne** [comment]
> Previously, I could execute the command to view the File History and it would present the drop down from the command palette to select one of the prior versions. This was a nice implementation because you never had to leave the existing file and it was relatively fast.

I'll try to add this back as an optional UI (you should be able to configure the UI you want). Will add this in the next release.

**Comment by DonJayamanne** [comment]
> But more importantly, where is the option to compare it against the workspace version

Hmm, will add this back. Didn't mean to remove it.

**Comment by pltrant** [comment]
Thanks for looking to add some options for the old UI back.  It great to have options (and not that the new UI isn't nice - it is, but for some use cases, the old one worked better).

For the git commands you wanted me to run, I'm not going to post the full output here since it's a huge amount of lines.  They each are about 800 lines long.  The repository I work in has about 25k files with 25-50 of those updated daily.  Let me know if I can run something else or if that's enough information (or if you want me to email you the full output).

**Comment by DonJayamanne** [comment]
@pltrant is this a public repo that I could probably look at?

**Comment by pltrant** [comment]
Unfortunately, it's a private repo.  However, I did run a 'git gc --aggressive' against my local repo and it made a significant difference.  After that, 'git log' only took about 18 seconds to query.  That's probably a reasonable level of expectation given how large and busy the repo is.  Assuming the implementation has always used that to generate the lists, you probably don't need to react here for the performance issue.  Thanks.

**Comment by diablodale** [comment]
Hello. Added my thumb up on the OP. I am also experiencing one of the fail cases the OP. There is no UI output for a compare where I select one commit and select a second to compare it against. I get similar output in the debug window as the OP write above.

You asked for the output of those commands. Here are mine:
```
git diff --name-status 77870abbf50e7169d91d56953baec2f2d5d1695a be9098f7b756c945501f22401e449e4826857b8d  (completed in 0.248s)
M	src/main.rs

git diff --numstat 77870abbf50e7169d91d56953baec2f2d5d1695a be9098f7b756c945501f22401e449e4826857b8d  (completed in 0.256s)
7	6	src/main.rs
```

And then nothing. Nothing in the output window. Nothing in the UI.

**Comment by pltrant** [comment]
Any update on when the next release (that incorporates these fixes) might happen?

**Comment by DonJayamanne** [comment]
Sorry, been busy. Will try to get onto this sometime over the weekend.

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
