### ISSUE TITLE
Can‘t view the Chinese path file.

### ISSUE THREAD

**Issue by actboy168** [DonJayamanne/gitHistoryVSCode#234]
[test repo](https://github.com/actboy168/MoeHero)

![2](https://user-images.githubusercontent.com/1836844/35896925-9980f240-0bf9-11e8-96ec-af3738ea38cd.gif)

**Comment by Mr-ziqiang** [comment]
跟我的问题一样，不但是中文路径。英文的也一样，大概是因为hash用了缩写。

this bug look the same #236 issue

**Comment by Mr-ziqiang** [comment]
好像是他盘符写错了
looks like the driver is error ,so....

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
