### ISSUE TITLE
Nodes and comments misaligned when opening gitHistory at non-default VSCode zoom

### ISSUE THREAD

**Issue by raphK** [DonJayamanne/gitHistoryVSCode#235]
gitHistory has to be opened when VSCode zoom level is default for commit nodes and commit comments to align.  Changing zoom level does not impact alignment: commits nodes and comments remain unaligned when gitHistory is opened at an VSCode zoom level other than the default.

To replicate the issue:
1. Set VSCode to default zoom (View > Reset Zoom)
2. Zoom in or out (View > Zoom in or Zoom out)
3. Open gitHistory
4. Observe comments and nodes remain unaligned regardless of zoom changes
5. Close gitHistory
6. Reset VSCode zoom (View > Reset Zoom)
7. Open gitHistory
8. Observe aligned comments and nodes
9. Observe nodes and comments remain aligned regardless of zoom changes

Screenshot of nodes not aligned to comments:
![image](https://user-images.githubusercontent.com/3084769/36054450-68c3b79a-0dee-11e8-9692-f44715639094.png)

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
