### ISSUE TITLE
Branch labels display ansi characters

### ISSUE THREAD

**Issue by psyrendust** [DonJayamanne/gitHistoryVSCode#239]
ANSI characters are being displayed in the branch labels dropdown.

![image](https://user-images.githubusercontent.com/928502/36229172-441cabb8-118b-11e8-966e-2f202911c3ab.png)

From terminal:
![image](https://user-images.githubusercontent.com/928502/36229249-7453345a-118b-11e8-8649-aebfe0d5e989.png)

Actual text output from `git branch` command:
```
  MAPS-5798[m
* [32mMAPS-6194-xxxx-xx-xxxx[m
  MAPS-6223-xxxx-xxxx-xx-xxxxx[m
  bak[m
  master[m
```
Sorry about the obfuscation.

#### System Info

VS Code:

      Version 1.20.1 (1.20.1)
      f88bbf9137d24d36d968ea6b2911786bfe103002
      2018-02-13T15:18:47.464Z

Git History Plugin:

      Version 1.20.1 (1.20.1)

My VS Code [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) Gist:

https://gist.github.com/psyrendust/53b4aca2f254cc7e381a3ea21fa092f7

System Software Overview:

      System Version: macOS 10.13.3 (17D47)
      Kernel Version: Darwin 17.4.0
      Time since boot: 2 days 11:15
      Bash Version: 4.4.12
      Zsh Version:  5.4.2
      Git Version:  2.15.0
      Node Version: 6.9.1
      NPM Version:  3.10.8

Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro14,3
      Processor Name: Intel Core i7
      Processor Speed: 3.1 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Memory: 16 GB
      Boot ROM Version: MBP143.0169.B00
      SMC Version (system): 2.45f0

**Comment by psyrendust** [comment]
Not sure if this is related to #155

**Comment by VasylBoyko** [comment]
It happens if 
git config --global color.ui **always**

![screen shot 2018-04-24 at 9 00 19 pm](https://user-images.githubusercontent.com/10295984/39205439-4fc18642-4803-11e8-9fa4-33f072f1ab0e.png)

So  parsing of branch names needs to be updated.

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
