### ISSUE TITLE
Please add documentation about keyboard shortcut

### ISSUE THREAD

**Issue by MatthieuScarset** [DonJayamanne/gitHistoryVSCode#24]
Hi, 

I'm trying to find the right command that I must write in keybindings.json, as follow:
`{ "key": "ctrl+alt+g",          "command": "view.file.gitHistory" },`

Could you please tell me what's the command name and additionnaly update the README?

Thank a lot!

**Comment by DonJayamanne** [comment]
@MatthieuScarset , the command is **git.viewFileHistory**
and it is already mentioned in the README [see here](https://github.com/DonJayamanne/gitHistoryVSCode#available-commands)

**Comment by MatthieuScarset** [comment]
Thanks @DonJayamanne 
I haven't found command before (maybe need more coffee :) )
