### ISSUE TITLE
Keep opened history view between restarts

### ISSUE THREAD

**Issue by dwuttke90** [DonJayamanne/gitHistoryVSCode#242]
hey there,

first of all: i really like your extension.
another step into the "install OS -> install VS Code -> done" direction ;)

i would love to see a feature to keep the opened editor for the git history stay opened between restarting vs code (actually the behavior all other tabs have as well).

**Comment by DonJayamanne** [comment]
Sorry but that's not possible using the current vscode API.

**Comment by dwuttke90** [comment]
sad, but ty for the fast answer
