### ISSUE TITLE
History between two commits fails when selecting a file that does not exist in initial commit

### ISSUE THREAD

**Issue by damiengrandi** [DonJayamanne/gitHistoryVSCode#243]
I compare my project commit "2878e28" (older one) with a more recent commit.
When selecting an "added" file like this :

![image](https://user-images.githubusercontent.com/7514487/37081409-a2f84e1c-21e9-11e8-9b12-f32f2182d153.png)

No tab window appears and console shows this :

![image](https://user-images.githubusercontent.com/7514487/37081455-ca35b3de-21e9-11e8-8fab-39627132eb22.png)

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
