### ISSUE TITLE
Bug: File history fails if project is located in a drive other than C:\

### ISSUE THREAD

**Issue by iliketoprogram14** [DonJayamanne/gitHistoryVSCode#246]
I have a project located in D:\path\to\project.  When I open up Git file history for a file within the project, I can see the previous commits, but if I try to open up any of the files to view or compare against, Git History throws up the error "fatal: 'C:\path\to\project\file' does not exist in <commit>".

I'm the only one to use this project, and I've only used it on this one machine, so it must be a bug in the extension.

**Comment by zapftho** [comment]
I have the same issue.

**Comment by rickynugroho** [comment]
I also have the same problem.
From what I see, this is same with issue #234 and #236

**Comment by erwanpoupard** [comment]
Same issue here

**Comment by ole1986** [comment]
Should also be fixed with version >= 0.5.0
