### ISSUE TITLE
adapt style of search input field to VSCode CD

### ISSUE THREAD

**Issue by dmstern** [DonJayamanne/gitHistoryVSCode#249]
The style of the search input field does not fit to the VSCode UI design.

Please use the style of other input fields in VSCode:
* background-color
* focus outline
* height

![2018-03-17 21_03_33-git history - untitled workspace - visual studio code](https://user-images.githubusercontent.com/5219707/37559456-ec4758ac-2a26-11e8-916e-b88ed4f3ef75.png)

**Comment by DonJayamanne** [comment]
> fit to the VSCode UI design.

Vscode doesn't exist the styles to extension authors creating webviews.

You are more than welcome to submit a PR for this simple request.
