### ISSUE TITLE
View line history failed in my VS Code on RHEL 7.0 

### ISSUE THREAD

**Issue by Chengxuan** [DonJayamanne/gitHistoryVSCode#25]
Cannot view line history in my VS Code on Red Hat Linux 7.0. Haven't tried other platform, not sure whether this is a Linux specific issue. Screen-shot as follow:
![screenshot from 2016-07-14 10-22-13](https://cloud.githubusercontent.com/assets/5425125/16834862/a3a62552-49ad-11e6-91e2-9c5cddaafc63.png)

**Comment by DonJayamanne** [comment]
Please could you try this with another git repo? Thanks

**Comment by Chengxuan** [comment]
![screenshot from 2016-07-14 16-07-05](https://cloud.githubusercontent.com/assets/5425125/16844586/ad258ca0-49dd-11e6-8d15-adf9d90efe1f.png)

I've tried it using 'git blame', seems the system doesn't like ':' before file path, replaced it with a space worked.

**Comment by Chengxuan** [comment]
It seems '-L121,121' is the first bit it's struggling of.

**Comment by DonJayamanne** [comment]
Sorry for the delay I getting back to you, will be looking into this. Is this a public repo that I can test on?

**Comment by Chengxuan** [comment]
No problem. I think it's a Linux specific issue. The repo I used to test is current repo.

**Comment by DonJayamanne** [comment]
What is the current repo? If you don't mind me asking?

**Comment by Chengxuan** [comment]
Sorry. Should be 'this' repo. gitHistoryVSCode

**Comment by Chengxuan** [comment]
I've tried this extension on my Windows 10 machine, it works fine. The Linux I am using is RHEL 7.0. But I suspect this might be a bug of 'child-process' module you are using.

**Comment by mikes-gh** [comment]
I tried this on fedora 25 using 0.1.2.
I couldn't reproduce.
Is this still an issue with the current version

**Comment by Chengxuan** [comment]
Sorry for the late reply. I'm still hitting this issue on RHEL 7.2:
```
fatal: unrecognized argument: -L54,54:gulpfile.js
```
Kernel version:
3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mikes-gh** [comment]
I think its more likely an issue with older version of git that comes with RHEL. 7.0
Probably 1.8.3 (from my centos 7 install).

what is your output of

git --version

Git  only supports -L option since 1.8.4
Is it possible you could try a newer version of git

http://tecadmin.net/install-git-2-x-on-centos-rhel-and-fedora/

**Comment by Chengxuan** [comment]
@mikes-gh You are correct, updated my git and it works fine. Thank you!
