### ISSUE TITLE
weird display commit history under Ubuntu16.04 by zoom 1.25

### ISSUE THREAD

**Issue by xuyixin0723** [DonJayamanne/gitHistoryVSCode#251]
The most of jobs I works should be under Linux(such as ubuntu16.04). Beasue my monitor is 1920*1080, I have to use gnome-tweak-tool to set zoom to 1.25 to avoid too small fonts. the setting is as below image shows ( please note red rect area):
![deepinscrot-1531](https://user-images.githubusercontent.com/3304068/37821826-a744800c-2ebf-11e8-9fb7-5eaa0afd0150.png)
but after I did it, when I want to show git history by the extension I found commit point can not be matched its right infomation as below image shows ( please note red rect area):
![deepinscrot-1725](https://user-images.githubusercontent.com/3304068/37821656-3133929a-2ebf-11e8-9a87-a42794895e17.png)
under the circumstance, I can't understand those commits belongs to which one branch
Do you have any idea to solve the problem ? or do sth to fix it
very thanks and expect progress!
@DonJayamanne

**Comment by jberube** [comment]
I have a similar issue, but using VSCode's zoom. The more I zoom, the higher the lower the dots are compared to its text. On default zoom level, I have no issue. I use a 150% screen scaling on one monitor (3840x2160), the other is 100% (1920x1080). The issue happen on both displays.

Opening the history on default zoom and then zooming in gives the right result.
When zooming in and the opening the history, the dots are too far from each other.

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
