### ISSUE TITLE
Shows empty list although commit entries are available.

### ISSUE THREAD

**Issue by tjeitner** [DonJayamanne/gitHistoryVSCode#252]
We use GitLab Community Edition 10.1.0. with Git 2.16.3. When I open Git History in VSCode it shows always an empty list although commit entries are available.

![image](https://user-images.githubusercontent.com/37798566/37903566-ad1036f8-30f8-11e8-9dcb-2a1c038bff50.png)

Do you have any idea to solve the problem?

Thanks Thomas

**Comment by DonJayamanne** [comment]
* Please check the `console window` for errors (Open `Help-> Toggle Developer Tools`)
* Would it be possible for you to provide a link to this repo so I could try to replicate this at my end?

**Comment by tjeitner** [comment]
Hi,
I made some more tests.

If I choose "Git:View file history" for the data-grid.component I get the following Git History console output (history is empty):
![image](https://user-images.githubusercontent.com/37798566/39688241-0f846a3a-51d2-11e8-9c37-be51e7a68944.png)
If I execute the git command via terminal I get the history information:
![image](https://user-images.githubusercontent.com/37798566/39688333-83ed7cb8-51d2-11e8-9bef-9b3e92ce0f63.png)
The log shows the following:
![image](https://user-images.githubusercontent.com/37798566/39688352-9cd070aa-51d2-11e8-8ecc-a13918df9e4d.png)
I'm sorry but our repo is not public so I can't give you access to it.

**Comment by DonJayamanne** [comment]
Unfortunately I never go to this, apologies. If this is still an issue please let me know.
Closing for now
