### ISSUE TITLE
Don't show Output window when viewing File History

### ISSUE THREAD

**Issue by garyking** [DonJayamanne/gitHistoryVSCode#253]
When I open up File History with this extension, the Output window also appears. Is it possible to make it NOT appear when I view File History?

**Comment by mikolino** [comment]
I have the same issue. It seems to be related to the error generated when checking remote on a local repository

    git remote get-url origin  (completed in 0.064s)
    fatal: No such remote 'origin'

**Comment by garyking** [comment]
So we just need an option like `checkRemote: true` then we can set this to `false` on a per-project basis, so that the extension doesn't check for the remote repo on some projects?

**Comment by mikolino** [comment]
I think the extension should just dismiss the error (or check if the repository has any remote beforehand).

Not having a remote shouldn't need custom configuration.

**Comment by mikolino** [comment]
I have written a patch to run "git remote show" before trying to get-url. It fixes the issue for me.

https://gist.github.com/mikolino/f8610f5bfe1cb891d6297c6ef1e097f6

**Comment by dustinmoris** [comment]
Issue still exists. See #281
