### ISSUE TITLE
Keep getting scrolled back to top when focusing back on diff file

### ISSUE THREAD

**Issue by garyking** [DonJayamanne/gitHistoryVSCode#255]
On a file that has uncommitted changes, I use `Git: Open Changes`. I scroll down on the page with changes. I click on line 200 or so. I scroll back to my file, then back to the changes. Focus is now moved back from line 200 to line 1, so I lose my place in the file. 

Instead, it should not scroll back to the top.

**Comment by DonJayamanne** [comment]
Should be fixed with #265.
