### ISSUE TITLE
Ill-formated when view all branches

### ISSUE THREAD

**Issue by psychelzh** [DonJayamanne/gitHistoryVSCode#256]
Have a look at the screenshot:

![image](https://user-images.githubusercontent.com/13306020/38306156-324ddfa0-3842-11e8-857e-6c592551d808.png)

**Comment by DonJayamanne** [comment]
Is there any chance I can get a link to the repo (or a sample repo) so I could replicate this at my end?
Thanks

**Comment by psychelzh** [comment]
The repo is iquizoo/pages

**Comment by alexandru-m-g** [comment]
I can confirm that I have the same issue. It's not new but I had a workaround until recently.

What used to help was going to another open file and then going back to GIT History. That was triggering a reload of the Git History tab with the "all branches" option directly selected. In this case it was rendering correctly. 

However, not sure what changed but now the Git History tab is not being reloaded anymore when i go away from it and back.

**Comment by psychelzh** [comment]
@alexandru-m-g Yeah, I found this workaround, too. Thanks!

**Comment by codexp** [comment]
I confirm this bug too. The workaround does not work for me :(
Here is a screenshot:
![image](https://user-images.githubusercontent.com/6502486/42529974-355cdde2-8480-11e8-81b3-b2a9d28b3c0f.png)

**Comment by DonJayamanne** [comment]
Closing as I believe this has been resolved
