### ISSUE TITLE
Can't not appears when source code from app.visualstudio repo

### ISSUE THREAD

**Issue by gagahkharismanuary** [DonJayamanne/gitHistoryVSCode#257]
I found this issue when my project source code repository from app.visualstudio.com repository and the gitHistory Tree not appears.

I Try my local repository that remote from bitbucket and Github works, So I think the project source code from app.visualstudio.com got issue to solve.

Thanks

**Comment by DonJayamanne** [comment]
I'm sorry, but I cannot understand what the problem is.
Please could you send a screenshot of the error or further details.
