### ISSUE TITLE
Does not work on WSLGit

### ISSUE THREAD

**Issue by rdrgn** [DonJayamanne/gitHistoryVSCode#258]
Recently, I started using [WSLGit](https://github.com/andy-5/wslgit) instead of Git for Windows. I wrote `"git.path": "c:/bin/wslgit.exe"` into the configurations of VSCode. (`wslgit.exe` passes commands to WSL, so it behaves as Git on Linux.) Now, the Git client of VSCode is working correctly, but Git History doesn't show any tabs.

(If you thought this is not an issue of Git History, just close it.)

**Comment by DonJayamanne** [comment]
Closing for now, due to inactivity.
