### ISSUE TITLE
can not support chinese files with Compare against

### ISSUE THREAD

**Issue by Moerj** [DonJayamanne/gitHistoryVSCode#260]
![image](https://user-images.githubusercontent.com/13795438/39083155-9821a7be-4592-11e8-9e4d-ca57a6ef3765.png)

vscode@1.22.2
git history@0.4.0

Chinese files can't be open. The file name is garbled

**Comment by DonJayamanne** [comment]
Is there a public git repo I could use to replicate this issue?
* Are you on windows or Mac?

**Comment by Moerj** [comment]
@DonJayamanne 

public git repo:
https://github.com/Moerj/monkey-company

Mac

**Comment by ipcjs** [comment]
The problem is with git, just execute this command: 
```
git config --global core.quotepath false
```

**Comment by Moerj** [comment]
@ipcjs thank you.
