### ISSUE TITLE
Keyboard shortcut for View file history throws an error

### ISSUE THREAD

**Issue by mgerner** [DonJayamanne/gitHistoryVSCode#27]
I just updated to v 0.0.7, and `git.viewFileHistory` stopped working -- when called from a keyboard shortcut.

Opening the command prompt (ctrl+shift+p) and running "Git: view file history" from there works correctly. On the other hand, pressing its keyboard shortcut ("ctrl+h" in my case, defined as { "key": "ctrl+h", "command": "git.viewFileHistory" }) triggers an error, with the text "fatal: Not a git repository (or any of the parent directories): .git" in the output console.

Everything was working fine prior to the extension upgrade, and I don't have problems with any other keyboard shortcuts. git.viewLineHistory works fine, both with and without a keyboard shortcut. I'm not sure what version of the extension I was on before, but it was at least 0.0.5. VSCode is at 1.3.1 and I'm running on Debian stretch.

**Comment by DonJayamanne** [comment]
@mgerner, bummer, will check this out tomorrow.

**Comment by DonJayamanne** [comment]
@mgerner , fixed, please try the latest update. Apologies for this bug.

**Comment by mgerner** [comment]
Works fine now. Thank for the very quick fix, and more generally, the very nice extension :).

**Comment by DonJayamanne** [comment]
@mgerner, thanks, hopefully i'll be able to add more features in the near future.
