### ISSUE TITLE
how can i get my github-avatars?

### ISSUE THREAD

**Issue by JWleo** [DonJayamanne/gitHistoryVSCode#274]
<img width="244" alt="12" src="https://user-images.githubusercontent.com/32316654/39739155-0370ba82-52c2-11e8-9634-2457d6167078.PNG">
just like that @DonJayamanne

**Comment by JWleo** [comment]
how could i fix the problem on my PC?need i retry to install this Plug-in？ @DonJayamanne

**Comment by DonJayamanne** [comment]
You'll need to wait for the new release, sometime today.

**Comment by JWleo** [comment]
@DonJayamanne yeah,thanks

**Comment by JWleo** [comment]
@DonJayamanne there are still some problem about the avatar
<img width="269" alt="proble2" src="https://user-images.githubusercontent.com/32316654/39962853-e7e85b4c-568d-11e8-9f2a-8b532f2e2afe.PNG">

**Comment by ole1986** [comment]
Could this be that you have reached the "free" github API request limitation?
