### ISSUE TITLE
remote name isn't origin

### ISSUE THREAD

**Issue by RockYuan** [DonJayamanne/gitHistoryVSCode#279]
git remote get-url origin
fatal: No such remote 'origin'

**Comment by CaBra503** [comment]
I am having this issue aswell, is there a way to configure which remote is being accesed?

**Comment by CaBra503** [comment]
I figured my problem out with git remove -v check the names and verify that you're using the correct branch with git branch -a

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/DonJayamanne/gitHistoryVSCode/pull/268

**Comment by dustinmoris** [comment]
This issue is not fixed yet!
