### ISSUE TITLE
putting deleted content after a d$ command does not insert the expected content

### ISSUE THREAD

**Issue by douglas-mason** [DonJayamanne/gitHistoryVSCode#28]
Steps to reproduce:
Delete line using `dd` and place the line with `p` and you'll get the expected behavior.

Delete to end of another line using `d$` and then attempt to place that text elsewhere with `p` and you'll see that the contents of the first `dd` operation is inserted instead of that from the `d$` operation.

**Comment by DonJayamanne** [comment]
@douglas-mason , what are you talking about?
This extension doesn't support such commands, it just displays the history.
Are you referring to VIM commands, probably issue related to some other extension.

**Comment by douglas-mason** [comment]
haha, sorry, I created this issue on the wrong repo. thanks
