### ISSUE TITLE
Please provide dates in changelog

### ISSUE THREAD

**Issue by alystair** [DonJayamanne/gitHistoryVSCode#280]
I feel the changelog should have a date attached to each version/release, similar to the guide at https://keepachangelog.com/en/1.0.0/

**Comment by ole1986** [comment]
I prefer to have a link which refers to github "releases" inside the changelog.
What do you think, @DonJayamanne

**Comment by DonJayamanne** [comment]
Lets do this

**Comment by ole1986** [comment]
@DonJayamanne Sorry, I did not get how we gonna do this now.

adding the dates into the changelog.md (through CI/CD) or profit from the "releases" on Github and only refer to the releases page in CHANGELOG.md (with a link)

**Comment by DonJayamanne** [comment]
**Lets automate more of the release using one of (or another)**
* https://github.com/marketplace/actions/release-drafter
* https://github.com/semantic-release/semantic-release
* https://github.com/github-tools/github-release-notes

**Comment by ole1986** [comment]
I think this is now done
