### ISSUE TITLE
Add support for git blame

### ISSUE THREAD

**Issue by y-a-v-a** [DonJayamanne/gitHistoryVSCode#286]
An essential element of working in a team is to praise or blame some-one for their work. A Git-editor-plugin isn't complete without `git blame`. `git blame` on current file, or even better, on current selected lines would be awesome.
Regards, Vincent

**Comment by DonJayamanne** [comment]
Out of scope

**Comment by y-a-v-a** [comment]
...and uninstalled the plugin. Bye! (it was ffing slow anyway)

**Comment by DonJayamanne** [comment]
@y-a-v-a its obvious you hadn't done your research on VS Code extensions. 
If you merely search for `Git Blame` in the market place you'll find there are tonnes of extensions that do that. The title of this extension is `Git History`, i.e. display the history/log, not `blame`.

Its interesting you took offense to my response, anyways as I stated about, please do your research next time.
