### ISSUE TITLE
Output console opening on every View File History

### ISSUE THREAD

**Issue by dberthia** [DonJayamanne/gitHistoryVSCode#288]
Each time I open the View File History, the Output console pops-up, even when I have it hidden. Is there any way to prevent this? I'm not interested in seeing the console output.

**Comment by jackharich** [comment]
I'm having this problem too. Thanks!

**Comment by medied** [comment]
Same here, thanks in advance for any insight

**Comment by lenmerkel** [comment]
This happens to me in any project where I only have a local Git repo. Looks like there is a forced "**git remote get-url origin**", even when the local repo has **no** remote repo configured. This results in a "**fatal: No such remote 'origin'**" message, which I guess causes the output window to open. I often work on small projects that only need a local repo, with no upstream remote, so this behavior is annoying.

**Comment by dustinmoris** [comment]
This is related to #281

**Comment by ArselMuginov** [comment]
In my case it runs this command:
`git remote get-url origin/feature`
Which is wrong, because my remote is `origin`, but I have branches like `feature/payment-system`.

**Comment by bhack** [comment]
@ArselMuginov Are you covered by https://github.com/DonJayamanne/gitHistoryVSCode/pull/318?

**Comment by mcdado** [comment]
@ArselMuginov I see that my change in https://github.com/DonJayamanne/gitHistoryVSCode/pull/318 broke situations where branches have slashes in them. https://github.com/DonJayamanne/gitHistoryVSCode/pull/330 should fix it.
