### ISSUE TITLE
Git: View History (git log) - getting error with missing file

### ISSUE THREAD

**Issue by jvyoralek** [DonJayamanne/gitHistoryVSCode#29]
When tried to show new functionality of "Git Log" (with command as on first screenshot) then getting error with missing file (second screenshot).

Using MS Visual Code 1.4.0 and Git History (git log) plugin v. 0.0.9.

![screenshot 2016-08-16 13 23 09](https://cloud.githubusercontent.com/assets/15640266/17697359/bc6c41b8-63b4-11e6-8686-2b40f9d0f897.png)

![screenshot 2016-08-16 13 23 24](https://cloud.githubusercontent.com/assets/15640266/17697358/bc695da4-63b4-11e6-8ea6-965fb70dee5d.png)

Thanks for help or fix.
J.

**Comment by DonJayamanne** [comment]
bugger,

**Comment by DonJayamanne** [comment]
@jvyoralek, fixed please install the latest version. Damn.

**Comment by jvyoralek** [comment]
@DonJayamanne It works now! Thanks for quick fix.
