### ISSUE TITLE
GitHistory is broken

### ISSUE THREAD

**Issue by nonoroazoro** [DonJayamanne/gitHistoryVSCode#293]
Seems that all the functions are broken. Here's the recording:

![git-history](https://user-images.githubusercontent.com/383132/42625506-80da3a64-85fa-11e8-9aaf-e2c7acd555f4.gif)

And the logs:

[git-history.log](https://github.com/DonJayamanne/gitHistoryVSCode/files/2188010/git-history.log)

The version of GitHistory is **0.4.1**
The version of VSCode is **1.2.5**

**Comment by JWleo** [comment]
just  install  the vs-code 1.24.1 again to solve this problem for temporary @nonoroazoro

**Comment by RevFry** [comment]
I'd rather not roll back Code just for the extension. It's like ditching your new car for the old one cause the blinker isn't working. :)

**Comment by RevFry** [comment]
Yeah, it looks like for me it's having problems creating a commit file in the temp directory.

**Comment by nonoroazoro** [comment]
@JWleo Thanks, I find out that it is broken in vs-code 1.25, now I'm using 1.24.1.

**Comment by benlindsay** [comment]
It's also mostly broken for me too. I can click on the commits but none of the commands work, and the text is all misaligned. I'm also pretty disinclined to reinstall an earlier version of VSCode to get around this.

![image](https://user-images.githubusercontent.com/9361152/42727004-2f2e5da8-876c-11e8-90e2-89aa05d20589.png)

**Comment by DonJayamanne** [comment]
Can someone please provide a repo I can use to replicate your issue. Thanks

**Comment by nonoroazoro** [comment]
@DonJayamanne You can just clone [the official babel repo](https://github.com/babel/babel) to reproduce.

**Comment by Exlsunshine** [comment]
Me too, hope some one could fix this.

**Comment by DonJayamanne** [comment]
Will release the fix tonight

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/DonJayamanne/gitHistoryVSCode/commit/3507e6b50cf6fb8f30ca842e1a1163dc32c2ee27

**Comment by benlindsay** [comment]
@DonJayamanne Thanks! Works great!
