### ISSUE TITLE
Add support for `git log --follow`

### ISSUE THREAD

**Issue by zgramana** [DonJayamanne/gitHistoryVSCode#30]
As a user, I want to be able to ensure `git log` is called with the `--follow`option, so that when I rename/move files I will still see the full git history for those files.

**Comment by zgramana** [comment]
Closing, as I see you recently merged @DonJayamanne PR #26 which adds this. 💯

**Comment by zgramana** [comment]
Looks like @douglas-mason's fix was lost in some refactoring: https://github.com/DonJayamanne/gitHistoryVSCode/commit/bd4100dce14c0c783d47496bedd183665de5651b#diff-298cac75e0205bd9de712014fd1f0178R117.

**Comment by DonJayamanne** [comment]
Oops

**Comment by DonJayamanne** [comment]
@zgramana , new build has been released.
