### ISSUE TITLE
Graphical view of branches ?

### ISSUE THREAD

**Issue by SheepDomination** [DonJayamanne/gitHistoryVSCode#305]
From my understanding you can view a graphical view of the branches; if so how do you know what color represents which branch ?

**Comment by DonJayamanne** [comment]
The colors are random, and there's no legend info.

**Comment by SheepDomination** [comment]
There is no way to tell the difference between branches, that is something which should be added, as the feature is good but it's needed to tell the difference between branches visually.

**Comment by SheepDomination** [comment]
When viewing the *git history* is that *only* github and if so; is there any way to change it to a private repository or switch between a private repository and github ?

**Comment by DonJayamanne** [comment]
> When viewing the git history is that only github and if so; is there any way to change it to a private repository or switch between a private repository and github ?

Out of scope

**Comment by SheepDomination** [comment]
What do you mean by, *out of scope* ?

**Comment by DonJayamanne** [comment]
> What do you mean by, out of scope ?

The git log only supports viewing local git repositories, not github, bitbucket, etc.

**Comment by SheepDomination** [comment]
Eight months is quite a delay in a response; even with another Job.
