### ISSUE TITLE
"Compare against previous version" doesn't work

### ISSUE THREAD

**Issue by dodok8** [DonJayamanne/gitHistoryVSCode#307]
When I use VS code and gitHistory on git repository save in USB flash drive(F:\), "Compare against previous version" doesn't work.
It returns error message like
```
git log --pretty=oneline 6a210d55a11636791bba18da0308527c462efc76^1 -n 1 -- C:\f:\study\PythonAlgorithmStudy\"Baekjoon\1328_\352\263\240\354\270\265 \353\271\214\353\224\251v1.py"  (completed in 0.318s)
fatal: Invalid path 'C:/f:': No such file or directory
```
Original file name is `1328_고층 빌딩v1.py`.

**Comment by MadaoChen** [comment]
I have the same problem

**Comment by tonyoldfield** [comment]
Same here.

**Comment by sh5525** [comment]
same here

**Comment by RevFry** [comment]
Yeah issue #297 I opened it a month ago.  For some reason everyone is having their project paths prepended with C: or /..

**Comment by gutmate** [comment]
same here

**Comment by iamvips** [comment]
Compare against previous version" doesn't work for me too. I am on VS 1.25.1 and it doesn't show me the changes done in the selected file and prints a message to Output as the "file is outside repository"

**Comment by AmitKKhanchandani** [comment]
Same here, Any Fixes?

**Comment by AmitKKhanchandani** [comment]
@DonJayamanne any update regarding this?

**Comment by Britford** [comment]
Same problem.  
git show xxxx:C:/e:/xxx/index.html  (completed in 0.046s)
fatal: Path 'C:/e:/xxx/index.html does not exist in xxx
Renders addon useless.

**Comment by erwanpoupard** [comment]
Same here with windows 10 and v1.26.1

**Comment by skydever** [comment]
... same here:

```bash
git log --pretty=oneline -n1 4b3b1bc7758d913f92eacac3fdcd06840fb3495c  (completed in 0.165s)
git show --pretty=oneline --decorate=full --numstat 4b3b1bc7758d913f92eacac3fdcd06840fb3495c  (completed in 0.36s)
git show --numstat --pretty=oneline -M 4b3b1bc7758d913f92eacac3fdcd06840fb3495c  (completed in 0.153s)
git show --name-status --pretty=oneline -M 4b3b1bc7758d913f92eacac3fdcd06840fb3495c  (completed in 0.182s)
git remote get-url origin  (completed in 0.064s)
git log --pretty=oneline 4b3b1bc7758d913f92eacac3fdcd06840fb3495c^1 -n 1 -- C:\d:\projects\some-path\a-file.js  (completed in 0.166s)
fatal: Invalid path 'C:/d:': No such file or directory

git show 4b3b1bc7758d913f92eacac3fdcd06840fb3495c:C:/d:/projects/some-path/a-file.js  (completed in 0.155s)
fatal: Path 'C:/d:/projects/some-path/a-file.js' does not exist in '4b3b1bc7758d913f92eacac3fdcd06840fb3495c'
```

**Comment by ZippoLee12138** [comment]
Same here

**Comment by ole1986** [comment]
@JWleo it would be good to know if th unofficial release from PR #316 also works for you.

By chance, can you test it?!

**Comment by JWleo** [comment]
@ole1986 Fine. I will tell you about the result after testing.

**Comment by JWleo** [comment]
@ole1986 yeah,Cool!!!!!! It works on window10 by using your VSIX file to update the office realese0.42. Thanks.
The office realese 0.42 is just fine on linux, so i don't need to install your VSIX file.

**Comment by skydever** [comment]
I am still facing this issue, is this already part of the current release?

```bash
fatal: Invalid path 'C:/d:': No such file or directory
```
