### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by ahmadawais** [DonJayamanne/gitHistoryVSCode#309]
Love this extension!

Two issues:
1: Buttons UI is not from the theme which looks very very odd
![image](https://on.ahmda.ws/3A352v3X3k1F/c)
2: My GitHub account is https://github.com/AhmadAwais and it has my profile pic as well but Git History is reporting the wrong image of who knows who

![image](https://on.ahmda.ws/0t1O280g221D/c)

Kindly, fix these two issues.

**Comment by ole1986** [comment]
This should be fixed!
