### ISSUE TITLE
Dates are being shown in other language!

### ISSUE THREAD

**Issue by Adnanhaddad96** [DonJayamanne/gitHistoryVSCode#317]
Hi. All dates of my commits are being shown in Arabic. Only the dates are affected by this. Do you have an idea of where this could come from?

![window-09-19-17](https://user-images.githubusercontent.com/33404398/45267018-11e95100-b465-11e8-905f-dd895394df3f.png)

**Comment by ashtrail** [comment]
I have exactly the same issue except the dates are written in Korean. I did buy my computer in Korea, so maybe it has something to do with that, but the language on my OS and vscode is english.
I'm on OSX Mojave 10.14, VSCode 1.28.2 and GitHistory 0.4.3.

<img width="410" alt="screen shot 2018-10-31 at 22 06 22" src="https://user-images.githubusercontent.com/10834082/47819152-ee9e9c00-dd59-11e8-8da8-ead9f01c2544.png">

**Comment by ole1986** [comment]
IS this still an issue after we have fixed language part with commit 
427bf71?

**Comment by ole1986** [comment]
I assume this is no more an issue. Because of the change using vscode display language instead of system language
