### ISSUE TITLE
gitHistory tmp- files in my Linux tmp directory appearing in my vscode linting list

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [DonJayamanne/gitHistoryVSCode#32]
Hello,

I just installed the add-on, had a look at the git file history of a few commits and then found all these tmp- files in my tmp dir. They are for some reason being brought up in my linting dialogue which is not good news.

When I restart vscode they are gone, but i don't want to have to do that every time i look at a git history. It does not matter if the files are open or not, they still show up.

Please see the attached screen shot, is this a bug or can I change a setting? THANKS.

PS I am using Fedora Linux (which is working 100% perfectly for vscode :)
![screenshot from 2016-09-06 16-12-17](https://cloud.githubusercontent.com/assets/12832280/18279394/43e229c0-744d-11e6-93c9-6bf78cd81023.png)

**Comment by DonJayamanne** [comment]
@Learn-Digital-Audio , I have released a new version.
Once you close the temporary file, the linter messages should dissappear. However, there's not much I can do about linter messages being displayed for the temporary files. This would be a configuration issue of the linter, i.e. if there's an option to limit messages to certain directories, etc.

**Comment by Learn-Digital-Audio** [comment]
Thanks for looking into this!
