### ISSUE TITLE
Native git extension api

### ISSUE THREAD

**Issue by ole1986** [DonJayamanne/gitHistoryVSCode#322]
We may soon be able to use the git extension api shipped with vscode natively.

not sure if all is covered but at least some parts can already reduce the code IMO. 

More details (at bottom you can find the API reference) 
https://github.com/Microsoft/vscode/issues/31103#issuecomment-424043103

**Comment by DonJayamanne** [comment]
I've had a look at it, unfortunately not all will be covered. If i remember correctly the data returned by the API is a little too basic. However it is something we should be using to improve the stability of this extension.

**Comment by DonJayamanne** [comment]
@ole1986 	Did you reach out to be via email?

**Comment by ole1986** [comment]
@DonJayamanne I already sent you an email asking to support you..

**Comment by DonJayamanne** [comment]
Will add you soon, have been away for 1.5 months on holiday, got back phone isn't working (can't authenticate on github to change any permissions due to two factor auth - can't do without a phone...).
Thanks, will add you as a collaborator soon.

**Comment by ole1986** [comment]
Check Out PR #410 for further details
