### ISSUE TITLE
Add Azure Dev CI

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#324]

**Comment by ole1986** [comment]
how is it going with CI?!

**Comment by DonJayamanne** [comment]
Sorry about this, been a little busy with some other work as well.
Also, damn GitHub announced GitHub Actions, and now I'm kinda hoping to try that out.

**Comment by DonJayamanne** [comment]
I noticed you haven't given your self credit in the readme page. I'll add that.

**Comment by ole1986** [comment]
Since we have now GitHub actions, can we close this issue?

**Comment by DonJayamanne** [comment]
Oh yes
