### ISSUE TITLE
Broken commit comparison (select / compare)

### ISSUE THREAD

**Issue by ole1986** [DonJayamanne/gitHistoryVSCode#326]
not to confused with the file file comparison it seems that the **commit compare** feature is broken, too

When I try to select a commit and afterwards choice the "Compare with..." nothing actually happens

![image](https://user-images.githubusercontent.com/4850116/46483858-e570ec80-c7f8-11e8-9442-8206ec9bdc91.png)

![image](https://user-images.githubusercontent.com/4850116/46484031-37b20d80-c7f9-11e8-9b4b-a179f05da376.png)

I haven't used this feature at all and actually do not know what the outcome is supposed to be.
Will double check the source, but maybe someone can explain me this?!

**Comment by ole1986** [comment]
For of you who searched for the results, its actually `compare Commits`  view which is simple not focused when the command is being executed.

This view can be focus using `>Explorer: Focus on Compare Commits View` command

**Comment by DonJayamanne** [comment]
I need to test this my self. The user shouldn't have to set focus, we should do it for them.

**Comment by DonJayamanne** [comment]
Awesome, thanks for the fix
