### ISSUE TITLE
Any support for external git difftool/mergetool?

### ISSUE THREAD

**Issue by waynebloss** [DonJayamanne/gitHistoryVSCode#337]
I'd like to run an external diff/merge tool instead of using the built-in one.

Is there any support for that?

Currently I'm using an extension called GitDiffer to run the command `git difftool` for current changes, but it doesn't work for historical changes.

**Comment by DonJayamanne** [comment]
Currently we utilize whats available in VS Code.
You'll need to report this feature request upstream to VS Code.
