### ISSUE TITLE
Bug on use -> View File History

### ISSUE THREAD

**Issue by igor-h** [DonJayamanne/gitHistoryVSCode#338]
git rev-parse --show-toplevel  (completed in 0.008s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.007s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}

**Comment by ole1986** [comment]
Possible reason is that git is not properly installed or registered.
A complete Git History log output from vscode  would be very helpful.

Also feel free to provide us with the following information

* Version number of git history extension
* Version number of git cmdlet
* Version number of Vscode
* OS information

Thank you in advanced

**Comment by igor-h** [comment]
Version number of git history extension: **0.4.3**
Version number of git cmdlet:  git version: 2.19.1
Version number of Vscode:  Version: 1.28.2 (user setup)
OS information:

Date: 2018-10-17T00:23:51.859Z
Windows 10 Pro
Architecture: x64

**Comment by igor-h** [comment]
any idea?

**Comment by ole1986** [comment]
@igor-h can you please provide me with the complete Git History log output.

I still think it cannot properly find the git binary being executed.

**Comment by igor-h** [comment]
git rev-parse --show-toplevel  (completed in 0.006s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.004s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.004s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.002s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.001s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.003s)
git rev-parse --show-toplevel  (completed in 0.006s)
git rev-parse --show-toplevel  (completed in 0.008s)
git rev-parse --show-toplevel  (completed in 0.009s)
git rev-parse --show-toplevel  (completed in 0.011s)
git rev-parse --show-toplevel  (completed in 0.01s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.009s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.008s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.003s)
{"stack":"Error: spawn git ENOENT\n\tat _errnoException (util.js:1024:11)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n\tat onErrorNT (internal/child_process.js:372:16)\n\tat _combinedTickCallback (internal/process/next_tick.js:138:11)\n\tat process._tickCallback (internal/process/next_tick.js:180:9)","message":"spawn git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn git","path":"git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.005s)
git rev-parse --show-toplevel  (completed in 0.01s)
git rev-parse --show-toplevel  (completed in 0.012s)
git rev-parse --show-toplevel  (completed in 0.013s)

**Comment by igor-h** [comment]
Maybe can Help, NodeJS v6.7.0

**Comment by ole1986** [comment]
iam sure v0.4.4 will fix this issue as it will fetch git path natively

**Comment by igor-h** [comment]
Thanks

**Comment by igor-h** [comment]
in vscode market, is still version 0.4.3

https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory#overview

**Comment by ole1986** [comment]
@DonJayamanne Can you by chance update it on marketplace?

**Comment by igor-h** [comment]
@ole1986 solved in version 0.4.4
