### ISSUE TITLE
GitLog not responding

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#34]
@gjstockham
>'ve done a complete re-install of VS Code. Without the icons extension, I don't get the admin prompt, but I still get nothing from git history. It looks like it is hanging.

**Comment by frankyan** [comment]
I encountered the same problem. 

>windows 10 Pro 64bit
Visual studio code version 1.5.2
git version 2.10.0.windows.1, installed with GitHub desktop windows

**Comment by frankyan** [comment]
I found the problem. There was something wrong with my git installation. It cannot be executed in CMD. That's the reason.

**Comment by castanjt** [comment]
Encountered this as well. I have Git setup as Bash on Windows. @frankyan, what was your fix? Did you have to reinstall Git or was there a work around in order to run git from cmd in order to get gitHistoryVSCode to work?

**Comment by frankyan** [comment]
@castanjt I had Github desktop installed but git couldn't be executed in CMD. So I installed the newest git downloaded from https://git-scm.com/. Then it worked. 
I think you should make sure that git can be executed in windows cmd instead of Bash on windows.

**Comment by raffy-dev** [comment]
I have the same problem, nothing happens when I select 'show history for..' 
I tried to reinstall githistoryvscode and Git but nothing changed
windows 10 Pro 64bit
git  version 2.15.1.windows.2
