### ISSUE TITLE
[Security] flatmap-stream is compromised

### ISSUE THREAD

**Issue by iamtekeste** [DonJayamanne/gitHistoryVSCode#350]
I think this project is using a compromised package called `flatmap-stream`. Here is more details on this compromised package 
https://github.com/dominictarr/event-stream/issues/116.

After running `find ~ -name "flatmap-stream"` on my machine, this project was the only one that had a reference to that package.

@DonJayamanne

**Comment by DonJayamanne** [comment]
Thanks, closing as a dup of https://github.com/DonJayamanne/gitHistoryVSCode/issues/351

**Comment by DonJayamanne** [comment]
A new version of the extension was release pinning to the right version of event-stream

**Comment by iamtekeste** [comment]
@DonJayamanne Thanks for the quick reply! Does this mean it is safe to use the extension again?

**Comment by DonJayamanne** [comment]
Yes,
