### ISSUE TITLE
vscode 1.30.0 vs git 2.7.4 "git status --porcelain=v1" error

### ISSUE THREAD

**Issue by GloobyBoolga** [DonJayamanne/gitHistoryVSCode#353]
**Git history** Version 0.4.4
**git** git version 2.7.4
**vscode** 1.30.0, c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, x64

git history fails with:
```
git status --porcelain=v1 -b --untracked-files=no  (completed in 0.006s)
option `porcelain' takes no value
```

**Comment by ole1986** [comment]
Your git version does not support any porcelain option.

Please update git cmdlet and you will be fine using git history.
