### ISSUE TITLE
Compare between two non-consecutive versions of a file

### ISSUE THREAD

**Issue by fairmonk** [DonJayamanne/gitHistoryVSCode#354]
trying to compare a file's version with file's version-2
Is this possible ? Currently I see only "Compare against previous version" option. Thank you !
![image](https://user-images.githubusercontent.com/9027632/51060635-0c5d6c80-15f9-11e9-9d14-52c3202e25fb.png)

using VS Code 1.30.1
git history 0.4.4

**Comment by DonJayamanne** [comment]
Please check the menu option, view file history.
From there you can compare two commits and check the difference between two commits for a file.
