### ISSUE TITLE
error an error occurred while running git rev-parse head (exit code 128)

### ISSUE THREAD

**Issue by Foxveer** [DonJayamanne/gitHistoryVSCode#363]
when i try cmd
ionic package build android

**Comment by ole1986** [comment]
@Foxveer I am not sure if this has something to do with the gitHistory extension

**Comment by Foxveer** [comment]
i'm trying to build apk without android studio

**Comment by ole1986** [comment]
@Foxveer then you should better search a solution here I guess: https://github.com/ionic-team/ionic/issues
