### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Inant** [DonJayamanne/gitHistoryVSCode#366]
- Issue Type: `Performance`
- Extension Name: `githistory`
- Extension Version: `0.4.6`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Inant Kharisma\donjayamanne.githistory-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DonJayamanne** [comment]
Please attach the `cpuprofile.txt` file.
Will re-open once attached
