### ISSUE TITLE
Don't complain, if there is no remote

### ISSUE THREAD

**Issue by sergiz** [DonJayamanne/gitHistoryVSCode#368]
Hello.

If there is no remote set (only local git repo), the plugin will open output and display

> git remote get-url origin  (completed in 0.05s)
fatal: No such remote 

every time you want to see git history using this plugin. Very annoying. I see there were some fixes introduced when there are multiple remotes, but in my case there is no remote.

**Comment by ctaleck** [comment]
I came here for the same reason: "Very annoying" for it to auto-switch my _terminal_ tab to the _output_ tab... 

Is there an option to suppress **gitHistory** from executing `git remote get-url origin`?

**Comment by jeffnm** [comment]
This also happens if you do have remotes, but none of them are named "origin". 

I think origin is a convention, not a requirement, and for some repositories it makes sense to use more explicit remote names.

In any case, this shouldn't be a fatal response since remotes are definitely optional.
