### ISSUE TITLE
Long commit messages pushes the blue clipboard image to the right

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#37]
@kumarharsh 
If the comments are very long, then the copy (blue) box is on the right
Ideally the comments should get truncated (with ellipsis) - that's what used to happen

**Comment by kumarharsh** [comment]
I think this is a bug rather than an enhancement.
The culprit would be the flexbox I'm using. Webkit has a problem with text not wrapping and expanding the container. Should be an easy fix, I'll look into this tonight if possible.

**Comment by DonJayamanne** [comment]
@kumarharsh , i dont think we should wrap the text. We can't have the box growing vertically, else that stuffs up the git graph on the left. 
I leave it up to you to check this out.
