### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Rajpratik71** [DonJayamanne/gitHistoryVSCode#370]
- Issue Type: `Performance`
- Extension Name: `githistory`
- Extension Version: `0.4.6`
- OS Version: `Linux x64 4.15.0-24-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/reddragon/donjayamanne.githistory-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[donjayamanne.githistory-unresponsive.cpuprofile.txt](https://github.com/DonJayamanne/gitHistoryVSCode/files/2993036/donjayamanne.githistory-unresponsive.cpuprofile.txt)

**Comment by mavaddat** [comment]
> * Issue Type: `Performance`
> * Extension Name: `githistory`
> * Extension Version: `0.4.13`
> * OS Version: `Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0`
> * VSCode version: `Visual Studio Code - Insiders
Version: 1.42.0-insider (user setup)
Commit: fd13e449f5f2fe300f187129d6065ed1cfad74d3
Date: 2020-01-17T17:23:31.960Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363`
> 
> ⚠️ Make sure to **attach** this file from your _home_-directory: `/home/reddragon/donjayamanne.githistory-unresponsive.cpuprofile.txt` ⚠️
> 
> Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
> 
[donjayamanne.githistory-unresponsive.cpuprofile.txt](https://github.com/DonJayamanne/gitHistoryVSCode/files/4083957/donjayamanne.githistory-unresponsive.cpuprofile.txt)

**Comment by ole1986** [comment]
Since we have improved several things I am closing it.
If you think this is wrong feel free to reopen
