### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by digitalapplebee** [DonJayamanne/gitHistoryVSCode#371]
- Issue Type: `Performance`
- Extension Name: `githistory`
- Extension Version: `0.4.6`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/home/donjayamanne.githistory-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DonJayamanne** [comment]
Please attach the `cpuprofile.txt` file.
Will re-open once attached
