### ISSUE TITLE
Support running remotely for VS Code Remote Development

### ISSUE THREAD

**Issue by mjbvz** [DonJayamanne/gitHistoryVSCode#379]
Hi, I'm on the VS Code team. We recently released support for [Remote Development](https://code.visualstudio.com/blogs/2019/05/02/remote-development) and I believe that your extension may not work properly when run in a remote workspace

## Problem
To make remote development as transparent as possible to users, VS Code distinguishes two classes of extensions:

- **UI Extensions**: These extensions make contributions to the VS Code user interface and are always run on the user's local machine. UI Extensions cannot directly access files in the workspace, or run scripts/tools installed in that workspace or on the machine. Example UI Extensions include: themes, snippets, language grammars, and keymaps.

- **Workspace Extensions**: These extensions are run on the same machine as where the workspace is located. When in a local workspace, Workspace Extensions are run on the local machine. When in a remote workspace, Workspace Extensions are run on the remote machine. Workspace Extensions can access files in the workspace to provide rich, multi-file language services, debugger support, or perform complex operations on multiple files in workspace (either themselves or by invoking scripts/tools). 

You can find more details about this architecture [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types).

Your extension is currently running as workspace extension. This means that the server it starts will be run on the remote machine, which in turn means that webview will not be able to access it using `localhost` since the webview is running on the user's local machine:

## Potential Fix
We've introduced a new webview [port mapping API](https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-webview-api) that should make it possible for your extension to run remotely with fairly minor modifications. 

Please let me know if you have any questions about the issue or the new apis. We've also put together [a guide](https://code.visualstudio.com/api/advanced-topics/remote-extensions#testing-and-debugging-your-extension) to help you test your extension in remote workspaces

**Comment by waynebloss** [comment]
@mjbvz None of the issues that I've seen detail which port should be forwarded for git.

One of the issues said "you can add a forwarded port" to make this extension work, but it didn't say which one.

I didn't think you needed any ports for git to work. Am I to run a git server on my remote machine for this? What am I missing?

Thanks!

**Comment by waynebloss** [comment]
OK, I figured it out - you need to open up the `Output` panel and look at the output for `Git History`.

Since the port number changes every time, you need to forward the port each time you open the remote folder.

**Comment by waynebloss** [comment]
Also, I found that you can't forward the port while the blank and broken `Git History` log view is open.

I assume that's because it's continually trying to connect or something.

**Comment by shinyT** [comment]
Thans 

> OK, I figured it out - you need to open up the `Output` panel and look at the output for `Git History` for the following line and take the port number from there _(9999 in this case)_:
> 
> ```
> Server running on http://localhost:9999/?_&id=xxxxxyyyyyzzzz&branchName=master&file=&theme=&branchSelection=1&locale=en_US
> ```
> 
> Since the port number changes every time, you need to forward the port each time you open the remote folder.

Thanks
According to your answer, I found a way to temporarily forward a new port for the duration of the SSH session. "

> run the Remote-SSH: Forward Port from Active Host... command when connected to an active SSH host."

[https://code.visualstudio.com/docs/remote/ssh](url)

**Comment by ole1986** [comment]
This will be fixed in PR #401 without configuring Remote-SSH to forward ports

**Comment by kis87988** [comment]
Is there possible we can get the merge version? since the release is not coming yet

**Comment by ole1986** [comment]
With the last update of vscode today they have increased the amount of css styles which causes to break the url request due to max length limitation.

Trying to fix this using postMessage now.

I also added GitHub action for vsce deployment. Unfortunately no response yet from @DonJayamanne to publish versions directly from GitHub.

**Comment by ole1986** [comment]
For those who cannot wait giving me feedback on my work.
You can download the version 0.4.8 ([2f1f260](https://github.com/DonJayamanne/gitHistoryVSCode/pull/405/commits/2f1f2604e70f1dda200d677da6caa5213cc641c2)) from [here](https://drive.google.com/file/d/1G7ss9zsJjF40msE7PNrn8Ik_4DW4iMgU/view?usp=sharing).

**PLEASE NOTE:**
Do not use the `Install in SSH: <Remote>` from the extensions sidebar as it will install the latest available version (0.4.6) from marketplace. Instead upload the file to your remote and choice `Install from VSIX` from the Extensions context menu while being connect to your remote.

**Comment by ole1986** [comment]
Please also take note about this issue #395
