### ISSUE TITLE
Merge scripts rendered in webview using WebPack

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#38]
Merge the scripts as done in the Python (Jupyter) branch:
- [webpack.config.js](https://github.com/DonJayamanne/pythonVSCode/blob/8cb501371de54a6a2c7dd21f8efecf07bc4d7c36/webpack.config.js)  
- [browser folder](https://github.com/DonJayamanne/pythonVSCode/tree/8cb501371de54a6a2c7dd21f8efecf07bc4d7c36/src/client/jupyter/browser)  

Makes it easier to manage the scripts

**Comment by mikes-gh** [comment]
Closing in favour of #108
