### ISSUE TITLE
Git log multi-root missing repositories

### ISSUE THREAD

**Issue by guilala** [DonJayamanne/gitHistoryVSCode#381]
After issuing a git log in a multi-root work space, a repository selection list is now shown. But it's incomplete. The list should show any git repository that is also visible in 'source control providers' in the source control side bar. But the list doesn't contain the git repositories of the work spaces that are a child directory of a git repository.

**Comment by ole1986** [comment]
This will hopefully be resolved in PR #410 as it is using the native git extension API to gather all repos

**Comment by ole1986** [comment]
I assume this will be fixed with v0.5.0
