### ISSUE TITLE
Give focus to the already opened Git History tab on View history command

### ISSUE THREAD

**Issue by charlesg99** [DonJayamanne/gitHistoryVSCode#382]
Currently, if you click on the top right Git icon to invoke the `Git: View History (git log)` command and already have the Git History view opened, nothing happens. This is a bit confusing when many other tabs are opened and the Git History one isn't visible because it is scrolled out of view. 

It would be nice to give focus to the Git History view if you click on the top right Git icon when it is already opened. Thanks!

**Comment by ole1986** [comment]
Duplicate #365
