### ISSUE TITLE
Type to jump to specific author in author filter

### ISSUE THREAD

**Issue by josephsieh** [DonJayamanne/gitHistoryVSCode#384]
Currently, if the git repo is contributed by many authors, it is tedious to filter the commits by certain author.  Users will need to scroll down the "All Authors" popup and find the specific author in interest by themselves.

It will be way easier if user can have the mouse cursor hover over the by default "All Authors" popup, or within the "All Authors" popup dialog, and start typing to jump to the right author.

**Comment by totszwai** [comment]
Can confirm... unable to select the author... The dropdown was only able to show like a dozen authors, which doesn't even cover the usernames starting with As. 🤣

**Comment by ole1986** [comment]
Soon you will be able to filter from dropdown and by clicking the author filter icon within a commit

![image](https://user-images.githubusercontent.com/4850116/74145787-f0fbd100-4bff-11ea-9e1d-c1dcb6275e80.png)
