### ISSUE TITLE
Git History don't work on vs code remote environment 

### ISSUE THREAD

**Issue by xajhuang** [DonJayamanne/gitHistoryVSCode#389]
VS Code used ssh connect to remote host. The git history don't work, but it's run correct on local host.

**Comment by yutiny** [comment]
You can add forwarded port in remote ssh, but the git history port is not the same when i reopen the remote ssh.

**Comment by sly1061101** [comment]
+1
Hope to get this fixed.

**Comment by dusty-phillips** [comment]
duplicate of #379

**Comment by senlinding** [comment]
me too

**Comment by DonJayamanne** [comment]
Sorry guys, I'll be looking into this in the next week or so.
Apologies for the delay in getting back with a response and a fix.

**Comment by ole1986** [comment]
Since vscode API >= 1.34 Port Mapping on createWebviewPanel has been achieved.
[more info on StackOverflow](https://stackoverflow.com/questions/55978517/why-does-localhost-not-work-inside-my-vs-codes-webviews-when-connected-to-remot)

I will give it a try in branch `remote-support`

**Comment by b-trav** [comment]
Hi, I was hoping someone could explain how to get the git history extension working for code-server - the remote version of vs code. I am accessing code-server by using ssh tunnels, however git history seems to be using a random port. Even if I then create a tunnel for this port, I get localhost refused to connect when I attempt to look at git history

**Comment by ole1986** [comment]
@b-trav 

I am not quite familiar with code-server, but I can provide you some info on how it currently works with a remote connection

express is using a random port when the listen command is executed - [see here](https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/server/serverHost.ts#L65)
This port mapping is achieved through the webView portMapping property [here](https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/commandHandlers/gitHistory.ts#L84) while the random port is used as extensionHostPort and <random port + 1> is used as webviewPort.

You can read more about the Webview portMapping here: 
https://code.visualstudio.com/api/references/vscode-api#Webview

**Comment by JeffreyO** [comment]
Is there a fix for this? I'm trying to use Azure Devops remote git repo.
