### ISSUE TITLE
How to find a specific file when viewing commit changes?

### ISSUE THREAD

**Issue by thinkerdu** [DonJayamanne/gitHistoryVSCode#393]
Hi, if I have a long list of changed files, how do I find a specific file like I would with `Ctrl + F`?
![image](https://user-images.githubusercontent.com/28700378/61574211-d4c30600-aaee-11e9-8790-efa292116622.png)

**Comment by ole1986** [comment]
Available with the next version

![image](https://user-images.githubusercontent.com/4850116/70249454-b0558680-177c-11ea-83b1-97c2a7b57cd4.png)
