### ISSUE TITLE
[BUG] commit date error

### ISSUE THREAD

**Issue by Ran-snow** [DonJayamanne/gitHistoryVSCode#394]
![image](https://user-images.githubusercontent.com/18158510/61600218-2fc93a00-ac62-11e9-8b5b-1b2c37f417ff.png)
![image](https://user-images.githubusercontent.com/18158510/61600236-47082780-ac62-11e9-9cbc-99905fb96ca9.png)

**Comment by ole1986** [comment]
May you explain to me what exactly the error is and if this still persist?

**Comment by ole1986** [comment]
Closing it as not reproducible
