### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by MigMigDev** [DonJayamanne/gitHistoryVSCode#395]
It takes too long for the first time to show log history. I've attached the log issue
(https://github.com/DonJayamanne/gitHistoryVSCode/files/3439297/donjayamanne.githistory-unresponsive.cpuprofile.txt)

**Comment by ole1986** [comment]
Have you tried to reduce the amount of commits using the `Page Size` settings for the extension?
By default its 100 which may cause this performance issue

**Comment by ole1986** [comment]
With v0.4.8 the performance should slightly be increased. Especially for remote connections
