### ISSUE TITLE
Next button is enabled though history is few

### ISSUE THREAD

**Issue by threeFatCat** [DonJayamanne/gitHistoryVSCode#400]
VSCode 1.38.1
OS Windows 10

Reproduce:
- Filter results where there will be less results (maybe between 1-10). Next button is enable and when you click it, it will route you to a blank page.

![1111](https://user-images.githubusercontent.com/11312281/65687974-dc79ca80-e09c-11e9-99b3-b01821000cad.PNG)
![image](https://user-images.githubusercontent.com/11312281/65688123-219dfc80-e09d-11e9-879b-a5327755c372.png)

Expectation:
- Next is disabled since results can fit in one page.

**Comment by DonJayamanne** [comment]
Apologies for never getting back to you on this, does this issue still exist?

**Comment by threeFatCat** [comment]
@DonJayamanne , no worries, it's not a deal breaker though. Right now when I tried to filter it to a smaller results (e.g by author) with 2 items on list. The Next button is enabled, and clicking on it will reset the filter to All authors and show the default list without filter.
