### ISSUE TITLE
View file history not working when a repo contains a submodule

### ISSUE THREAD

**Issue by rickstaa** [DonJayamanne/gitHistoryVSCode#408]
The view file history command is not working in the newest vscode insider release. Further, no console output is given.

- Also happens with all other extensions disabled
- Only happens in git repositories with git submodules.

#### System info
- **Version:** 1.41.0-insider
- **Commit:** 599c076d91be1374cf51004cec610f3bcaf4c9cd
- **Date:** 2019-11-22T07:25:13.067Z
- **Electron:** 6.1.5
- **Chrome:** 76.0.3809.146
- **Node.js:** 12.4.0
- **V8:** 7.6.303.31-electron.0
- **OS:** Linux x64 5.0.0-36-generic
- **Extension version:** Version 0.4.6

**Comment by rickstaa** [comment]
Closed as it did work but just took a very long time to initialize.

**Comment by ole1986** [comment]
I noticed the same.. 
Already trying to improve it using git extension API

**Comment by rickstaa** [comment]
@ole1986 Thanks a lot! Do you already have a issue or do you want me to reopen this one?

**Comment by ole1986** [comment]
I do already have a local branch and going to create a PR for it. 

Also version 0.4.8 should have a slight performance improvement due to some bundled things
