### ISSUE TITLE
command 'git.viewHistory' not found

### ISSUE THREAD

**Issue by reishapira** [DonJayamanne/gitHistoryVSCode#411]
Just upgraded from 0.4.6 to 0.4.8, getting this error:
command 'git.viewHistory' not found

Installing the older 0.4.6 version resolved the issue.

VS code about:

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-23-generic

**Comment by ole1986** [comment]
Deployment issue due to missing tsc compile command in vscode:prepublish
