### ISSUE TITLE
Update CHANGELOG file

### ISSUE THREAD

**Issue by julian-poidevin** [DonJayamanne/gitHistoryVSCode#415]
Changelog file has not been updated since [Version 0.4.7](https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/CHANGELOG.md#version-047)

It should be updated at each release so users can see changes right in VSCode instead of going to the [release ](https://github.com/DonJayamanne/gitHistoryVSCode/releases)page.

**Comment by ole1986** [comment]
Shame on me.

I assume the repo is also hosted on visual studio, So @DonJayamanne may need to pull it from there to make it available on marketplace.
