### ISSUE TITLE
branch picker list is not scrollable in Git History page 

### ISSUE THREAD

**Issue by ethanshar** [DonJayamanne/gitHistoryVSCode#417]
First, Thanks for this amazing tool!

How to reproduce:
Open Git History page  and try to change the branch you're looking at. 

If your repo has too many branches you'll get a long list which unfortunately isn't possible to scroll, therefore you can't reach the branches at the bottom.

This has started happening in the last version or the one before it.

**Comment by ole1986** [comment]
@ethanshar  Can you please provide me with a screenshot?

Also would be helpful to have a rough number of how many branches we are talking about.

Thank you

**Comment by ethanshar** [comment]
Hey @ole1986, 

here's a screenshot
![Screen Shot 2019-12-18 at 13 14 57](https://user-images.githubusercontent.com/1780255/71081770-96626d80-2198-11ea-855e-bc183dcc29ad.png)

talking about more than 30 branches

**Comment by ole1986** [comment]
We may need a similar solution for #384, too!

**Comment by ole1986** [comment]
Thinking of [bootstrap-select](https://developer.snapappointments.com/bootstrap-select/examples/)

**Comment by ole1986** [comment]
OMG... Some "§" has crept into the [main.css on line 610](https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/browser/src/main.css#L610)
I am gonna fix this first

**Comment by DonJayamanne** [comment]
I believe this has been resolved.
If not please do get back to us and we'll be happy to reopen this or please do create a new issue
