### ISSUE TITLE
The "All Authors"  Can't  Scroll

### ISSUE THREAD

**Issue by zhb124404** [DonJayamanne/gitHistoryVSCode#422]
Issue Type: <b>Bug</b>

This list can't show all authors when there are many authors, consider to support scroll?

Extension version: 0.4.11
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

**Comment by ole1986** [comment]
@zhb124404 To my surprise the scrolling seem to work the same as the branches (which has been fixed in #417)

![image](https://user-images.githubusercontent.com/4850116/72047504-f55c6380-32ba-11ea-995e-0c98494f7a67.png)

**Comment by zhb124404** [comment]
there is no scroll 
![Snipaste_2020-01-09_15-41-52](https://user-images.githubusercontent.com/16805041/72047971-b4824000-32f6-11ea-9404-82ba4e8819a8.png)

**Comment by ole1986** [comment]
Please update to version 0.4.12 or higher
https://github.com/DonJayamanne/gitHistoryVSCode/releases/tag/0.4.12
