### ISSUE TITLE
Do not show hidden submodules 

### ISSUE THREAD

**Issue by xmedeko** [DonJayamanne/gitHistoryVSCode#424]
I ahve a repo with some submodules and I have hidden these submodules in VS Code Source Control (Ctrl+Shift+G), because these submodules are read-only for me.  (Right click, hide) When I use gitHistoryVSCode e.g. to show File History, I do not want to have these hidden submodules in the list of modules to choose. The list contains all submodules, though.

Probably related to microsoft/vscode#88670

**Comment by xmedeko** [comment]
Closing the repository solves the issue. See microsoft/vscode#88670

**Comment by ole1986** [comment]
Are you using the version of the PR #410? Otherwise I couldn't believe all previous version solve this issue!

**Comment by xmedeko** [comment]
I have a Git History 0.4.13. When I do Close Repository, I reallo do not see the submodule when trying to show File History.
