### ISSUE TITLE
Release vsix extension files

### ISSUE THREAD

**Issue by mirekphd** [DonJayamanne/gitHistoryVSCode#426]
Please release also the compiled vsix extension file, apart from the source code. A good example can be found here:
https://github.com/Azure/vscode-kubernetes-tools/releases

**Comment by ole1986** [comment]
Mhm.. we may be able to automate this using the following github action:
https://github.com/actions/upload-release-asset

**Comment by ole1986** [comment]
That was easier than expected. We have now automated it on every publish using `vsce-attach-file.yml` workflow

I might put this into `vsce-publish.yml` later one
