### ISSUE TITLE
Key input not working after certain actions

### ISSUE THREAD

**Issue by RLusseni** [DonJayamanne/gitHistoryVSCode#427]
After certain actions (e.g. pressing "Copy the full hash" in the git history view) successive keyboard inputs are not recognized anymore (e.g. open command menu by pressing switching tabs by pressing CTRL+TAB)

After clicking anywhere outside the git history view will "reactivate" keyboard inputs again

```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

```
Name: Git History
Id: donjayamanne.githistory
Description: View git log, file history, compare branches or commits
Version: 0.4.13
Publisher: Don Jayamanne
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory
```

**Comment by ole1986** [comment]
I am not quite sure if this may have something to du with the iframe being nested inside the webviewPanel.

The key input issue may also be related to #421

**Comment by DonJayamanne** [comment]
I'll get rid of the iframe this well
