### ISSUE TITLE
View History on Moved File Causes Error

### ISSUE THREAD

**Issue by CoryKroll** [DonJayamanne/gitHistoryVSCode#43]
I have a git repo where I initially saved a file under a folder and did a commit.  Then, I moved the file up to the root and did another commit.  

When right-clicking and attempting to view the history of this file (by selecting Git: View File History > (select older checkin) > Compare against workspace file), I get an error.

In the output log, I get:
fatal: Path 'app.js' exists on disk, but not in '8b9d22275d80e46f12076fefb7c81e82817fd0fb'.

app.js was the file that moved between commits.

I am using 0.0.12.

**Comment by rkeithhill** [comment]
I see the same error but I used `git mv` to move a folder.

**Comment by mikes-gh** [comment]
Yes it's all the same issue.  Next on list to fix.
