### ISSUE TITLE
Recent change makes "hash/tag/branch/more" unreadable

### ISSUE THREAD

**Issue by cyrusdaboo** [DonJayamanne/gitHistoryVSCode#430]
The recent change to the "actions" item has made it unreadable on my device. See screenshot.

<img width="385" alt="Screen Shot 2020-02-01 at 12 09 42 PM" src="https://user-images.githubusercontent.com/13540930/73595968-f8c6c180-44eb-11ea-8618-c4061baa6f18.png">

**Comment by cyrusdaboo** [comment]
I am using `Light (Visual Studio)` theme.

**Comment by ole1986** [comment]
@cyrusdaboo thank you for reporting

Its pretty strange since I have checked the behaviour of changing the color theme. But i will double check it

**Comment by cyrusdaboo** [comment]
Thanks for the quick turn around on this.
