### ISSUE TITLE
History not showing when VS Code is in Admin mode

### ISSUE THREAD

**Issue by pretyk** [DonJayamanne/gitHistoryVSCode#431]

**Comment by ole1986** [comment]
Do you have further info on how you open it in admin mode.
Also OS version and extension version would be helpful

**Comment by ole1986** [comment]
@pretyk Any further details?

**Comment by ole1986** [comment]
Running the extension in vscode as administrator does not seem to have any influence.
Below screenshot shows vscode running as admin.

![image](https://user-images.githubusercontent.com/4850116/74585408-799db700-4fdc-11ea-9a51-b8578a7423b5.png)
