### ISSUE TITLE
Unable to view git history of a file from initial commit

### ISSUE THREAD

**Issue by astralmaster** [DonJayamanne/gitHistoryVSCode#432]
Right click on a file (tab) -> Git: View File History -> from the list of commits select the first (earliest) one -> up comes the list of files, click on any file -> nothing opens. 

This happens only when trying to open file from initial commit. From other commits, all files open up fine.

**Comment by ole1986** [comment]
@astralmaster  Can you please provide us the the Git History output log. Thank you

**Comment by astralmaster** [comment]
@ole1986 Here you go, however none of these lines are outputted after I click the files that have no reaction.

`git rev-parse --show-toplevel  (completed in 0.111s)
git rev-parse --abbrev-ref HEAD  (completed in 0.073s)
Server running on http://localhost:46940/?_&id=f08df9b632e62f3740a9a8176c2f3b5f&branchName=master&file=d%3A%5Cwamp%5Cwww%5Ccrystalsport%5Ctemplate%5Csite%5Cjs%5Csite.js&theme=&branchSelection=1&locale=en_US
git branch  (completed in 0.092s)
git shortlog -e -s -n HEAD  (completed in 0.103s)
git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 master --follow -- template/site/js/site.js  (completed in 0.24s)
git show-ref  (completed in 0.08s)
git branch --all --contains 5a3d6be47c079be5699b0f3d0330483641557f84  (completed in 0.081s)
git status --porcelain=v1 -b --untracked-files=no  (completed in 0.092s)
git config remote.origin.url  (completed in 0.073s)
git log --pretty=oneline -n1 4fdbae1e3c8c0c7cf5ab57ddef54dbe59885a4c4  (completed in 0.079s)
git show --pretty=oneline --decorate=full --numstat 4fdbae1e3c8c0c7cf5ab57ddef54dbe59885a4c4  (completed in 1.401s)
git show --numstat --pretty=oneline -M --first-parent 4fdbae1e3c8c0c7cf5ab57ddef54dbe59885a4c4  (completed in 0.949s)
git show --name-status --pretty=oneline -M --first-parent 4fdbae1e3c8c0c7cf5ab57ddef54dbe59885a4c4  (completed in 0.107s)
git status --porcelain=v1 -b --untracked-files=no  (completed in 0.12s)
git config remote.origin.url  (completed in 0.078s)
`

**Comment by astralmaster** [comment]
Just to avoid confusion, [these](https://imgur.com/a/cpKhLOi) are the files that do not open/provide contextual menu.

**Comment by ole1986** [comment]
@astralmaster The initial commit seem to have many files included. have you tried the filter for a file first and then clicked on it. Does this maybe resolve the issue?

**Comment by astralmaster** [comment]
@ole1986 Tried it, no reaction at all. Even when I single out a specific file using search filter.

**Comment by ole1986** [comment]
@astralmaster
Before you click on any file in the commit details, could you first open the Webview Developer Tools

![image](https://user-images.githubusercontent.com/4850116/73855561-867c1700-4834-11ea-8536-c6877e8bb470.png)

Then click on any file and check the Developer tools window.
In my case it showed two web requests.

![image](https://user-images.githubusercontent.com/4850116/73855785-da86fb80-4834-11ea-8381-24372938828c.png)

**Comment by astralmaster** [comment]
Before click on files:
![2020-02-06_130609](https://user-images.githubusercontent.com/36546159/73921975-c6e59e80-48e1-11ea-9274-279b1fb70d71.jpg)

After:
![2020-02-06_130630](https://user-images.githubusercontent.com/36546159/73921999-d49b2400-48e1-11ea-80d1-dc15a6a6cfbd.jpg)

**Comment by ole1986** [comment]
@astralmaster thank you for the screenshots.

Would you mind figuring out for us what the payload size is in your case.
The simplest way to do is to save the request as HAR file (incl. content) as shown below in the screenshot.

We only need the size of its file.

![image](https://user-images.githubusercontent.com/4850116/73927830-6864f400-48d2-11ea-9aa7-95e1f4647c53.png)

Thank you in advanced

**Comment by astralmaster** [comment]
If the resultant file is the whole payload then 431 KB. 
[network-log.zip](https://github.com/DonJayamanne/gitHistoryVSCode/files/4164558/network-log.zip)
I have attached the file.
