### ISSUE TITLE
Gravatar not working

### ISSUE THREAD

**Issue by nesslopz** [DonJayamanne/gitHistoryVSCode#436]
Hi! New update is awesome, great features, but since `>0.4.16` I can't see gravatar pictures, it's broken.
It works on `0.4.15`

Also, on `git history` command it asks for repository, inclusive if there's only 1 choice.

Thanks :+1:

**Comment by ole1986** [comment]
Thank you for reporting,

Can you please provide me with the remote you are expecting to have gravatar pictures

**Comment by nesslopz** [comment]
Hi! I'm sorry, I upload screenshots

This is how looks on a Private Bitbucket repository:
Log: ![Screen Shot 2020-02-12 at 2 24 37 PM](https://user-images.githubusercontent.com/5330860/74374192-8e433a80-4da3-11ea-8370-3c954a4ddb3f.png)

Commit detail: ![Screen Shot 2020-02-12 at 2 24 45 PM](https://user-images.githubusercontent.com/5330860/74374191-8daaa400-4da3-11ea-99b7-b89cd0e3e315.png)


And with a Public GitHub repository it doesn't show nothing as photo
Log: ![Screen Shot 2020-02-12 at 2 25 01 PM](https://user-images.githubusercontent.com/5330860/74374190-8daaa400-4da3-11ea-9eeb-009ba2b2ea6c.png)

Commit detail: ![Screen Shot 2020-02-12 at 2 25 09 PM](https://user-images.githubusercontent.com/5330860/74374187-8d120d80-4da3-11ea-9345-b0163cd69302.png)

**Comment by ole1986** [comment]
Can you please open the Developer Webview when Git History is opened
![image](https://user-images.githubusercontent.com/4850116/74376260-12b4ae00-4de2-11ea-986f-cb26286c6a9a.png)

and tell me what is shown in one of the log entries img source, like shown below?

![image](https://user-images.githubusercontent.com/4850116/74376366-41cb1f80-4de2-11ea-8e0b-8d703e3aa715.png)

**Comment by ole1986** [comment]
Also for testing purposes you can try to disable the Avatar Cache through setting `gitHistory.avatarCacheExpiration`

![image](https://user-images.githubusercontent.com/4850116/74376566-a8503d80-4de2-11ea-8fa4-f66cc172a00f.png)

**Comment by ole1986** [comment]
OMG I forgot to push the changes

**Comment by nesslopz** [comment]
Hi! I'm sorry I was not able to test as you told me, because I was out of office. But I confirm is working back in 0.5.2. Thank you so much :+1:

(offtopic: do you have any guide for extension development, apart of documentacion, I'm working in a extension too but is very simple and saw your code it's really impresionant)

**Comment by ole1986** [comment]
There is a [CONTRIBUTING.md](https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/) (which i just noticed is outdated due to the removed submodule)

All rights for the code go to @DonJayamanne 
I am just a little code helper ;-)
