### ISSUE TITLE
new feature request: open diff by click path of file when view single commit in commits list

### ISSUE THREAD

**Issue by knownothingsnow** [DonJayamanne/gitHistoryVSCode#44]
I used to be a Webstorm user. The Git extension in Webstorm has a feature that allows the user to view all the modified files for a single commit ___(your extension already has this feature)___. In addition, users can also view git diff for each modified file in side by side mode by click the path of files. I hope you can consider adding this feature to the extension.(My English is poor.Sorry for the grammer mistake)

**Comment by DonJayamanne** [comment]
Can do, will do over the weekend

**Comment by DonJayamanne** [comment]
Fixed in the latest release. https://github.com/DonJayamanne/gitHistoryVSCode/commit/b211e10bfe4b92eddbbf0717600cba57bfe3f292

**Comment by knownothingsnow** [comment]
Great to hear that. That would be very useful!
