### ISSUE TITLE
Very slow in the latest release

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#443]
Opening the Python Extension Repo is very slow now, almost unusable.

**Comment by ole1986** [comment]
I just tried from my remote linux and local windows machine and unfortunately I could not reproduce it. See attached animation (20 fps / uncut)

![vscode-python-githistory-perf](https://user-images.githubusercontent.com/4850116/75019792-d3e1c080-5491-11ea-9f27-4ab8aab3e4e3.gif)

Do you have any hints for me?

Possible related to #439

**Comment by DonJayamanne** [comment]
Been trying to figure out myself, but can't.
Can't replicate anymore. Damn it, it was just very slow.
No worries, will close and if i find something I'll file a new issue with details and a fix.
Thanks again.
