### ISSUE TITLE
Remove webserver

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#451]
I would like to get rid of express and the like.
Making this simpler & lightweight.

**Comment by ole1986** [comment]
I actually did not knew that getting rid of express would be an option.

I do have a websocket server implementation in my local test branches which still uses express (expressWs).

So how we are going to fetch the data from?

**Comment by DonJayamanne** [comment]
> So how we are going to fetch the data from?

VSC has an API to send requests back to the extension.  See here https://code.visualstudio.com/api/extension-guides/webview#passing-messages-from-an-extension-to-a-webview

**Comment by DonJayamanne** [comment]
> local test branches which still uses express (expressWs).

We can keep it for testing purposes. I find this useful for react, as I can then use chrome extensions to analyze what's going on in react world.
However for production I think we must get rid of it, it will be faster (slightly) - smaller bundle and monkeying around with ports and the like.

**Comment by ole1986** [comment]
Ah... postMessages!

So PR #440 may already become a more postMessage related change instead of using websocket and express

I would love to take over that part

**Comment by DonJayamanne** [comment]
> I would love to take over that part

Go for it. Please feel free to take any task. I'm merely adding a list of things that I think needs to be done. It doesn't have to be me.

I'd get rid of all of the express, etc stuff.. 
Again thanks for the help
