### ISSUE TITLE
Improvements to webpack

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#452]
* Smaller bundles
* Fast loading of extension

**Comment by ole1986** [comment]
I once tried to bundle all the server sources with webpack. But it was very tricky with the express package (and some other I cannot remember the name now) being included.

I think once we get rid of the express package (as mentioned in #451) and replace with webview.postMessege, bundling it should work very smooth.

**As a side note:**
By mistake it can happen very fast that the size of the current bundle.js (browser bundle) increases significantly by only adding another icon from react-icons package for instance.

**Comment by DonJayamanne** [comment]
> By mistake it can happen very fast

We can add a GitHub action to ensure bundle size doesnt increase by more than 20% of previous known (hardcoded) size.
I.e add a test and hardcoded a value 5mb, if new size is 30% more than 5mb, then test fails. This way nothing can go in noticed.

**Comment by DonJayamanne** [comment]
If interested you can have a look at the python extension for VSCode. I added webpage to that, and things are great (both extension and react bundles). We are shipping koa today in that extension, I prefer koa over express.
