### ISSUE TITLE
Styling for individual file history details

### ISSUE THREAD

**Issue by adrianth** [DonJayamanne/gitHistoryVSCode#48]
The individual file history details feature is very useful, thank you - I was looking forward for that for some time. The dark  blue color of the  links is not very appealing though. Can you please change it to the standard color scheme in VS Code? I think the "standard" blue is #3769A6. This is how it looks like:

![link](https://cloud.githubusercontent.com/assets/5209882/19159596/aaffed3c-8bb2-11e6-9dec-8d55165a2811.png)

Thanks

**Comment by dogoku** [comment]
I also agree that this needs to change, and it's more of a usability issue at this point as the contrast is very low for dark themes

**Comment by DonJayamanne** [comment]
@adrianth @obust @dogoku 
A new version has been released with this fix
