### ISSUE TITLE
cannot change repos in multi-root workspace

### ISSUE THREAD

**Issue by NewtMa** [DonJayamanne/gitHistoryVSCode#496]
support for multi-root workspace was working ... and I haven't been able to choose repos since the last update. I could only choose once which repo I want to look fro git logs. Then it just stuck with the repo I choose unless I uninstall the extensions and choose again.

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue. I can replicate this at my end. We will endeavour to get a fix out asap.

**Comment by DonJayamanne** [comment]
@ole1986 The fix seems fairly simple, the handler for the command is here
```typescript
    public async viewHistory(fileUri?: Uri, lineNumber?: number): Promise<void> {
        const gitServiceFactory = this.serviceContainer.get<IGitServiceFactory>(IGitServiceFactory);

        const gitService = await gitServiceFactory.createGitService(fileUri);

```

The `createGitService` is what displays the prompt to select a workspace.
All we need to do is pass a flag `true` that indicates the fact that we need to ALWAYs display the picker/prompt. Simple fix. However, not sure how it worked in the past. I'm happy with that simple fix and we can fix/cleanup slowly.

what do you think?

**Comment by NewtMa** [comment]
@DonJayamanne Thank you so much for your quick reply.

**Comment by ole1986** [comment]
@NewtMa usually it takes the o
Repository you have selected from the source control sidebar in vscode.

But we already a request to always prompt with the Repository picker. So it might be an option setup another command (allowing us to keybind it) which force display the prompt dialog

**Comment by NewtMa** [comment]
> @NewtMa usually it takes the
> Repository you have selected from the source control sidebar in vscode.
> 
> But we already had a request to always prompt with the Repository picker. So it might be an option setup another command (allowing us to keybind it) which force display the prompt dialog

@ole1986 Sorry for the delay. I didn't know the button behavior had changed. And I noticed there were two git history buttons. One in the source control panel, another around the file tabs. 

Maybe you could change the one around the tabs to always prompt the dialog and the one in source control sidebar to remain the same behavior as before, or you could just remove the one around the file tabs and update the extension page.

**Comment by prem48science** [comment]
Hi, is this fixed yet?

**Comment by ole1986** [comment]
Sorry, Not yet. You need to select the repo from source control sidebar in vscode

**Comment by prem48science** [comment]
Even if I select another project from the source control sidebar. it is not switching to another project. I have to shutdown VScode and reopen to select a new project again.

**Comment by ole1986** [comment]
@prem48science when you select from the sidebar it is necessary to rerun the `Git History (git log)` command to open another tab

**Comment by prem48science** [comment]
yeah. I use latest version. 
ah! got it. my source control selected two projects by default. By selecting only one project I can get git history of that particular project from the sidebar. 

anyhow a keyboard command is recommended. let me see if I can contribute to the same.  thanks @ole1986
