### ISSUE TITLE
fatal: ambiguous argument 'iot': both revision and filename

### ISSUE THREAD

**Issue by he0119** [DonJayamanne/gitHistoryVSCode#499]
When I opened git history, it was loading forever. 
Extension version: 0.6.2
Here is the log.

```log
git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 iot --  (completed in 0.234s)
git rev-list --full-history iot --count  (completed in 0.154s)
fatal: ambiguous argument 'iot': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

![image](https://user-images.githubusercontent.com/5219550/76313139-5c27e880-630f-11ea-82ab-578aca290ee8.png)

**Comment by ole1986** [comment]
Hm.. I think 

`git rev-list --full-history iot --count`

should actually be

`git rev-list --full-history --count iot`

**Comment by he0119** [comment]
> Hm.. I think
> 
> `git rev-list --full-history iot --count`
> 
> should actually be
> 
> `git rev-list --full-history --count iot`

I have a branch and a folder both named iot.

`git rev-list --full-history --count iot --` works for me.

```powershell
PS C:\Users\hmy01\Works\Working\smart-home> git rev-list --full-history --count iot --
47
PS C:\Users\hmy01\Works\Working\smart-home> git rev-list --full-history --count iot
fatal: ambiguous argument 'iot': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
