### ISSUE TITLE
Ability to edit current version

### ISSUE THREAD

**Issue by laggingreflex** [DonJayamanne/gitHistoryVSCode#50]
When comparing a previous version with current one, it would be great to be be able to actually edit the current version, just like VSCode natively offers the ability to edit when comparing against un/staged version. 

PS: Awesome Extension!

**Comment by laggingreflex** [comment]
BTW it weirdly allows editing the *previous* version (displayed on the right with the filename with the %TEMP% path).

**Comment by mikes-gh** [comment]
Can you confirm this is fixed in 0.1.2 please.
I just tried and I can edit the work space version in the diff window since the enclosed PR

**Comment by laggingreflex** [comment]
It is! Awesome work! 👍
