### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#502]
What's required to create a release?
* GitHub release
* Release notes (is this automated)
* Publishing to market place

@ole1986 Please could you let me know what you do here?

**Comment by ole1986** [comment]
Release notes are unfortunately not yet automated.

So my steps are usually:

- do changes from a separate branch
- make PR of it
- merge PR into master
- amend version and changelog.md
- copy content of changelog.md into a new release note on GitHub
- if all ok, release the version using "publish" from GitHub releaess to trigger the GitHub Action vsce-publish.yml

Rest is done by the GitHub action

- checking and building the files using webpack
- upload the vsix file as asset onto the release
- upload to market using vsce publish
