### ISSUE TITLE
Triggering a release

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/gitHistoryVSCode#503]
**What's the criteria to trigger an automated release?**
* Suggestion, tag created with a format `v*`
This when one needs to create a release, all we need to do is just add a tag and push.

**What will be automated**
* Release notes/Change log
* GitHub release
* Upload to marketplace

@ole1986 thoughts?

**Comment by ole1986** [comment]
automate release when pushing an annotation tag sound good to me.
Also, I agree to the three steps.

Only thing is what should be written into the release notes/ changelog..
The issues? all commits? grouped? non-grouped

Or issues only in release notes, but all commits into changelog for more transparency?

**Comment by DonJayamanne** [comment]
> but all commits into changelog for more transparency?

Yes. Everything.
If things don't work as expected, we can always change after first, sending or third release or later ..

**Comment by ole1986** [comment]
I already tried two of these mentioned in #280 

* https://github.com/github-tools/github-release-notes
* https://github.com/marketplace/actions/release-drafter

I preferred gren (github-release-notes) as it provides also the changelog to get updated
Do you want me to integrate?

**Comment by DonJayamanne** [comment]
Sorry, I missed this comment. I believe you have picked one. My response would have been anyone.

**Comment by ole1986** [comment]
This issue seem to be resolved using `gren` (github-release-notes) while running `git push --tags` for new versions to generate the release notes on github.com -> Releases
