### ISSUE TITLE
History doesn't display for specific project

### ISSUE THREAD

**Issue by ekoopmansAP** [DonJayamanne/gitHistoryVSCode#536]
Hi! Git History is great, I really appreciate the extension.

I haven't been able to get it working with my latest project. `View History` and `View File History` both appear blank:
<img width="1042" alt="git-history blank" src="https://user-images.githubusercontent.com/62129793/78517399-7070df80-7800-11ea-8382-1669d35ca4e6.png">

In the developer console, I get these error messages:
<img width="912" alt="git-history console" src="https://user-images.githubusercontent.com/62129793/78517419-8383af80-7800-11ea-9e85-6640c0614d45.png">

I believe this is related to the first error message `E2BIG`, because when testing in another (working) project I still get the other error message `t.payload is not iterable`.

This is on a Mac using Git History 0.6.3, VS Code 1.43.2, git 2.23.0. On this project, `git log` etc work fine, VS Code's built-in git utils work fine, and Git Lens works fine.

**Comment by ole1986** [comment]
@ekoopmansAP thank you for reporting.

I assume the list of commits has reached the max postmessage size.
Can you please try to reduce the `gitHistory.pageSize` setting (E.g to 10 items) and see if it works?

**Comment by ekoopmansAP** [comment]
Same result after reducing `gitHistory.pageSize` to 10 (previously, all settings were default). It certainly could be related to number of commits though, there are over 25k.

**Comment by reuvygroovy** [comment]
I have the same issue. Also tried 10 but no avail. I see this error - don't know if it's related:

workbench.desktop.main.js:258 [Extension Host] (node:25308) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

It also happens with a specific project only.

**Comment by ole1986** [comment]
Pretty sure it has something to do with number of commits.

But also thought reducing the page size would solve it but seem to not.

Need to investigate more on this issue

**Comment by damianfijorek** [comment]
Maybe #541 fixes this as exception is in the same method, `E2BIG` stands for _Arg list too long_ and the solution was to pass arguments in chunks. Windows checks just total length of command so you could get just `ENAMETOOLONG`, see https://github.com/sanack/node-jq/issues/51#issuecomment-515808932.

**Comment by ole1986** [comment]
@ekoopmansAP is this issue fixed in version 0.6.5?

**Comment by ekoopmansAP** [comment]
Yes, it's working perfectly now (including with default page size of 100)! Thanks @damianfijorek @ole1986, amazing work. So nice to be able to view the history within VS Code.
