### ISSUE TITLE
Switch between projects

### ISSUE THREAD

**Issue by prem48science** [DonJayamanne/gitHistoryVSCode#537]
Hi, Git history is a great tool to visualize the git log. 

I work on multiple projects in the same workspace related to a bigger project.  kind of small project groups within a big project. I need to switch between these projects if an update is notified. I couldn't find any command where I can just switch between project history. 

Any possible solution you know for this ?

**Comment by ole1986** [comment]
I assume I mean repositories.
Usually the `source control` in vscode provides you the option to select the correct repository

(sorry for language)

![image](https://user-images.githubusercontent.com/4850116/80016559-8efafa00-84d3-11ea-957e-62f4a2d8f740.png)

Whenever you select the repo and run "Git History (log view)" it should display the appropriate repository in a tab (and remembers the selection)

So, when you rerun the Git History it will bring back the selected entry.

I just created PR #540 which comes up with another setting allowing you to always prompt with the repository selection.

**Comment by prem48science** [comment]
Yes, the setting to prompt the user for repo helps! it will be a great enhancement. thanks for the contribution @ole1986
