### ISSUE TITLE
Don't see any history

### ISSUE THREAD

**Issue by reuvygroovy** [DonJayamanne/gitHistoryVSCode#539]
I can't see any history for files, despite the fact that I know they exist. How can I troubleshoot this? I enabled verbose logs but don't see anything there.

**Comment by damianfijorek** [comment]
I've the same issue, just `Loading...' forever.

**Comment by ole1986** [comment]
Do you have further details about OS and versions?

**Comment by reuvygroovy** [comment]
Using VSCode 1.43.2 on Windows 10. Latest version of this extension I believe since I just installed it,

**Comment by damianfijorek** [comment]
gitHistory 0.6.3, VSCode 1.44.2, Windows 10. This is not error but looks suspicious `[Embedded Page] Uncaught (in promise) #<Object>` in `vebviewElemetn.ts:261`:
```
this._register(addDisposableListener(this.element!, 'console-message', function (e: { level: number; message: string; line: number; sourceId: string; }) {
			console.log(`[Embedded Page] ${e.message}`);
		}));
```
I've checked another project, where it works fines and there is no such line in console.

**Comment by ole1986** [comment]
Do you have multiple repositories in the project or only a single one?
Any special characters in the filename/filepath?

**Comment by reuvygroovy** [comment]
I don't know. Don't think so. There are hundreds of files. Hard to remember ya know.

**Comment by damianfijorek** [comment]
I've got master and debugged the issue. Our build pipeline tags sources with build number and it seems we reached the limit of what command on Windows could take.

Command is `git rev_parse` and then over a thousand of tags in `args`. 

```
const gitShow = spawn(gitPathCommand, args, childProcOptions);

Error: spawn ENAMETOOLONG
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:553:9)
	at GitCommandExecutor.<anonymous> (gitHistoryVSCode\src\adapter\exec\gitCommandExec.ts:54:25)
	at Generator.next (<anonymous>)
	at fulfilled (gitHistoryVSCode\dist\src\extension.js:28242:58)
```

**Comment by damianfijorek** [comment]
@reuvygroovy You could download this repository run `npm install` inside, open in VSCode, hit F5 to debug the extension. Another VSCode will open where you could open your repository and catch the exception in the first VSCode.

**Comment by reuvygroovy** [comment]
which repository should I download? how? and when/where do I run npm install? can you provide me some intructions?

**Comment by damianfijorek** [comment]
> which repository should I download? how? and when/where do I run npm install? can you provide me some intructions?

- Run you favorite terminal. 😉
- `git clone https://github.com/DonJayamanne/gitHistoryVSCode.git`
- `cd gitHistoryVSCode`
- `npm install`
- `code`
- Hit F5 to debug the Git History extension.
- Set breakpoints on all exceptions.
- Reproduce you issue in the new VSCode window.
- Report exception you get. Inspect locales in debugger, maybe you will find out why it does not work with your repository. Good luck. 😊

**Comment by ole1986** [comment]
I think some path or filename seem to be too long?
`Error: spawn ENAMETOOLONG`

**Comment by reuvygroovy** [comment]
So it's weird. Even within the same Repo, seems like it's related to a specific file. 
I followed the above step. Pressed F5. Within the new vscode window that was opened I opened my code and tried to fetch git history. it had nothing, The previous debug also had no errors.

**Comment by ole1986** [comment]
Any chance you can figure out the file?
That would be really helpful to fix that issue

**Comment by damianfijorek** [comment]
> I think some path or filename seem to be too long?

It's not about length of particular file, tag or argument in general but the total length of all of them. See fix for similar issue https://github.com/microsoft/vscode/pull/66095

I will try to make script to generate a public repository, that would allow you to reproduce this issue, later this week. Then I could try to use the divide and conquer idea to fix it too.

@reuvygroovy Have you tried with all break points?
![image](https://user-images.githubusercontent.com/963492/80067395-06fe0a00-853e-11ea-847e-271fc9925878.png)

**Comment by damianfijorek** [comment]
The repository to reproduce my issue: https://github.com/damianfijorek/thousendTags

**Comment by reuvygroovy** [comment]
I think I figured it out!

If the file name has a space in it, it doesn’t work.

I took the same file, renamed it removing all spaces, and it worked.

Can you check on your end?
