### ISSUE TITLE
History detail color

### ISSUE THREAD

**Issue by huyqut** [DonJayamanne/gitHistoryVSCode#54]
Hi, I find it hard to look at the (blue) color of file in the history file:

![githistory](https://cloud.githubusercontent.com/assets/22194121/20101528/f72b7e9a-a5f4-11e6-8716-caad6a14e855.PNG)

Can we change the color so that it is readable?

**Comment by vvatikiotis** [comment]
Or, alternatively, albeit more work, make it configurable.

**Comment by DonJayamanne** [comment]
@huyqut @vvatikiotis @obust @I0ud @lovefurniture @Spown @ychaikin
A new version has been released with this fix
