### ISSUE TITLE
Files with spaces

### ISSUE THREAD

**Issue by reuvygroovy** [DonJayamanne/gitHistoryVSCode#542]
This is in reference to [539](https://github.com/DonJayamanne/gitHistoryVSCode/issues/539) which was closed.

If the file name has a space in it, it doesn’t work. I took the same file, renamed it removing all spaces, and it worked.

Can you check on your end?

**Comment by ole1986** [comment]
Thank you for your effort. I will haver a closer look into it soon.

Just for completion, can you provide OS, vscode version and git as well as git history version

**Comment by reuvygroovy** [comment]
Using version v0.6.4
Windows 10 with VSCode 1.44.2
