### ISSUE TITLE
 temporary branches cannot be seen

### ISSUE THREAD

**Issue by jhonnattan123** [DonJayamanne/gitHistoryVSCode#550]
In order to back up some changes, create a temporary branch, commit to it, and then leave it. the program is that from visual study code it is not possible to change to this branch, however it does exist. the only way to change is manually.

how i create a temporal branch:

> $ git checkout -b YGUser2

if u click in 
![image](https://user-images.githubusercontent.com/31730855/81895013-31f8de00-957f-11ea-9c2b-f317e358d2a3.png)

u cannot see the branch YGUser2
![image](https://user-images.githubusercontent.com/31730855/81894748-8f405f80-957e-11ea-9df2-76f6c84f1fe4.png)

the branch appears only when you do a git checkout --force YGUser2 from that moment it begins to appear. i use WSL Ubunu 18.04

**Comment by ole1986** [comment]
@jhonnattan123 I think that this is more related to vscode itself?

**Comment by ole1986** [comment]
In  "Git History" we currently do not update the state when a git branch is changed or added.
For this it is neccessary to press the "Refresh" button

![image](https://user-images.githubusercontent.com/4850116/82112625-d2512d00-974e-11ea-931d-e72bba1b1879.png)
