### ISSUE TITLE
Is it possible to revert file to a commit?

### ISSUE THREAD

**Issue by resting** [DonJayamanne/gitHistoryVSCode#553]
After choosing View File History > Choose commit > Choose file > Compare against working file, is there a way to revert working file to the one in being compared against from the current screen?

**Comment by ole1986** [comment]
@resting from the Git History view you can revert a commit by using the soft or hard reset buttons.

If you want to only revert a single file you can do the following:

* Choose the previous commit you want to revert the file from.
* Click soft reset to revert the files by keeping the modified files in stage
* Unstage the file you want to revert
* commit the stage (without the file you just unstaged).

**Be aware of the hard reset as it fully replaces the the files with the previous commit (without staging the modifications)**
