### ISSUE TITLE
"Unrecognized file stat status 'c" when clicking on a commit

### ISSUE THREAD

**Issue by ponchofiesta** [DonJayamanne/gitHistoryVSCode#557]
**Reproduce**
- I opened "View History (git log)" on a remote SSH hosts Git repo.
- I clicked on the first commit

**Result**
Output console on bottom opens with this output message:
```
git shortlog -e -s -n HEAD  (completed in 0.01s)
git remote show origin -n  (completed in 0.019s)
git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 master --  (completed in 0.024s)
git rev-list --full-history --count master --  (completed in 0.036s)
git show --pretty=oneline --decorate=full --numstat 7af34e120c9931fa3abb308941c044b0af2c5bb6  (completed in 0.009s)
git show --name-status --pretty=oneline -M --first-parent 7af34e120c9931fa3abb308941c044b0af2c5bb6  (completed in 0.006s)
Unrecognized file stat status 'c
```

Remote host has this software:
- CentOS Linux 7 (Core)
- git version 1.8.3.1

**Comment by ole1986** [comment]
It seem to interpret the `git status` file status as a lowercase "Copied"  -> c.
Usually it should be uppercase. Have you tried updating the git version to 2.X?

**Comment by ponchofiesta** [comment]
I just found out this version is from 2013  :flushed:
In this environment it's not easily done to update software like this. But I'll do my best to get this addressed. Might there be an easy fix or workaround?

**Comment by ole1986** [comment]
Have you tried to run the below command manually to see if its really a lowercase "c" ?

``
git show --name-status --pretty=oneline -M --first-parent 7af34e120c9931fa3abb308941c044b0af2c5bb6
‛‛‛

**Comment by ponchofiesta** [comment]
The command runs without errors:
```
$ git show --name-status --pretty=oneline -M --first-parent 7af34e120c9931fa3abb308941c044b0af2c5bb6
7af34e120c9931fa3abb308941c044b0af2c5bb6 add utilities
M       roles/bamboo-remote/tasks/main.yml
```

I also tried it with an actual call from VSCode. I ran every single command shown in the console before the error occured. And I got the error in VSCode but not on the shell.

**Comment by ole1986** [comment]
@ponchofiesta that is pretty strange since there is no 'c'

Is this the complete output of the command? I was expecting to have an copied file or something

**Comment by ponchofiesta** [comment]
Maybe because it was an older commit. The current error is this:
```
git show --name-status --pretty=oneline -M --first-parent 97a5549e545ac30f0db9af4413662f9fc240c5c8  (completed in 0.006s)
Unrecognized file stat status 'c
```

Terminal:
```
$ git show --name-status --pretty=oneline -M --first-parent 97a5549e545ac30f0db9af4413662f9fc240c5c8
97a5549e545ac30f0db9af4413662f9fc240c5c8 remove redundant host.yml, use inventory instead
D       hosts.yml
M       instance.tf
R100    inventory       inventory.yml
```

**Comment by ole1986** [comment]
Just to clarify with such commit you still have the issue?
Any chance to get this repository?

If not I can only recommend to debug the extension by yourself.
Add a breakpoint to file `src/adapter/parsers/fileStat/parser.ts` on line  line 136 to find some unusual content in the status parts

**Comment by trishnendu** [comment]
I'm facing the same issue

git show --name-status --pretty=oneline -M --first-parent 9c523375b4a1d2eeffd73291a029aa30a03a3f1a  (completed in 0.018s)
Unrecognized file stat status 'c

**Comment by ponchofiesta** [comment]
What's your environment? (Git version, Remote or not, Operating system)

**Comment by crazycliffy** [comment]
Saw this post.  I'm facing the same issue with **Unrecognized file stat status** as well.  I'm not able to update Git to the latest since I'm not the administrator.

Environment:  `Remote SSH, vscode 1.48.2, Centos 7, Git History 0.6.9, Git 1.8.3.1`

```
git show --pretty=oneline --decorate=full --numstat 26070fce9c3bd2d61b1f9a420489dbd1615c9c82  (completed in 0.022s)
git show --name-status --pretty=oneline -M --first-parent 26070fce9c3bd2d61b1f9a420489dbd1615c9c82  (completed in 0.013s)
Unrecognized file stat status 'c
```
When copying the commands to terminal, there are no error messages.

Anyone found a workaround for this yet?

**Comment by crazycliffy** [comment]
Compiled my own version of git-2.28.0, and installed to some other non-root folder like home (since I don't have root access), and now the problem goes away.  Suggestion git history extension have a required version warning message.

**Comment by ole1986** [comment]
.... So it's seem to be an automated build issue?

**Comment by zhanglintc** [comment]
I have the same issue. It seems caused by the git  version.
I update my git version from `1.8.3`(CentOS 7 default git version) to `2.30.1`, the problem has gone.

**Comment by ole1986** [comment]
Thanks for letting us know

**Comment by ponchofiesta** [comment]
Why was it closed? It is not compatible with Git 1.8.3. Which is the Git version on CentOS 7.

**Comment by ole1986** [comment]
Git 1.8.3 is no longer maintained so I assume the OS should provide you an option to update to a maintained version of git scm

**Comment by ponchofiesta** [comment]
CentOS 7 is supported till 2024. Thus Git 1.8.3.1 is too (like it is done in all Linux Distributions). 

OK, then this extension needs some newer unspecified Git version. I can live with that.

**Comment by SweetMojito** [comment]
I have encountered it too. I also have a problem with the git version. Just upgrade to 2.2.1 and it will be fine.
