### ISSUE TITLE
BUG: fs.appendFile causes overwrites when stdout of git show of commit > temp file

### ISSUE THREAD

**Issue by mikes-gh** [DonJayamanne/gitHistoryVSCode#56]
Comparing a previous version to a workspace version the code here runs to create a temporary file for vscode to diff.

https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/helpers/historyUtils.ts#L202

Stdout of for example

`git show "$CommitSHA/somelargefile.js"`

is asynchronously appended from stdout to a tmp file used for the vscode diff.

However for larger files `fs.appendFile` can be called before the previous `fs.appendFile` has finished causing the tmp file to be overwritten at random places

I solved it temporarily by using `fs.appendFileSync` although a queuing strategy might be yield better performance.

**Comment by DonJayamanne** [comment]
Ouch, will look into this today. Thanks for identifying the root cause.

**Comment by mikes-gh** [comment]
This looks like a good strategy to keep everything async

http://stackoverflow.com/a/14917682
