### ISSUE TITLE
in VSCode 1.47.0 (Jun 2020) githistory adds a breaking icon in multi-repo workspace

### ISSUE THREAD

**Issue by Nikodermus** [DonJayamanne/gitHistoryVSCode#561]
##  GitHistory enabled:
![image](https://user-images.githubusercontent.com/7080621/87095056-a8bff980-c205-11ea-8ba6-ae12f6c52990.png)

## Disabled plugin:

![image](https://user-images.githubusercontent.com/7080621/87095097-bffee700-c205-11ea-9244-2f22a105ed24.png)

## VSCode Info

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z (13 hrs ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by minusmario** [comment]
> ## GitHistory enabled:
> ![image](https://user-images.githubusercontent.com/7080621/87095056-a8bff980-c205-11ea-8ba6-ae12f6c52990.png)
> 
> ## Disabled plugin:
> ![image](https://user-images.githubusercontent.com/7080621/87095097-bffee700-c205-11ea-9244-2f22a105ed24.png)
> 
> ## VSCode Info
> Version: 1.47.0
> Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
> Date: 2020-07-09T08:01:54.115Z (13 hrs ago)
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 18.7.0

same issue here:
Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by massimo-cassandro** [comment]
same for me

>Versione: 1.47.0
>Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
>Data: 2020-07-09T08:01:54.115Z (1 giorno fa)
>Electron: 7.3.2
>Chrome: 78.0.3904.130
>Node.js: 12.8.1
>V8: 7.8.279.23-electron.0
>Sistema operativo: Darwin x64 19.5.0

**Comment by inker** [comment]
Same.

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z (2 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
