### ISSUE TITLE
command 'git.viewHistory' not found

### ISSUE THREAD

**Issue by SmallOyster** [DonJayamanne/gitHistoryVSCode#565]
When I click the icon on VSCode Git page, it show the tips "command 'git.viewHistory' not found".

And the icon is still there, but the picture is gone.

**Comment by SmallOyster** [comment]
So sorry for my chinglish. 😭

**Comment by ole1986** [comment]
Please provide us some more info about your environment and possible log entries (E.g. Webview Developer Tools)

**Comment by SmallOyster** [comment]
> Please provide us some more info about your environment and possible log entries (E.g. Webview Developer Tools)

This is the screenshot when I start the VSCode and click the icon, the console say this.

I use **Windows 10 Home, VSCode 1.47.2**.

But before I update the VSCode,I can always use the extension smoothly...... So mysterious!!!

![screenshot](https://static.xshgzs.com/image/vsc-gitHistory-bug.png)

**Comment by ole1986** [comment]
Thank you

dup with #556
