### ISSUE TITLE
Missing Avatars…?

### ISSUE THREAD

**Issue by rareyman** [DonJayamanne/gitHistoryVSCode#567]
After the last update, avatars have shown up as broken images… Is this just me or something with the extension?

Using macOS 10.15.6, VS Code .47.2 and Git History 0.6.8 (default settings)

![image](https://user-images.githubusercontent.com/846457/88109168-e8b8a200-cb5e-11ea-8fc4-5c089552329c.png)

**Comment by Tayson199** [comment]
[](url)
