### ISSUE TITLE
Should file history use the --all flag

### ISSUE THREAD

**Issue by mikes-gh** [DonJayamanne/gitHistoryVSCode#57]
When displaying a file history I was getting confused with a duplicate commit message.
This was due to a stash. 

https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/helpers/historyUtils.ts#L119

Should the history include stashes?  Or perhaps an indicator to say its a stash?

**Comment by DonJayamanne** [comment]
This has been removed and a new build will be released soon.
Yes you are right, this shouldn't be displayed.

**Comment by mikes-gh** [comment]
Great.  I also just wanted to say than you for a great extension.

**Comment by DonJayamanne** [comment]
Thanks
