### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by pankaj-nayak** [DonJayamanne/gitHistoryVSCode#578]
- Issue Type: `Bug`
- Extension Name: `githistory`
- Extension Version: `0.6.9`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 30,
		"activateCallTime": 1,
		"activateResolvedTime": 314,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.microsoft-authentication",
				"_lower": "vscode.microsoft-authentication"
			},
			"activationEvent": "onAuthenticationRequest:microsoft"
		}
	},
	"runtimeErrors": []
}
```

**Comment by ole1986** [comment]
@pankaj-nayak can you please explain what the bug is?

**Comment by ole1986** [comment]
Closing it due to less information
