### ISSUE TITLE
Branches colors

### ISSUE THREAD

**Issue by sommella** [DonJayamanne/gitHistoryVSCode#580]
Hi,
I notice that some branches are in green and some in red, can someone please explain what does it mean?
Thanks

**Comment by ole1986** [comment]
@sommella when talking about the lines being visualized on merges the different colors are defined here:
https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/browser/src/components/LogView/BranchGraph/svgGenerator.ts#L12

**Comment by ole1986** [comment]
Oh sorry,

Now I know what you are asking.

The red color of the branch is supposed to be the remote branch name. While the green branches are your local branches (only available on your computer)

The following link may help you to understand
https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches

**Comment by longrunningprocess** [comment]
Thank you for answering, I was just using this extension for the first time and thought it meant something was broken or wrong.  I wonder if it might be helpful to others to have a simply explanation in the docs about the fact that green just means local and red means remote?
