### ISSUE TITLE
Git History doesn't show anything

### ISSUE THREAD

**Issue by keplian** [DonJayamanne/gitHistoryVSCode#581]
Windows 10, WSL2, VSCode 1.49

When I try to  "Git: View History", "Git: View File History" or "Git: View Line History" (command pallet or clicking on icon) i got new tab, but there is no information (see screenshot). 

"git log" is working, but Git History doesn't

![изображение](https://user-images.githubusercontent.com/45819480/93026943-67d3cf00-f612-11ea-8df0-e7fddb0c5237.png)

**Comment by PF4Public** [comment]
It also seems to have issues with Marketplace:
![image](https://user-images.githubusercontent.com/10319700/93913825-49568d80-fd0e-11ea-9125-722669d5032f.png)

**Comment by ole1986** [comment]
Please provide more info through the Webview Developer Tools (E.g. log output)

**Comment by PF4Public** [comment]
Marketplace:
![image](https://user-images.githubusercontent.com/10319700/94173819-1f7fa100-fe9d-11ea-8dae-49179476ac06.png)

Extension itself:
![image](https://user-images.githubusercontent.com/10319700/94174011-5b1a6b00-fe9d-11ea-9b7d-2f6f0574de88.png)

**Comment by ole1986** [comment]
Something strange is going on here:

Usually the REquest URI should begin with somthing similar to: 
`Request URL: vscode-webview-resource://0b3ba171-xxxx-xxxx-xxxx-e3088b271fd8/file///[...]`

But in your case its contain something like:
`[...].vscode-webview-test.com`

Is there any plugin which may intercept the webview flow?

**Comment by ole1986** [comment]
Are you running vscode online (remotely)?

**Comment by keplian** [comment]
> 
> 
> Please provide more info through the Webview Developer Tools (E.g. log output)
> 
> **UPDATE**
> Possible proxy issue? (Especially for the Marketplace -> Details page)


VScode running in WSL remote connection

![изображение](https://user-images.githubusercontent.com/45819480/94187440-a2f6bd80-feb0-11ea-8876-8352848d91e9.png)

**Comment by ole1986** [comment]
When you open the marketplace does it work for other extensions?

**Comment by PF4Public** [comment]
Just FYI this issue was fixed on its own on my system.

**Comment by ole1986** [comment]
Thank you for letting us know
