### ISSUE TITLE
The button now shows the file history, not the branch history

### ISSUE THREAD

**Issue by wave-light** [DonJayamanne/gitHistoryVSCode#587]
The black button in the toolbar <img src="https://user-images.githubusercontent.com/40989533/95186752-3c33a700-07c2-11eb-95fb-b1d1db872888.png" alt="git icon" width="16" height="16"> now shows the history of the active file, not the active branch. Is there a setting that can configure this?

**Comment by ole1986** [comment]
the behavior has slightly changed.
Using the git icon from sidebar opens the repository while the icon in editor title opens the related file.

So you can still open the repo using the **side bar icon** or the command "Git: View History (git log)"

**Comment by wave-light** [comment]
@ole1986 Thanks for the reply, but I have no git icon in the sidebar

**Comment by ole1986** [comment]
In the sidebar when opening the "Source Control" there should be a git repo icon for every repository as shown in the below screenshot:

![image](https://user-images.githubusercontent.com/4850116/95309850-f17e6180-088b-11eb-8a42-4ed815d41823.png)

**Comment by wave-light** [comment]
Thanks - I do have that icon and I can confirm that it opens the repo history
