### ISSUE TITLE
Wrap long commit message

### ISSUE THREAD

**Issue by edorivai** [DonJayamanne/gitHistoryVSCode#601]
Thank you for creating this amazing tool :heart: 

Long lines in commit messages don't get wrapped it the commit detail pane, rather they result in the message box overflowing and forcing the user to scroll horizontally to read the message:

![image](https://user-images.githubusercontent.com/765358/97850359-3911d500-1cf4-11eb-9c70-119f664b4460.png)

I would personally prefer it to wrap to optimize for detailed commit message descriptions - for example, see some of the commit messages to the React core repo: https://twitter.com/acdlite/status/1251169389564407809

**Prior discussion**
The only related issue I could find here was this one: https://github.com/DonJayamanne/gitHistoryVSCode/issues/37. It was closed back in 2016, so not sure how relevant that is to the current version.

**Versions:**
Git History: `v0.6.12`
VSCode: `1.50.1`

**Comment by MathieuDerelle** [comment]
I'm having this problem in 0.6.15

really long commit messages make the top window horizontally scroll (that's really annoying)
![image](https://user-images.githubusercontent.com/16286023/110506171-258dd500-80ff-11eb-9335-a5fddb8c58d2.png)

NB : there'a a line return before the `>`
see the output on github : 
![image](https://user-images.githubusercontent.com/16286023/110506637-903f1080-80ff-11eb-959c-fba624bbde66.png)

the gif in https://github.com/DonJayamanne/gitHistoryVSCode/pull/600 shows that
1. the "bottom" window is not scrolling horizontally
2. the commit name in the top window is relatively short (is it a double line return that prevent the end of the commit message from showing ? a regression ?)

**Comment by MathieuDerelle** [comment]
single line returns in name commits indeed break the top window
but not double line returns (which are truncated in the top window)
