### ISSUE TITLE
Can't view project's history anymore

### ISSUE THREAD

**Issue by jmevel** [DonJayamanne/gitHistoryVSCode#602]
Hello,

I noticed something recently, maybe it's due to the extension update.
I can't view the git history of a whole project anymore. 

When I open a project's folder containing a `.git` folder I used to immediately see the Git History extension icon at the top right corner even without opening any file in VS Code.
That icon was showing the history of the whole project but now it's gone.

So I tried running the command `Git: View History` using the palette but this isn't working, it's doing nothing.
This command only works if I open a file first in VS Code but this is showing me this file's history only, not the whole project's one.

Also when I've opened a file, the extension icon is back at the top right corner but it's basically the same: showing me only the file's history.

I think there have been an issue in a recent update which is running the `Git: View File History` command instead of running the `Git: View History` one.

If not, could you please tell me how to view the whole project's history?

Thanks a lot

By the way: good job for your work, this is one of my favorite extension on VS Code

**Comment by ole1986** [comment]
@jmevel thank you for reporting

can you please provide us some more details about the environment and also the logs?

Most important are also the console log output of the Webview (when opening "Git: View History"). You can find the console log output by running the command "Developer: OpenWebview Developer Tools"

**Comment by ole1986** [comment]
Also there is an setting to configure the *top right button*. Check out the `gitHistory.editorTitleButtonOpenRepo` setting:

![image](https://user-images.githubusercontent.com/4850116/98446497-1a5d7500-211e-11eb-81df-87fffe359bd8.png)

**Comment by jmevel** [comment]
@ole1986 thanks a lot for your answers and the tips about the `gitHistory.editorTitleButtonOpenRepo` setting.
This Indeed did allow me to view the project's history when clicking on the top right corner icon when a file is opened.

However there's something I don't understand.
It seems there's 3 commands here:

> Git History: View History
> Git History: View History (git log)
> Git History: View File History

`Git History: View File History` shows current file's history, no problem with that.
`Git History: View History (git log)` shows project's history all the time
`Git History: View History` depending of the `gitHistory.editorTitleButtonOpenRepo` setting, either shows file's history or project's history.

Is it the intended behavior? 
I find it quite confusing especially considering the setting is only about `the editor title button`, which isn't mentioning the `View History` command at all.

I had no idea I had to either change this unrelated setting or to use the `View History (git log)` instead.
I think this needs a bit of renaming in order to clearly express the intended behavior of these commands.

Here is my VS Code version:

> Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

And Git History version: `v0.6.13`

**Comment by ole1986** [comment]
To be honest it was a very quick change to provide both options (File History and Branch History) from the editors title navigation.
I am going to improve it the way it already executes the correct command dependent on its configuration setting (gitHistory.editorTitleButtonOpenRepo)
