### ISSUE TITLE
Improve prompts for destructive operations to include better warning indicators

### ISSUE THREAD

**Issue by tjx666** [DonJayamanne/gitHistoryVSCode#605]
I has some file not added, and I use this extension to hard reset, then the sad story happen.

I have some suggestion。
First,  for dangerous operation, such as `reset`, the `ok`  button should be `red`.

![Snipaste_2020-11-09_17-38-26](https://user-images.githubusercontent.com/41773861/98524618-64775f80-22b2-11eb-89f2-6754bcda3d30.png)

And When I hard reset, this extension should confirm user twice, and tell user what would be affected exactly. `All affected files will be dropped` is two general.

**Comment by ole1986** [comment]
@tjx666 

Sorry to hear that you have lost the work. We will improve this asap and try to make it more secure and understandable

**Comment by DonJayamanne** [comment]
Fyi, we have displayed a prompt and we already display a warning text in red.
I'd check how VSCode handle warning prompts, does VSCode change the buttons to red?

**Comment by DonJayamanne** [comment]
Accidentally closed (using the phone), meant to hit the other button

**Comment by tjx666** [comment]
Although VSCode doesn't colorize the button to red, but VSCode gives the details of  risk.

![screenshot_2020-11-09_23-18-24](https://user-images.githubusercontent.com/41773861/98559881-1e39f480-22e2-11eb-8adc-c6a1f2e09211.png)

**Comment by DonJayamanne** [comment]
Thanks, I think just updating the warning message that we already display in red would suffice. Perhaps including the warning icon too would help.

Also, sorry you lost some of your work.
