### ISSUE TITLE
"Upload Changed File" not working

### ISSUE THREAD

**Issue by danieleiobbi** [DonJayamanne/gitHistoryVSCode#607]
Hi, with the latest updates "Upload Changed File" does not work. I have to disable the extension for it to work.

![git-history](https://user-images.githubusercontent.com/31411680/98667696-106e8880-234f-11eb-9235-7765f1f7a2e5.jpg)

**Comment by ole1986** [comment]
@danieleiobbi I am pretty sure the Git History extension does not provide such "Upload Changed File" feature.
So it seem to come from a different extension

**Comment by danieleiobbi** [comment]
OK thanks
