### ISSUE TITLE
[FEATURE] Visualize the history of a block of lines

### ISSUE THREAD

**Issue by bguetarni** [DonJayamanne/gitHistoryVSCode#618]
Hi, is it possible to add a feature to see the history of a whole block rather than just one line ?
I frequently want to see the history of a function; however in a file history some commits don't contain changes for this particular function, so I lose a lot of time looking for the commits concerned with this function.
The same thing happen for a block of lines rather than a whole function.

Thanks ! :)

**Comment by ole1986** [comment]
I am not sure if this doesn't become to messy and also may cause more load time.

What we have achieved is a side-by-side view. So that you can at least "quicker" click the commits without having the details view overlapped. Would this already be helpful?

See PR #612

**Comment by bguetarni** [comment]
It should be useful yes, I will go with that.
Thanks.
