### ISSUE TITLE
Commit Info Popup Covers Commit History

### ISSUE THREAD

**Issue by esiemiat** [DonJayamanne/gitHistoryVSCode#623]
When selecting a commit in the commit history view the information for that commit, along with the search box, covers other commits listed in the history making everything very difficult to read. See attached screen shot.

![IssueSample](https://user-images.githubusercontent.com/5307534/106545549-95dd8100-64d7-11eb-936d-ac6a283ac836.png)

This occurs on multiple systems.

**Comment by ole1986** [comment]
We do have a PR where this has been fixed and also supports a side-by-side view.

Check out #612

I hope I can arrange a merge soon

**Comment by esiemiat** [comment]
OK, thank you. Really like the extension though.

**Comment by esiemiat** [comment]
Does this mean a fix will be released soon?

**Comment by ole1986** [comment]
I hope so.
Unfortunately the publish token is expired.

@DonJayamanne any chance you can fix #627 ?
