### ISSUE TITLE
View History shows blank page

### ISSUE THREAD

**Issue by tranzystorek-io** [DonJayamanne/gitHistoryVSCode#626]
As in title, clicking the "Git: View History" button shows a blank page

![obraz](https://user-images.githubusercontent.com/5671049/107804488-39deec00-6d64-11eb-850f-0e892a39be98.png)

Environment:

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

My code is on a WSL2 machine (Arch Linux) via the Remote WSL extension.

**Comment by tranzystorek-io** [comment]
For now the issue has disappeared, but I think it's recurring, so I'll leave it open just in case

**Comment by ole1986** [comment]
We had an issue with paths containing ampersand (&).
Maybe this was also the reason of a blank page for you?

It just has been fixed with version 0.6.15. Check out PR #611

**Comment by tranzystorek-io** [comment]
Not really, I use only typical [a-z0-9-] paths.

**Comment by tranzystorek-io** [comment]
The bug hasn't reappeared recently, I think this issue can be closed
