### ISSUE TITLE
The new history grid is unreadable now with the horizontal scroll

### ISSUE THREAD

**Issue by shudson-versasuite** [DonJayamanne/gitHistoryVSCode#631]
This used to be my favorite Git History UI and I would constantly perplex colleagues by using it instead of Visual Studio or Azure.  

But now I cannot see from one end of a commit to the other.  

I liked it better when the [...] wrapped the list of remote branches, IDK about anyone else but for some shared component library repos this list can get quite large.  But now that you've changed it to display every freakin remote branch, the horizontal scroll is twice the size of the viewport itself.

Thanks,

LSH
![git-history-1](https://user-images.githubusercontent.com/57822914/110560217-38a6a200-810b-11eb-9f48-5e92bc84d33c.PNG)
![git-history-2](https://user-images.githubusercontent.com/57822914/110560220-3b08fc00-810b-11eb-8f6d-8cf9ba1cbbc0.PNG)

**Comment by joalri24** [comment]
Also getting this with very long commit messages

**Comment by cyrusdaboo** [comment]
Same here. Things get even worse when using the side-split view for commit details.

**Comment by ole1986** [comment]
I am sorry... trying to fix things asap
