### ISSUE TITLE
No Scroll Bar in Commit Details Window [0.6.15]

### ISSUE THREAD

**Issue by bramankp** [DonJayamanne/gitHistoryVSCode#633]
When I am viewing commits and select one to get more details, there's no scroll bar in the bottom (below screenshot) window that allows me to see and interact with all the rest of the files that are part of that commit. I can drag the divider higher but that would only let me go so far (and then I'd have to drag it back for the commit history).

![image](https://user-images.githubusercontent.com/19915618/110702857-0eafb700-81c1-11eb-9774-557f5ef261bf.png)

**Comment by Demonese** [comment]
I meet the same problem.
vscode version: 1.54.1
Where is scroll bar?
![image](https://user-images.githubusercontent.com/57629614/110748057-3020a980-827a-11eb-9c4f-32bd4b699595.png)

**Comment by russell640** [comment]
I am seeing a horizontal scrollbar, but I would prefer a setting for max commit title length where a commit title would be truncated or truncated with an ellipsis at the end.  Using this setting, a horizontal scrollbar would not be needed.
Git History 0.6.15
VS Code 1.54.1
