### ISSUE TITLE
Commit details are unscrollable

### ISSUE THREAD

**Issue by marcellinke** [DonJayamanne/gitHistoryVSCode#636]
Hi, the new commit details split window is unscrollable. If I select a changeset with many files changed in it I am unable to scroll through these files in the commit details window.

**Comment by marcellinke** [comment]
There is a workaround for it. When I am using the side-by-side commit details option in the settings of this extension, I can scroll through the files of the changeset, but I still don't have a scrollbar.

**Comment by ole1986** [comment]
Related to PR #634
