### ISSUE TITLE
any way to show only one branch of the file history?

### ISSUE THREAD

**Issue by Jerry7X** [DonJayamanne/gitHistoryVSCode#64]
file history in the same branch is more useful,  is it not supported now?

**Comment by Jerry7X** [comment]
2717b35f90a93bdfd8d77a6ed95f1aa5ecdc4db8 this commit seems do it !

**Comment by DonJayamanne** [comment]
A new version with the necessary changes had not been released

**Comment by DonJayamanne** [comment]
@Jerry7X 
A new version has been released with this fix
