### ISSUE TITLE
next/previous buttons throw a bare HTML code

### ISSUE THREAD

**Issue by Spown** [DonJayamanne/gitHistoryVSCode#67]
This is what I get when I press either of the nav buttons on bottom of the log

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-11/Code_2016-11-26_18-24-30.png)

**Comment by mikes-gh** [comment]
In my case it just sends me to another tab.
Out of interest has it ever worked for you.

**Comment by Spown** [comment]
no. the screenshot is the only behavior I've experienced.

**Comment by mikes-gh** [comment]
I confirm your behaviour if no windows open before.
If other windows are open it mat switch to them instead.

**Comment by mikes-gh** [comment]
Looking at the code this is expected.
The paging logic is incomplete.
I'll look into in the next few days.

**Comment by DonJayamanne** [comment]
Lol

**Comment by DonJayamanne** [comment]
@mikes-gh I've added you as a collaborator for this project. You seem to be quite active and know your way around most of this project.

**Comment by mikes-gh** [comment]
Thank you :smile: :

**Comment by mikes-gh** [comment]
OK I have found the issue.
Before I commit this can we have some opinions on the current default page size of 500.
This seems like a lot of scrolling and affects the default performance of git log command.
I was thinking 50 would be about right.
When I'm developing I am rarely interested in stuff that old.

We could always have a

git log all

to override the paging for a fully scollable list

**Comment by mikes-gh** [comment]
Oh and apologies to @DonJayamanne for saying it wasn't finished.  It was.
There was just a subtle bug in the log parser code not reading the last log entry.

**Comment by Spown** [comment]
well, I for one look in the log mostly when I need to know what happened for a quite a while ago, since the recent staff is still in m head. My team is rather small, but with larger dev teams and can be both the very recent or old. To name the average number of commits to check would actually be impossible, since sometimes you have 50 a day and sometimes you have 50 a month. The index of a commit and it's age rarely correlate. So with a paged view it is actually very difficult to say where the commit in question lies... especially if you don't see the number of pages.

Additionally I'm often looking into log not for one single commit, but for multiple and I would jump between them to see the development. Again with a paged view this turns into a clickfest. That's why I still have to grab SmartGit and use it's log...

I hope I'm not going too far by suggesting an on-demand populated list. This is similar to the _infinite scrolling_ but with the the total number of items known in advance (if this possible with VSCode ofc.): 
1. make the page height equal to [number of commits]x[height of a commit item] to ensure the vert. scrollbar reflecting the true scale of the log.
2. put empty [50 | whatever is left]x[height of a commit item] containers inside
3. show first 50 commits in the first container
4. only load the next 50 when the user actually scrolls the next container into the visible area

Thus if the page contains 5000 commits if the user clicks the scrollbar somewhere in the middle the bottom of the 49th and the top of the 50th container would get visible and only these would be loaded. the most "difficult part" would be to limit concurrent loads either by queuing  them or by chaining them.

**Comment by mikes-gh** [comment]
@Spown  This is a great idea and thanks for the detailed response.   There is a blocking issue with upstream (electron) in that if you click on a commit and then click back to the git log it reloads.  Also the documentcontentprovider that vscode uses may present some barriers.  I'll fix thisbug first then move this to a new issue as an enhancement request.

**Comment by mikes-gh** [comment]
Fixed in version 0.1.4
