### ISSUE TITLE
Error accessing git repo

### ISSUE THREAD

**Issue by flynnwt** [DonJayamanne/gitHistoryVSCode#7]
I am getting a 'Not a git repository' error when getFileHistory() is executed.  It seems to be happening because `git rev-parse --git-dir` in getGitRepositoryPath() returns a relative path if the file is at the same level as the .git directory.  

I added this before the resolve() in getGitRepositoryPath() and it works as expected:
```
if (path.dirname(log) === '.') {
   log = path.dirname(fileName) + '/' + log;
}
```
Without the change, it works fine on files in subdirectories (when the git command returns an absolute path).  I'm running on Windows.

**Comment by DonJayamanne** [comment]
Thanks for the fix, i've included it into the latest build. 
Please could you confirm it works so that i could close this issue

**Comment by flynnwt** [comment]
Looks good!
