### ISSUE TITLE
Remove paging and make git log an on demand loading scrollable list

### ISSUE THREAD

**Issue by mikes-gh** [DonJayamanne/gitHistoryVSCode#71]
@Spown wrote

well, I for one look in the log mostly when I need to know what happened for a quite a while ago, since the recent staff is still in my head. My team is rather small, but with larger dev teams it can be both the very recent or old. To name the average number of commits to check would actually be impossible, since sometimes you have 50 a day and sometimes you have 50 a month. The index of a commit and it's age rarely correlate. So with a paged view it is actually very difficult to say where the commit in question lies... especially if you don't see the number of pages.

Additionally I'm often looking into log not for one single commit, but for multiple and I would jump between them to see the development. Again with a paged view this turns into a clickfest. That's why I still have to grab SmartGit and use it's log...

I hope I'm not going too far by suggesting an on-demand populated list. This is similar to the _infinite scrolling_ but with the the total number of items known in advance (if this possible with VSCode ofc.): 
1. make the page height equal to [number of commits]x[height of a commit item] to ensure the vert. scrollbar reflecting the true scale of the log.
2. put empty [50 | whatever is left]x[height of a commit item] containers inside
3. show first 50 commits in the first container
4. only load the next 50 when the user actually scrolls the next container into the visible area

Thus if the page contains 5000 commits if the user clicks the scrollbar somewhere in the middle the bottom of the 49th and the top of the 50th container would get visible and only these would be loaded. the most "difficult part" would be to limit concurrent loads either by queuing  them or by chaining them.

**Comment by mikes-gh** [comment]
We can probably do this with waypoints

http://imakewebthings.com/waypoints/api/viewport-height/

**Comment by DonJayamanne** [comment]
@mikes-gh sorry, but I'm going to be busy over the next few weeks (december and first week of Jan). But this makes more sense and is a better UX (paging is so old school :)

**Comment by DonJayamanne** [comment]
Closing for now, until reported again

**Comment by DonJayamanne** [comment]
Dup of #468
