### ISSUE TITLE
ubuntu 14.04 Performance issue

### ISSUE THREAD

**Issue by zhaohaixin** [DonJayamanne/gitHistoryVSCode#73]

**Comment by mikes-gh** [comment]
Try posting with more info.
What is your issue?
How can it be reproduced?

**Comment by zhaohaixin** [comment]
I opened a AOSP project, the following 30 git log, with qgit can quickly get git log, but the use of githistory have to load three minutes to get the information, I am sorry so late reply.

**Comment by mikes-gh** [comment]
Sorry I  still don't understand your issue.

**Comment by mikes-gh** [comment]
Do you have a link to your repo?
What is the output of `git rev-list --count HEAD`

**Comment by mikes-gh** [comment]
I can't really progress this without more info feel free to reopen if you have more info.
