### ISSUE TITLE
[BUG] 1.76.0-insider Branch and tag marks are no longer displayed in the GitHistory extension

### ISSUE THREAD

**Issue by maetada** [DonJayamanne/gitHistoryVSCode#730]
Type: <b>Bug</b>

It's about vscode issues.

"This is an issue related to the Git History extension rather than VS Code itself. I have reached out to @DonJayamanne who owns the extension and is aware of the problem. He will be working on updating the extension to react to the git extension API changes."

For this reason, I will write the contents here.
<br>
<br>

In the extension GitHistory
From the source control tab click on the history icon
Shows a list of history, but
Branch information and tag information, which were displayed on the right side of the list until now, are no longer displayed.

VS Code version: Code - Insiders 1.76.0-insider (c4a609f94329b17d91cd13a4fd113d1abfe5ec1f, 2023-02-03T05:24:12.020Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 7, 12|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id efcb8ae3-c686-414f-b934-9c7bb9bc8d2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
cocoapods-snippets|Age|1.0.0
vscode-sqlite|ale|0.14.1
dart-code|Dar|3.58.0
flutter|Dar|3.58.0
vscode-markdownlint|Dav|0.49.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|13.2.0
gc-excelviewer|Gra|4.2.56
vscode-git-tags|how|1.4.4
rest-client|hum|0.25.1
vscode-insertdatestring|jsy|2.3.1
Kotlin|mat|1.7.1
vscode-language-pack-ja|MS-|1.75.2023020109
flake8|ms-|2022.7.13121011
isort|ms-|2023.9.10341117
python|ms-|2023.3.10341119
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.2.1000360234
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vsliveshare|ms-|1.0.5828
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|56.16.0
salesforcedx-vscode-apex|sal|56.16.0
salesforcedx-vscode-apex-debugger|sal|56.16.0
salesforcedx-vscode-apex-replay-debugger|sal|56.16.0
salesforcedx-vscode-core|sal|56.16.0
salesforcedx-vscode-lightning|sal|56.16.0
salesforcedx-vscode-lwc|sal|56.16.0
salesforcedx-vscode-soql|sal|56.16.0
salesforcedx-vscode-visualforce|sal|56.16.0
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.48.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-maven|vsc|0.40.4
markdown-all-in-one|yzh|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
hidelangstatbar:30657380

```

</details>

**Comment by mdufourneaud** [comment]
I also encounter the issue.
I have tried re-installing the extension, but the marks are still missing.

I am ready to help if needed...

VS Code version: `1.76.0-insider (af4a70d991053dcbf64d9a86c76a02dced81d9c4)`
OS version: `Windows_NT x64 10.0.22623`

**Comment by leodinas-hao** [comment]
Same issue here as well. Does anyone have some workaround? Thanks

**Comment by sgabb** [comment]
Some issue on version 1.7.6

These are the details of the installation:
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:25:16.105Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.14.0-1057-oem snap
Sandboxed: No

This is the log in terminal after opening a history of a repository:
`git rev-list --full-history --count master --  (completed in 0.025s)
git shortlog -e -s -n HEAD  (completed in 0.153s)
git log --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=100 master --  (completed in 0.184s)`

This is the estension version:

Name: Git History
Id: donjayamanne.githistory
Description: View git log, file history, compare branches or commits
Version: 0.6.19
Publisher: Don Jayamanne
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory

**Comment by HelloDBA** [comment]
I also encounter the issue.

**Comment by maetada** [comment]
Now the tag and branch name are displayed! thank you

**Comment by AdiIntel** [comment]
Thanks for the quick fix!

**Comment by HelloDBA** [comment]
Thanks for the quick fix!

**Comment by rlk833** [comment]
@maetada Hm, there now seems a frequent, but I am not sure if consistent, bug related to this fix.

If I have a branch, such as master, which is one or more commits ahead of the origin/master, and push the master to origin/master, the origin/master tag will not move up to master commit just pushed. Pull will not refresh it either.

Refreshing, closing the view and opening it again, will not bring it up to date.

I have to close vscode and open it again before the origin/master and master are on the same commit.

**Comment by Wtower** [comment]
The same also happens when pruning or removing a branch. Need to restart vscode.

**Comment by rlk833** [comment]
A clue in the case of origin/master not moving up in view after a push.

IF the history view is NOT OPEN when you do the push, and then open it, it moves up.

Sounds like some type on internal update notification is lost if the push occurs while open, AND this is flag is not refreshed for the view until the next time a push occurs while view is closed.
