### ISSUE TITLE
Cannot read properties of undefined (reading 'exports')

### ISSUE THREAD

**Issue by tiger8888** [DonJayamanne/gitHistoryVSCode#754]
Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No

error:stack

workbench.desktop.main.js:1962 TypeError: Cannot read properties of undefined (reading 'exports')
	at h.<anonymous> (c:\Users\Tiger\.vscode\extensions\donjayamanne.githistory-0.6.20\dist\src\extension.js:9500:27)
	at Generator.next (<anonymous>)
	at s (c:\Users\Tiger\.vscode\extensions\donjayamanne.githistory-0.6.20\dist\src\extension.js:9459:21)
$onExtensionRuntimeError @ workbench.desktop.main.js:1962
N @ workbench.desktop.main.js:1532
M @ workbench.desktop.main.js:1532
H @ workbench.desktop.main.js:1532
G @ workbench.desktop.main.js:1532
(anonymous) @ workbench.desktop.main.js:1532
invoke @ workbench.desktop.main.js:93
deliver @ workbench.desktop.main.js:93
fire @ workbench.desktop.main.js:93
fire @ workbench.desktop.main.js:564
q.onmessage @ workbench.desktop.main.js:1630

the error position is here:
![微信截图_20231201150529](https://github.com/DonJayamanne/gitHistoryVSCode/assets/1930815/ebaad820-bac0-469c-a4a8-55075a6536fd)

**Comment by tiger8888** [comment]
solved as the pic
![无标题](https://github.com/DonJayamanne/gitHistoryVSCode/assets/1930815/d20a013d-b010-41b4-8209-794675788ed2)

**Comment by webull-webull** [comment]
Where is this configuration and how do I access it
