### ISSUE TITLE
Increase performance of git log on windows

### ISSUE THREAD

**Issue by mikes-gh** [DonJayamanne/gitHistoryVSCode#79]
Currently we do this

`git log --format="%n95E9659B-27DC-43C4-A717-D75969757EA5%nrefs=%ncommit=%H%ncommitAbbrev=%h%ntree=%T%ntreeAbbrev=%t%nparents=%P%nparentsAbbrev=%p%nauthor=%an <%ae> %at%ncommitter=%cn <%ce> %ct%nsubject=%nbody=%b%n%nnotes=%N%n95E9659B-27DC-43C4-A717-D75969757EA1%n" --date-order --decorate=full --skip=0 --max-count=500 --numstat --`

and use nodejs spawn and stdout.on('data' to read the result.

I ran some basic benchmarks and this takes 6 seconds on my install of windows 7 for around 100 commits at the command line.
Obviously it takes a bit longer to parse these entries but in the main it is the stdout that is slow.

git on windows seems to be the worst performer.
git on OSX has good performance.
git on Fedora 25 good performance.

If you examine the result of the above command you will see we are preloading a lot of stuff we will never likely use.

We should load only what we need to display the git graph and then think about loading the other bits on demand async whatever to get a better UX.

**Comment by mikes-gh** [comment]
It seems that running this command in git bash is much faster that under cmd on windows.

Anyone with knowledge of how the spawn internals work on windows?
I'm guessing spawning git would run without a shell?
I think exec is used for shell commands.

**Comment by mikes-gh** [comment]
We could look at the the performance of http://www.nodegit.org/ source https://github.com/nodegit/nodegit
It uses libgit2 and lloks pretty active.

**Comment by DonJayamanne** [comment]
@mikes-gh , I did check that out when starting this project, but that's quite a huge dependency.
Also its a native dependency, meaning we will need to release and update every time VS Code updates their node versions (result of updates to Atom). However its work a look once again.
I know theres a project that allows compile native modules so they work with multiple node versions (i.e. support for backwards compatibility), though not forward.

**Comment by DonJayamanne** [comment]
Another approach would be to try and see if we can somehow make use of what Visual Studio Code is using.

**Comment by DonJayamanne** [comment]
[Here's the source](https://github.com/Microsoft/vscode/blob/4af3d1797da4c3fe0e92c69ad39d2af990d1c592/src/vs/workbench/parts/git/node/git.lib.ts), 
It looks like they too are [spawning](https://github.com/Microsoft/vscode/blob/4af3d1797da4c3fe0e92c69ad39d2af990d1c592/src/vs/workbench/parts/git/node/git.lib.ts#L243) the git executable.

**Comment by mikes-gh** [comment]
Yes I saw that too probably stick to your current way.
Native dependencies sounds like it might raise a few issues
Since reading stdout from a spawn seems slower in windows I think the best we can do is only get what we need.  For example we could cut the stream (and the size of the html) down dramatically if we only get what we need to display the git log page.
If I limit the page size to 10 for example that makes a huge difference.
I think were back to an on demand loading list spawning git on demand.

**Comment by DonJayamanne** [comment]
Agreed, time to shave off a few milli seconds here and there to speed this up, thought I'd default the setting to something like 20, some monitors are quite big, like the monster I have at work...
Might want to consider calculating the height and determining the number of items to be displayed (if possible).

I've always wanted to rewrite the front end component to use websockets (socket-io), this way it would be a lot more efficient (something I've successfully done in another extension).

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue. Closing for now due to inactivity.
