### ISSUE TITLE
git log - better zoom support

### ISSUE THREAD

**Issue by tballast** [DonJayamanne/gitHistoryVSCode#82]
The commit hash gets cut off whenever I try to view the git history. This has been the case in both Ubuntu 14.04 and Ubuntu 16.04. 

It does this regardless of window size, though when I shrink the window I can see a little bit more of the blue button. 

![git log](https://cloud.githubusercontent.com/assets/5382820/21229994/7cfd07fe-c2b1-11e6-9533-fe5133e930d9.png)

**Comment by mikes-gh** [comment]
Yes Ive noticed the html isnt very responsive.
Just out of intesrest what happens if you use the menu to View -> Zoom In

**Comment by tballast** [comment]
Well, that seems to have fixed it! Now even when I close and re-open the editor it's displaying every correctly. It doesn't seem to preserve the zoom I set if I use Ctrl + Scrolling, but that's a separate issue.

**Comment by mikes-gh** [comment]
Thanks for confirming
We can leave this open to better cope with different zoom levels.

**Comment by tballast** [comment]
Perfect. Thanks for the help!

**Comment by jdforsythe** [comment]
Zoom levels definitely breaks this. At a single zoom in, I can't even see the bottom pane with the commit details.

**Comment by JSteitz** [comment]
Hello I don't have the problems with the Details Pane or the Hash Button.
But the commit dots (?) are not aligned with the corresponding commit message.
See Screenshot:

![Screenshot](https://user-images.githubusercontent.com/677821/29924782-67964ee2-8e5e-11e7-95a7-bb7cd49afb96.jpg)

**Comment by ole1986** [comment]
Is this still an issue?
