### ISSUE TITLE
Git outputChannel clashes with vscode's Git output.

### ISSUE THREAD

**Issue by mikes-gh** [DonJayamanne/gitHistoryVSCode#83]
https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/extension.ts#L11

We are taking over vscode's existing 'Git' output channel.
This causes some issues with overwriting the built in output and giving us 2 output windows named Git.
Should we rename it to Git History or Git Log?

**Comment by DonJayamanne** [comment]
Yes that makes sense.

**Comment by mikes-gh** [comment]
Leaving open to track fix 😄
