### ISSUE TITLE
Code style for if else try catch

### ISSUE THREAD

**Issue by mikes-gh** [DonJayamanne/gitHistoryVSCode#84]
I see both examples in the code which should I use?
There is a tslint rule for no 1. (presumably because its defacto)  so that's easier to enforce but coming from c# I tend to the later.

1. (we can enforce this).
```
if (some condition) {
    dosomething;
} else {
    dosomethingelse;
}

try {
    dosomething;
} catch {
    some error;
}
```

or

2. (next-line rule doesn't exist yet in tslint)

```
if (some condition) {
    dosomething;
} 
else {
    dosomethingelse;
}

try {
    dosomething;
} 
catch {
    some error;
}
```

**Comment by mikes-gh** [comment]
It does look like no 1. wins (frequency wise)

**Comment by DonJayamanne** [comment]
I'm not too fussed about coding styles. So please feel feel to use either one. 
Personally I prefer the latter too.
