### ISSUE TITLE
Commit Pick list format RFC

### ISSUE THREAD

**Issue by mikes-gh** [DonJayamanne/gitHistoryVSCode#86]
Maybe missing short sha to right of Commit message but what do you think in principle.

![commit pick list](https://cloud.githubusercontent.com/assets/16208742/21354271/553afb7c-c6c1-11e6-91b0-fb527084d31d.png)

**Comment by DonJayamanne** [comment]
Never found the need for it.
However now that you mentioned it, it makes sense to have something so critical. 
I agree, it makes sense to add it in there.

**Comment by mikes-gh** [comment]
Closed with #98
