### ISSUE TITLE
Bug: git history is unable to open files if current project is opened to a sub directory in the repository

### ISSUE THREAD

**Issue by rafikhan** [DonJayamanne/gitHistoryVSCode#91]
**Repro Steps:**
1. Open VS code in any sub directory of a cloned git repository
1. Navigate to the git history
1. Click on any commit
1. Click on any file in the commit

**Expected:**
git history extension should know that vscode is opened to a sub directory of the repository and resolve paths properly.

**Actual:**
Error in VS Code:
> There was an error in retrieving the file history. (fatal: ambiguous argument '`path to the file in my repo`': unknown revision or path not in the working tree.

**Comment by mikes-gh** [comment]
Fixed in next version.
Hopefully will be published early  this week.
See #81

**Comment by mikes-gh** [comment]
Can you try 0.1.5 please and report back.

**Comment by rafikhan** [comment]
Hi, I checked this morning and is working correctly.  Thank you for the
quick update.  I'm really excited to start using this extension in my
workflow.

I have some feature requests.  What's the best way to do that?  File an
issue?

-Rafi

**Comment by mikes-gh** [comment]
> I have some feature requests.  What's the best way to do that?  File an
issue?

Yes Issues is the right place.
