### ISSUE TITLE
No handler found for the command: 'git.viewHistory'. An extension might be missing an activation event.

### ISSUE THREAD

**Issue by alexsoares** [DonJayamanne/gitHistoryVSCode#92]
Hi,
I install this extension, but when i will use then, i got this error:
No handler found for the command: 'git.viewHistory'. **An extension might be missing an activation event.** I use the vscode for Linux OS version 1.0.0
Somebody know whats the problem?

**Comment by mikes-gh** [comment]
Did you install it through vscode or git clone

**Comment by alexsoares** [comment]
Through vscode...
I updated my vscode to version 1.8.1 and the extension it's worked very well.
So for me the problem was a versioin of my VSCode.

**Comment by mikes-gh** [comment]
OK thanks for confirming
