### ISSUE TITLE
Extension not generating content

### ISSUE THREAD

**Issue by castanjt** [DonJayamanne/gitHistoryVSCode#95]
Hello, I'm trying to figure out if I've discovered a bug or if there's an issue with my setup. I've installed the extension in VS Code. When I run, Git: View History (git log), all I see are Previous and Next buttons with no graph or output. When I run, Git: View File History on a file that has existing commits, I get a notification: There are no history items for this item 'front-page.php.'

Initially, I thought that the issue was related to not having Git installed using CMD as a shell. I've been using Bash on Windows. I've added Git to my Path and I can now run git commands in CMD both inside and outside of VS Code. Nevertheless, I'm unable to get the extension to work. It's almost as though it's not seeing the repo. 

Based on the docs, this looks like an exciting extension and I'm hoping that I can get it to work. Any recommendations are appreciated.

**Comment by mikes-gh** [comment]
Can you open vscode at your repo.
then immediately run git log from the integrated terminal. `ctrl + shift + '`
I presume you get output?

Also can I have  the output from

`git --version`
OS version
VSCode version

**Comment by castanjt** [comment]
Hi @mikes-gh, 

Yes, I can open VSCode from the .git directory using context menu. I also get the appropriate output from my log when running CMD or Bash as integrated terminals.

Here are the versions that you requested:
Git: Version 2.8.1.windows.1
OS: Windows 7 SP1
VS Code: Version 1.8.1

Please let me know if I can be of further assistance. Thanks!

**Comment by mikes-gh** [comment]
That's very similar setup to my main machine exception my git version is

git version 2.11.0.windows.1

However this shouldn't make any difference.
Is you repo public?

**Comment by castanjt** [comment]
No, it's private. 

I just checked the extension on a different computer. It works fine on the other computer with two different repos. One of the repos that works was the same one that encountered the bug on the Windows 7 comp.

Here are the versions of software on the computer, where it seems to work fine.

Git: Version 2.6.3.windows.1
OS: Windows 10
VS Code: Version 1.8.1

**Comment by DonJayamanne** [comment]
Are any errors logged in your console window. Go into Developer tools menu and check out the console window.

**Comment by mikes-gh** [comment]
@castanjt  Any new on this?  It does seem environment related but I would like to clear it up.  Maybe we need some additional checks

**Comment by castanjt** [comment]
Hi @DonJayamanne , 

The Developer Tools in Visual Studio Code are indeed showing an error. The error is the same whether CMD or Bash is enabled for the console. Ultimately, this is happening when I run Git: View History (git log) from the Command Palette.

Here's the error: 
[Embedded Page] Uncaught TypeError: Cannot read property 'scrollTop' of null --- Link to webview.ts:93

Here's the code in webview where the error is being referenced. 

Line 93 is the one that starts with 				
`console.log(`[Embedded Page] ${e.message}`);
`
```
this._disposables = [
			addDisposableListener(this._webview, 'console-message', function (e: { level: number; message: string; line: number; sourceId: string; }) {
				console.log(`[Embedded Page] ${e.message}`);
			}),
			addDisposableListener(this._webview, 'crashed', function () {
				console.error('embedded page crashed');
			}),
			addDisposableListener(this._webview, 'ipc-message', (event) => {
				if (event.channel === 'did-click-link') {
					let [uri] = event.args;
					this._onDidClickLink.fire(URI.parse(uri));
					return;
				}

				if (event.channel === 'did-set-content') {
					this._webview.style.opacity = '';
					let [stats] = event.args;
					this._onDidLoadContent.fire({ stats });
					return;
				}
			})
		];


```

Let me know if I can be of further assistance. Thanks.

**Comment by DonJayamanne** [comment]
Thanks, now to find where scrolltop is being used in my code.

**Comment by v-andrew** [comment]
@castanjt @mikes-gh 
I had exactly the same problem, with Git 2.10.2
Upgrade to 2.11.1 resolved the issue.

**Comment by mikes-gh** [comment]
Thanks for reporting this.
Sounds like we should just advise 2.11.1

BTW was anyone affected using symbolic links or non ascii characters in their repo?

**Comment by mikes-gh** [comment]
@castanjt 
Is it possible for you to install 2.11.1 to test this theroy?

**Comment by castanjt** [comment]
@mikes-gh, I'm home sick for the next few days. I won't be able to test until I have access to my work laptop again. Shouldn't be a problem though. I should have an update next week.

**Comment by huyinjie** [comment]
I have a similar error and I sloved it bu upgrade to 2.11.1
Thanks

**Comment by castanjt** [comment]
@mikes-gh - Wanted to give you a quick update. I tried upgrading Git to 2.11.1. Still same issue. Also upgraded VS Code to Version 1.9. 

I'm shutting down my comp and haven't restarted yet. I'll try again tomorrow and see if a restart helps. As of now though, issue still persists. Thanks.

**Comment by castanjt** [comment]
@mikes-gh - The Git version theory has been debunked. The issue that I'm having doesn't appear to be the version of Git. Presently, here are the versions that are installed on the machine that's still having the issue:

Visual Studio: 1.9.1
OS: Windows 7 SP 1
Git: 2.11.1.windows.1

Interestingly though, there are no developer console errors.

Thanks,
Jeremy

**Comment by castanjt** [comment]
I've attached a screenshot of the UI for reference. 

![vscodebug](https://cloud.githubusercontent.com/assets/15129928/23271848/13275aee-f9c7-11e6-9ed2-6df4ea92b3b0.jpg)

**Comment by castanjt** [comment]
@mikes-gh - I have noticed something else though. In the VS console (not the developer tools console), under the Output tab, I'm seeing the following output.

git fetch
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

The output seems to be automated. I'm not really doing any command line inputs into Git to generate the output in the VS console. Do you have any insight into the error?

For this particular repo, I have two pairs of remotes set - one in Bitbucket for archiving and one for deployment to a server.

**Comment by mikes-gh** [comment]
That is vscode output which shows something is wrong with your repo.  It does a fetch periodically.

**Comment by castanjt** [comment]
Do you want to try to test that theory with me? 

If you're on Windows 7, let's pick the same project on Github and clone via integrated terminal using CMD, make a commit, and see if the Git History VS Code extension still works.

So far, all of the repos that I've tested it with haven't worked. However, I'm a solo developer, so the origin of my repos is local rather than cloning. Upstream for me is really meant for disaster recovery or deployment rather than collaborating. I want to see if the issue is tied to how I'm creating and configuring my repos vs. another identified bug since the upgrade to Git Ver 2.11.1 didn't result in any change.

As mentioned previously, I'm able to use the extension using the same repos on Windows 10. I'm starting to wonder if this is an OS issue rather than a Git issue. Also, what OS are you running?

**Comment by mikes-gh** [comment]
Since you get errors in the `Git` output windows about git fetch (this is vscode not us) this would indicate you have a fundamental problem with your environment that would need to be fixed before Git History will work.

You could test this theory by uninstalling Git History and monitoring Git output from vscode.

**Comment by mikes-gh** [comment]
Is there anything else I can do here?

**Comment by DonJayamanne** [comment]
I believe this has been fixed in the latest version
